### ISSUE TITLE
Consider lowering single line Overrides propery with "Initialiser".

### ISSUE THREAD

**Issue by AdamSpeight2008** [dotnet/vblang#150]
Roslyn Issue: dotnet/roslyn#21457
The following piece of code isn't doing *in my opinion* most will expect.
[VisualBasicConversionExpression.vb Line: 18](
http://github.com/dotnet/roslyn/blob/3f1185b032aa2b3b75d72c6f16846fcdb0ab96c5/src/Compilers/VisualBasic/Portable/Operations/VisualBasicConversionExpression.vb#L18)
```vbnet
Public Overrides ReadOnly Property Conversion As CommonConversion = ConversionInternal.ToCommonConversion() 
```
That of over ridding the base implementation.

Question is should VB allow it and do the expected `overrides` ?
Essentially getting lowered to
```vbnet
Public Overrides ReadOnly Property Conversion As CommonConversion
  Get
    Return ConversionInternal.ToCommonConversion() 
  End Get
End Property
```

**Comment by Echo-8-ERA** [comment]
I wouldn't expect that. I would be expecting ConversionInternal.ToCommonConversion() to be called once, at object creation, just like as if it were a field instead of a property declaration.

**Comment by AdamSpeight2008** [comment]
@Echo-8-ERA The actual code used for the lowering isn't set in stone, the issue is more about the property not seeming to be initialised correctly, because the base-class could initial the property first and not being re-initialise in the derived-class.

An alternative lowering.
```vbnet
Private ReadOnly m_Conversion As CommonConversion = ConversionInternal.ToCommonConversion() 
Public Overrides ReadOnly Property Conversion As CommonConversion
  Get
    Return m_Conversion
  End Get
End Property
```
