### ISSUE TITLE
`Out` arguments

### ISSUE THREAD

**Issue by AnthonyDGreen** [dotnet/vblang#152]
This proposal addresses scenario #67.

``` VB.NET
Dim result As Integer
If Integer.TryParse("123", Out result) Then
    ...
End If
```

I propose that VB allow you specify the keyword `Out` on any argument in an argument list that corresponds to a `ByRef` parameter. If `Out` is specified by the user, definite assignment analysis will consider that use to be a write instead of a read/write. This will avoid the compiler reporting a warning that an unassigned variable is being passed `ByRef`. Unlike implementing full on `Out` parameter support in the language this proposal only adds a new way for the end-user to signify their _intent_.

This proposal **does not**:
1. Cause any new variables to be introduced.
2. Validate that the parameter being passed to is actually decorated with the `<Out>` attribute.
3. Suppress redundant initialization of the variable; VB variables continue to be initialized to the default value for their type by definition.
4. Give any special syntax to allow one to specify in a method declaration that a parameter is intended as an output nor does it add any additional analysis to ensure that parameters manually decorated with the `<Out>` attribute assign such parameters.
5. Suppress copy-in semantics for passing properties `ByRef`, late-bound calls, or `ByRef` arguments with implicit conversions; the current value of the variable, value, or property is still passed in.
6. Cause any new warnings or errors to be reported when passing `ReadOnly` fields or properties, or values as `Out` arguments even though doing so is utterly useless.

**Comment by jrmoreno1** [comment]
Have you looked at https://github.com/dotnet/roslyn/issues/13558?  It is somewhat similar.  It gives parity with C# and is in my opinion more VBish.

**Comment by AdamSpeight2008** [comment]
@jrmoreno1   dotnet/roslyn#13558 isn't the same as this proposal.

**Comment by jrmoreno1** [comment]
@AdamSpeight2008: no it's not the same, but I don't see why it shouldn't/couldn't be rolled into 13558.  One could argue that it doesn't address the difference between read/write and write, but since it's optional I don't see why adding it shouldn't be taken as a flag saying "don't nag, I know what I am doing".

**Comment by ericmutta** [comment]
> @AnthonyDGreen Unlike implementing full on Out parameter support in the language

By the way, will we be getting that full support soon? It would make using all the `TryXXX` methods so much nicer  (e.g. Dictionary.TryGetValue and Integer.TryParse).

**Comment by AnthonyDGreen** [comment]
@ericmutta not sure. We're not too keen on making `Out` parameters (on the declaration side) first class now that tuples are here and more directly address the scenario of multiple return values _and_ work with `Async`. As for implicitly declared `Out` argument variables we're not too keen on inline assignment in general and want to see how the scoping rules we picked for C# play out before committing VB here. Personally I'd be more interested in something like what F# does with Try methods.

**Comment by AnthonyDGreen** [comment]
The VB LDM looked at this issue on August 23rd and decided we like the idea of just recognizing the attribute on the parameter and correctly suppressing the warning without adding any new syntax. This also saves syntax for `Out` vars if we decide to do them. So I guess this proposal is rejected.

**Comment by AdamSpeight2008** [comment]
We'd also need to check that the parameter is assigned to within the method.

@AnthonyDGreen @KathleenDollard
I prefer the having the modifier present at the **usage site** as it makes it explicit that you're declaring a new variable into the environment, rather being implicit.
 Imagine `Go to definition` sending you to the parameter of a function. It would be confusing, I'd be thinking *did the IDE make mistake*.  Whereas having the modifier present, it could indicate that this the definition / declaration.

If we could introduce a couple of new nodes
  * `ExtendedArgumentSyntaxNode` inheriting from `ArgumentSyntaxNode`.
    * A base class for defining syntax the extend the definition of an argument.
    * eg `OutArgumentSyntaxNode Inherits ExtendedArgumentSyntaxNode`
  * `BoundExtendedArgument Inherits BoundArgument` 
     * `BoundOutArgument Inherits BoundExtendedArgument` 
       * We could attach the declaration to it, via the compiler.
