### ISSUE TITLE
broken link

### ISSUE THREAD

**Issue by birbilis** [dotnet/vblang#153]
the http://vblang.org link mentioned at the title/description of this repo is broken, tries to take one to http://msdn.microsoft.com/vstudio/roslyn which fails with a "The connection was reset" in Firefox

**Comment by AnthonyDGreen** [comment]
Thanks for filing this. I'm working with the domains team to get this pointed to the right place, wherever that might be.

**Comment by AnthonyDGreen** [comment]
Until such time as we have a proper website VB-specific website to link to I have removed said link from the description.

Regards,

**-ADG**
