### ISSUE TITLE
IDEA: global/shared import alias types.

### ISSUE THREAD

**Issue by ericmutta** [dotnet/vblang#158]
When looking over code I wrote a million years ago I was pleasantly surprised to find I can do this in VB:

```vb
Imports MyType = Foo.Bar.ReallyLongGenericClassName(Of Foo.Bar.SomeOuterClass.SomeInnerClass)
```

However, the limitation is that MyType is only available in the source file where it appears which means you have to keep repeating this in every source file. VB supports project-level imports, but there's no way to use aliases with those. What if we could achieve that via:

```vb
Imports Shared MyType = ReallyLongFullyQualifiedNameHere
```

...and have the `MyType` alias type be available in all source files, the same way it would be if it was typed manually? Another possibility is to use the already-existing `Global` keyword:

```vb
Imports Global.MyType = ReallyLongFullyQualifiedNameHere
```

The rules would remain exactly the same, with one addition that if an imported alias type is declared global/shared it must be unique across the entire project.

@AnthonyDGreen what do you think? From a big picture perspective this is akin to C's [typedef](https://en.wikipedia.org/wiki/Typedef) keyword and if this is something that can be considered for VB, I would be happy to flesh out a larger proposal.

**Comment by AnthonyDGreen** [comment]
Hey @ericmutta ,

Fun (secret) fact. Even though that box appears to only take qualified names you can also use it to define aliases. I think we just parse it as if it's "whatever text follows the Imports statement". So I can do this:

![image](https://user-images.githubusercontent.com/10539978/30257145-bd6e7782-9664-11e7-98e3-19071cf779b2.png)

And then use those aliases in code today:

![image](https://user-images.githubusercontent.com/10539978/30257158-d6c5965c-9664-11e7-9c18-ea1219001a63.png)

Isn't VB awesome!?

**Comment by AnthonyDGreen** [comment]
Indeed that is what the compiler does. Here's [the section of code that parses the global imports](http://source.roslyn.io/#Microsoft.CodeAnalysis.VisualBasic/OptionsValidator.vb,27).

**Comment by ericmutta** [comment]
> @AnthonyDGreen Isn't VB awesome!?

Hahahaha, this is unbelivably cool! I have no idea why I didn't think to try it! 17 years of VB and it still surprises me just how flexible it is 😄
