### ISSUE TITLE
feature request: Redeclare variable bindings

### ISSUE THREAD

**Issue by ericshawlinux** [dotnet/vblang#161]
In rustlang you can do this because they have bindings which can go out of scope when redeclared.

For example:
```
Dim Phones As String() = GetPhones()
' (use Phones as string array)
' After the following redeclaration, the string array will become inaccessible
Dim Phones As New PhoneCollection(Phones)
' (use Phones as an object)
```

**Comment by craigajohnson** [comment]
What would the benefit be? On initial thought I would prefer this not be allowed (partially on grounds of readability - following a code base would now require careful checking of redeclarations), or, at the least, protected behind something like an Option Redeclare On directive. Would this also invalidate Set Next Statement if you attempt to return back to a line in a block before the current variable was in scope?

**Comment by franzalex** [comment]
This is a definite no no!

There is a reason VB.NET is a statically typed language. Besides, what *really useful* purpose would this serve?

**Comment by ericshawlinux** [comment]
> Would this also invalidate Set Next Statement if you attempt to return back to a line in a block before the current variable was in scope?

If you were to make a new binding within a block, the binding should go out of scope at the end of the block and restore the binding of the parent scope.

> Besides, what really useful purpose would this serve?

Sometimes the same name can accurately describe two or more different variables used one after the next. Many people find that it is easier to focus when there are less names in the code.

I personally find myself wanting to rebind often, but instead I use PhonesStrArr and PhonesObj etc.

**Comment by Echo-8-ERA** [comment]
I'd say that if your method is big enough that it's actually useful to repurpose  an identifier, you should be looking into doing some refactoring to break up the method into smaller parts.
