### ISSUE TITLE
[Proposal] Allow math functions on enums

### ISSUE THREAD

**Issue by ptoye** [dotnet/vblang#185]
VB allows some math and bitwise operators on enums. So why not also allow max, min? It's totally inconsistent.

I agree that enums with the Flags attribute need bitwise operations, but equally those without need arithmetic, at least to compare them.

**Comment by reduckted** [comment]
>  ...at least to compare them.

Not sure what you're getting at here. You can already compare enum values.

```vb
Public Enum MyEnum
    First
    Second
    Third
End Enum

Public Class Foo
    Public Sub Bar()
        Dim a As MyEnum = MyEnum.First
        Dim b As MyEnum = MyEnum.Second

        If a < b Then
            ' ...
        End If
   End Sub
End Class
```

And adding enum values... what would this result in?

```vb
Dim z = MyEnum.Second + MyEnum.Third
```

The answer is currently `3`, but there's no enum member with a value of `3`. In that example, `z` is an `Integer`. Are you proposing that it becomes `MyEnum`?

As for min and max, I assume you're referring to `Math.Min()` and `Math.Max()`. There's already an issue for that over at dotnet/corefx#11555

**Comment by ptoye** [comment]
I hadn't realised that there was already an open issue. Thanks for pointing it out. I posted my original comment several years ago, and can no longer remember the specific problem that I had. It's even possible that the VB has changed since I posted it!
