### ISSUE TITLE
[Proposal] New type comparison keywords

### ISSUE THREAD

**Issue by brandonhood** [dotnet/vblang#188]
Issue created for pull request:
https://github.com/dotnet/vblang/pull/187

EDIT:
The pull request is just to add the proposal; there's no implementation yet. This proposal is for adding two new contextual keywords (```A``` and ```An```) to VB for more readable type-checking for object instances.

**Problem:** Type-checking is confusing to a VB newcomer due to two similar but totally different language operators - ```GetType(TypeName)``` and ```TypeOf(obj)``` - as well as ```obj.GetType()```, courtesy of .NET. The type-comparison expression for object instances - ```TypeOf obj Is TypeName``` - is clunky even by VB standards, and that's _without_ regard to the fact that VB's "sibling" language has a ```typeof``` operator that is actually equivalent to ```GetType``` instead.

**Proposal:** Add two contextual keywords to be used in type comparison expressions. I'm suggesting two because VB is intended to be typed and/or read easily by English speakers, and a human parser will stutter a bit on a blatant grammar violation 😄 
```
' This function is intentionally verbose to better showcase the keywords
Function IsStringOrInteger(param As Object) As Boolean
    If param Is A String
        Return True
    ElseIf param Is An Integer
        Return True
    End If
    Return False
End Function
```

At the moment, I and many others see VB as an extremely ugly C# due to the feature parity they have although the gap is widening a bit. Language changes like this are, imo, in the spirit of VB.

**Downsides:** Admittedly, this proposed feature is entirely redundant due to the existence of the ```TypeOf``` operator. This is strictly syntactic sugar.

**Comment by AdamSpeight2008** [comment]
@brandonhood  Could you provide a description of the issue and what solution the pull request  provides.

**Comment by brandonhood** [comment]
@AdamSpeight2008 Updated!

**Comment by zspitz** [comment]
Are you suggesting that misuse of `A` and `An` be a compiler error?
```vb
If param Is An String
    Return True
ElseIf param Is A Integer
    Return True
End If
```

**Comment by brandonhood** [comment]
@zspitz I don't think you're giving ESL users enough credit. The indefinite article is pretty simple to figure out. 

However, this made me remember that there are some mismatched a/an cases (e.g. "hour" and "European," courtesy of Wikipedia) that would fog this up a bit. Not that it matters; this issue's amassed three thumbs down in nearly 5 months, so I doubt any decision about semantics will affect its fate 😛
