### ISSUE TITLE
Show generated code.

### ISSUE THREAD

**Issue by Bill-McC** [dotnet/vblang#199]
Considering #196 , and #194, #198; I'd like to be able to have the IDE show compiler generated code in situ where possible with remnants in a compiler generated region.
This would allow expanding an auto prop, and setting breakpoints inside part of the generated code .
Ideally there should also be an edit icon ✏️ or similar that when clicked adds the generated code to the user code.

**Comment by CyrusNajmabadi** [comment]
This is not really related to the vblang, but the tooling around it. As such, this should go to dotnet/roslyn
