### ISSUE TITLE
Notifying Property Modifiers

### ISSUE THREAD

**Issue by AdamSpeight2008** [dotnet/vblang#202]
I propose we make available an additional *modifiers* the indicates the property will implement `INotifyPropertyChanged` and/or `INotifyPropertChanging` when compiled.
 * `NotifyChanging` autoimplement `INotifyPropertyChanging`.
 * `NotifyChanged` autoimplements `INotifyPropertyChanged`

These would also verify that when the user, uses the fully expanded form of property, that they implement the raising of the events.
```
Public Property Name As String
  Get
  End Get
  Set(value As String)
  End Set
End Property
```
-------

**Example**

```vbnet
Public Class EditorViewModelTraditional
  Implement INotifyPropetyChanged

  Public Event PropertyChangedEvent As PropertyChangedEventHandler Implement INotifyPropertyChanged.Changed

  Private _MainDocument As String
  Public Property MainDocument As String
    Get
      Return _MainDocument
  End Get
  Set( value As Document)
    If Not Object.Equal( value, _MainDocument) Then
      _MainDocument = value
      RaiseEvent PropertyChanged(Me, New ProperyChangedEventArgs(NameOf(MainDocument))(
    End If
  End Set
End Property
'...
End Class
```
Could be rewritten as
```vbnet
Public Class EditorViewModelTraditional
  Implement INotifyPropetyChanged ' Auto implement, if not existing

  ' Auto impemented, if not existing
  Public Event PropertyChangedEvent As PropertyChangedEventHandler Implement INotifyPropertyChanged.Changed

  Public NotifyChanged Property MainDocument As String

'...
End Class
```
or just
```vbnet
Public Class EditorViewModelTraditional
  Public NotifyChanged Property MainDocument As String
'...
End Class
```
We could also have

**Comment by franzalex** [comment]
I really like how issues do with `INotifyPropertyChanged` has gathered so much traction. However, there are now three different issues that are more or less about the same thing. 

 > [`WithPropertyEvents` modifier to enable easy INotifyPropertyChanged implementations #194](194)
 > [Bindable Classes and Properties #198](198)
 > #202 (this issue)

It is my thought that all ideas should be put together into one thread in order that all discussions and/or suggestions be centralised to save the trouble of repeating one's self across these three threads and any others that may come up in future.

**Comment by AnthonyDGreen** [comment]
#107, #194, and #198 are three very different approaches to addressing the same scenario. This seems like it's just #198 with a different modifier. If you want to suggest a tweak to one of those designs please do it on one of those threads.
