### ISSUE TITLE
Introduce variants of 'Friend' visibility/scope.

### ISSUE THREAD

**Issue by ericmutta** [dotnet/vblang#203]
When implementing complex classes, it is quite common to break up their functionality into helper classes that are nested in the class they help (e.g. you can see this all over the .NET collection classes such as [here](http://referencesource.microsoft.com/#mscorlib/system/collections/generic/list.cs,1042) and [here](http://referencesource.microsoft.com/#mscorlib/system/collections/generic/list.cs,1140)).

Sometimes, you want special access control and right now the rule is that nested classes can access private members of their containing classes:

```vb
Public Class MyBigComplexClass
  Private SomeField As Integer

  Public Class MySmallHelperClass
    'the field MyBigComplexClass.SomeField is accessible in here.
  End Class
End Class
```

**However, we currently have no way of saying that a member of a nested class should be private to its containing class**:

```vb
Public Class MyBigComplexClass  
  Public Class MySmallHelperClass
    Public SomeField1 As Integer 'accessible beyond assembly.
    Friend SomeField2 As Integer 'accessible within same assembly.
    Private SomeField3 As Integer 'accessible only in MySmallHelperClass
  End Class
End Class
```

We may need a new keyword (or combination of existing keywords) for a scope that means "visible to me and the type(s) that contain me":

```vb
Public Class MyBigComplexClass  
  Public Class MySmallHelperClass
   'this retains the meaning of Friend, i.e visible everywhere inside this assembly.
    Public Friend SomeField1 As Integer

   'this is new and means visible only to outer types (i.e MyBigComplexClass).   
    Private Friend SomeField2 As Integer 
  End Class
End Class
```

...in other words we say `Friend` is short for `Public Friend` and retains its current meaning, then introduce `Private Friend` as a variant that limits the "friendship" access to the outer type(s) rather than the entire assembly.

The actual syntax, keywords, etc does not matter much, the important thing is the scope semantics.

CC: @AnthonyDGreen

PS: without this scope the only way to hide implementation details of public nested classes is to make the nested class private, then make its members public so the outer class can access them, then use an interface for the parts that should be visible outside the outer class. It's way too much work!

**Comment by AnthonyDGreen** [comment]
Given the narrowness of the scenario wouldn't this better be implemented using an analyzer?

**Comment by ericmutta** [comment]
> @AnthonyDGreen Given the narrowness of the scenario...

I would like to make the case that the scenario is in fact broad and appears in **pretty much every non-trivial API for public consumption**.

The outline of the scenarios is as follows:

1. You have a manager/controller component that provides the API. This is the outer class.
2. You have objects controlled by the manager/controller component. This is the nested class.
3. The managed objects have some public parts that should be visible to the user of the API.
4. The managed objects have some internal parts that should be visible only to the manager/controller.

Requirement number 4 is what could be made easier by compiler support for a scope like `Private Friend` as I suggested earlier.

Some concrete examples:

- You have a `WindowManager` (the outer class) and some `Window` objects (the nested class). Window objects have public parts (e.g title, location, dimension) that should be visible to the user. Window objects have internal parts (e.g. the frame buffer for the window's pixels) that should be visible only to the `WindowManager` since they are implementation details.

- You have a `DbTransactionManager` (the outer class) and some `DbTransaction` objects (the nested class). Transaction objects have public parts (e.g. the list of SQL operations to perform) that should be visible to the user. Transaction objects have internal parts (e.g. the socket connection to the DB server) that should be visible only to the `DbTransactionManager` since they are implementation details.

Without support for `Private Friend`, there are several (sub-optimal) ways to implement the above APIs:

1. Make the internal parts of managed objects `Public` so the outer manager class can use them. This makes implementation easy but exposes implementation details which is bad.

2. Make the managed objects completely opaque by returning integer handles (the Win32 API does this). Provide functions to change the public parts when given a handle (e.g [SetWindowText](https://msdn.microsoft.com/en-us/library/windows/desktop/ms633546(v=vs.85).aspx)). The internal parts are hidden because the handle is opaque. This works but now you have to implement a handle table and every operation requires a look-up in that table which hurts performance.

3. Make the managed objects mostly opaque by returning them as `Object` references. The public parts can be changed by functions that take those objects, `DirectCast` them to the appropriate type, then access the needed parts directly. This eliminates the complexities/performance issues of a handle table but makes the interface awkward (i.e less object-oriented) and compromises type safety with all the casting.

4. Define a seperate Interface that the nested (managed) class implements. This interface has all the public parts. The nested class is made private inside the outer (manager) class so the outside world can't touch it, but all its members are public so the manager class can access them directly. The public parts are accessed via the interface (keeping the object-oriented feel) and the private parts are accessed by `DirectCast` to an instance of the nested class. This has the overhead of defining and using an interface and still has some type safety issues because of the casting required.

With support for `Private Friend` (or whatever keyword ends up being used) we would have the encapsulation (so outside world can't touch internal parts), the accessibility (so outer manager class **can** touch the internal parts), the performance (no handle table lookups), the brevity (no interface to define and implement) and the type safety (no casting).

I hope I have made a convincing enough case and welcome feedback!

**Comment by AnthonyDGreen** [comment]
But you omitted the option of just making the members of `Window` or `DbTransaction` members `Friend`. The only drawback being that other parts of your program can see those members. Which usually comes down to a lack of discipline or trust with _other members of the team_ who just call whatever methods they can see because they're lazy n00bs. 

We get requests like this a lot. People who want to use `Friend` visibility but only with certain classes, either the containing class or "just these three classes here", or "classes in this namespace", or "but not 'Friend Assemblies' with `InternalsVisibleTo` access", or "private but only called from this one method or these two methods". These something that can be enforced through an analyzer. You can limit who can call what by name, namespace, containing, first three letters, whatever.

The other problem is, that this isn't a real CLR accessibility level, like the others. So how would this modifier actually appear in metadata? It would probably have just `Friend` level access.

Lastly, the .NET Class Library guidelines generally [discourage the use of nested types](https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/nested-types):

> X DO NOT use public nested types as a logical grouping construct; use namespaces for this. 
> X AVOID publicly exposed nested types. The only exception to this is if variables of the nested type need to be declared only in rare scenarios such as subclassing or other advanced customization scenarios. 
> X DO NOT use nested types if the type is likely to be referenced outside of the containing type. 
> For example, an enum passed to a method defined on a class should not be defined as a nested type in the class. 
> X DO NOT use nested types if they need to be instantiated by client code. If a type has a public constructor, it should probably not be nested. 
> If a type can be instantiated, that seems to indicate the type has a place in the framework on its own (you can create it, work with it, and destroy it without ever using the outer type), and thus should not be nested. Inner types should not be widely reused outside of the outer type without any relationship whatsoever to the outer type. 

So for the majority of class libraries the problem is more likely to be limiting `Friend` visibility between two peer classes, which this accessibility modifier won't solve. But, what you could do is something like this:

``` VB.NET
Class WindowManager

End Class

' Analyzer enforced.
<Friends(GetType(WindowManager))>
Class Window

End Class
```

That would have all the same effect as a new modifier, and be a general (and generalizable) solution to the problem regardless of whether the classes are sibilings or have a nesting relationship. Does that make sense?

**Comment by ericmutta** [comment]
> @AnthonyDGreen Does that make sense?

This makes a lot of sense actually, thanks for taking the time to respond in depth!

I especially like the simplicity of using Friend then either adding an analyzer to check proper usage, or even better, just isolating the code in an assembly by itself (any "manager" type thing like a window manager or transaction manager is likely to be large enough to warrant being in its own assembly).

I am also yet to use any library that employed analyzers (are they enabled for VS Community edition?) so I hadn't thought of those and will definitely look into them some more, thanks for the pointer.

(You can close this when done).
