### ISSUE TITLE
Option strict on source level

### ISSUE THREAD

**Issue by tverweij** [dotnet/vblang#206]
In VB.Net, we have option Strict on project level and on file level.
It should be nice to have it on source level too:

Option Strict On
Public Class x
Private f as string = "123"
#Option Strict OFF
Private f2 as string = 123 'this will compile
#Option Strict ON
Private f3 as string = 123 'this won't compile

**Comment by reduckted** [comment]
#117

**Comment by paul1956** [comment]
Your example has a simple workaround just cast 123 but  this would be useful because as I have reported in #23367 (repeated below) sometime valid code will not compile depending on state of Option Strict and Option Infer and there is no easy workaround that don't change the original code..
```
Option Strict Off or On
Option Infer Off or On
        Friend Overloads Shared Function GetUnificationUseSiteDiagnosticRecursive(Of T As TypeSymbol)(types As ImmutableArray(Of T), owner As Symbol, ByRef checkedTypes As HashSet(Of TypeSymbol)) As DiagnosticInfo
            For Each t In types '            For Each t As T In types '***** This line is the issue
 
            Next
            Return Nothing
        End Function
```

**Comment by tverweij** [comment]
@paul1956 
It was only an example - in real world I work with Option Strict On except for cases where late-bound is needed - mostly one or two lines in a complete file. 
And at this moment this means that I have to use Option Strict Off for all code, just to be able to add those two lines.
@reduckted 
Indeed, this is a duplicate of #117 - my apologies.

**Comment by paul1956** [comment]
@tverweij I agree it would be very useful, I always use Strict On and Infer Off and continue to run into issues on one line in a file where this would help. My workaround today is to flip the Options get rid of all the errors **I can** (using codefix) and then flipping the Options back and hoping no one ever touches the file again.

**Comment by tverweij** [comment]
Closed - duplicate of 117
