### ISSUE TITLE
Type aliases

### ISSUE THREAD

**Issue by tverweij** [dotnet/vblang#208]
To get more readable code it would be nice to have type aliases.

Example
`Function CalculateSpeed(distance as Double, elapsedTime as Integer) as Double`

Would be much more readable as:
```
Alias Miles = Double
Alias Seconds = Integer
Alias Kmh = Double

Function CalculateSpeed(distance as Miles, elapsedTime as Seconds) as Kmh
```

This would make refactoring also much easier; if I decide that seconds should be a Double instead of an Integer, I only have to change the Alias and all instances of Second are changed.

At this moment It can be done at the file level:
`Imports Foo = System.String
`
But it should be nice to have this at any level (even project level if defined in a module).

**Comment by reduckted** [comment]
This can already be done today.

At the file level, like this:

**Calculator.vb:**
```vb
Imports Kmh = System.Double
Imports Miles = System.Double
Imports Seconds = System.Int32

Class Calculator

    Function CalculateSpeed(distance As Miles, elapsedTime As Seconds) As Kmh
        ' ...
    End Function

End Class
```
Or at the project level, like this:

**MyCalculator.vbproj:**
```xml
<Project>
  <!-- ... snip ... -->
  <ItemGroup>
    <Import Include="Kmh = System.Double" />
    <Import Include="Miles = System.Double" />
    <Import Include="Seconds = System.Int32" />
  </ItemGroup>
  <!-- ... snip ... -->
</Project>
```

You can even enter those imports via the UI. Just open _My Project_, then select _References_, then in the _Imported namespaces_ section, enter "Kmh = System.Double".

As a side note, you may also be interested in #120 (Units of Measure)

**Comment by tverweij** [comment]
I did no know the last one. But it is not easy to maintain; as soon as you added it in the UI, you can not change is anymore (except by opening the project file and change is manually in the project xml).
You can also not refactor on project level by rename change kmh to KmPerHour.
And it cannot be done at method level.

**Comment by AdamSpeight2008** [comment]
@tverweij  This loses the "unit type-safety" of #120, eg It does prevent you adding `Seconds` to `Metres`

**Comment by tverweij** [comment]
@AdamSpeight2008 
It doesn't have to be units - it can be anything. The units are only as example.
And there must be a way to easy refactoring, if only to correct a mistake (defined secods instead of seconds; an error is easy made - typing error or complete wrong word - as English is not my first language, while my source code must be in English).

**Comment by tverweij** [comment]
That would help a lot.
But class level and method level would be handy.

**Comment by KathleenDollard** [comment]
I am reopening most of the issues this user closed on their exit. 

I am not reopening this issue as it is a shortcut to existing functionality and did not get additional support.
