### ISSUE TITLE
Where to report VB Compiler bugs/Issues

### ISSUE THREAD

**Issue by paul1956** [dotnet/vblang#220]
I have reported multiple VB compiler bugs in Roslyn GitHub #23367, #23099, #23019, #22788, and most are market Language-VB or Area-Compilers 

Does that mean they are being looked at or are transferred here or something else because going back to 2015 most just sit there (even some that are fixed).

I assume VB issue with Roslyn Sample code is handled in Roslyn Repo, correct

**Comment by AnthonyDGreen** [comment]
The Roslyn repo is the correct place to file compiler issues. @jcouv and @jaredpar are members of the compiler team and if one of them has tagged an issue with "Area-Compilers" that means it's recognized as a compiler issue. The process of scheduling when the bug will be investigated or fixed depends on the severity and what other issues we're fixing at that time. Some of the issues you've listed are poor error experiences, which aren't as severe as crashes and the like, so they may take longer to get to. None of the issues you've listed have been closed so at some point the bug will be assigned. If there's a particular issue you haven't heart back on in a while free to ping any @jaredpar @jcouv or myself in a comment on that issue and we'll give you an update on its status, if any is available.

Sorry for the confusion and thanks for your patience.
