### ISSUE TITLE
VB Support for C# pattern variables

### ISSUE THREAD

**Issue by paul1956** [dotnet/vblang#246]
It is very difficult (beyond my ability) to convert C# Pattern Variables to VB using Roslyn even for the simplest cases. The conversion for the most used case is easy for a human but if VB supported at least the simple case shown below it would be wonderful.
              
```
if (ModelExtensions.GetSymbolInfo(semanticModel, node).Symbol is IMethodSymbol methodSymbol && methodSymbol.ReturnType.Equals(ModelExtensions.GetTypeInfo(semanticModel, node).ConvertedType))
```
Converts to
```
 If TypeOf ModelExtensions.GetSymbolInfo(mSemanticModel, node).Symbol Is IMethodSymbol Then
    Dim methodSymbol As IMethodSymbol = CType(ModelExtensions.GetSymbolInfo(mSemanticModel, node).Symbol, IMethodSymbol)
    If methodSymbol---.ReturnType.Equals(ModelExtensions.GetTypeInfo(mSemanticModel, node).ConvertedType) Then
        Return SyntaxFactory.InvocationExpression(MemberAccessExpressionSyntax, SyntaxFactory.ArgumentList())
    End If
End If
```
If this is not planned a pointer on how to do this conversion using Roslyn would really be helpful. I have a VisitIsPatternExpression routine and I can detect the case and even build most of the code up to the ---symbols shown above as a comment but a complete solution and replacement is stumping me.

**Comment by reduckted** [comment]
This doesn't answer your question, but a slightly more efficient way of writing the converted code would be:

```vb
Dim methodSymbol As IMethodSymbol

methodSymbol = TryCast(ModelExtensions.GetSymbolInfo(mSemanticModel, node).Symbol, IMethodSymbol)

If methodSymbol IsNot Nothing Then
    ' ...
End If
```

**Comment by AdamSpeight2008** [comment]
I think you can also do the following.
```vbnet
Dim methodSymbol= TryCast(ModelExtensions.GetSymbolInfo(semanticModel, node).Symbol, IMethodSymbol)
If method?.ReturnType.Equals(ModelExtensions.GetTypeInfo(semanticModel, node).ConvertedType)) Then

End If
```

**Comment by paul1956** [comment]
That I can work with thanks.

**Comment by paul1956** [comment]
I know I closed this and maybe I should open another issue but I am stuck at a small detail. When I return from the visitor I have the second line as
```
If methodSymbol.ReturnType.Equals(ModelExtensions.GetTypeInfo(semanticModel, node).ConvertedType)) then
```
But I am missing the required ? after methodSymbol I know I need to do some kind of replacenode() but the syntax is stumping me. I have everything between the "If " and " Then" in a SyntaxNode of type ExpressionSyntax. For starters what is the "?"

**Comment by reduckted** [comment]
This seems a bit off topic for this repository. Maybe asking on StackOverflow would be a better option.

**Comment by paul1956** [comment]
I asked for VB support C# pattern variables, the rest was about a workaround until I get it. But I will close and ask elsewhere. Please don't lose the original request.
