### ISSUE TITLE
VB support for end of line comments in more places

### ISSUE THREAD

**Issue by paul1956** [dotnet/vblang#249]
Any chance of VB every supporting comments after _ continuation character? It would be great to be able to do the following and I don't see it as a breaking change since today nothing except a CFLF is allowed after the _. Being able to have variable spaces between _ and ' is extra credit.
```
Dim x = AnyFunction(1, _  ' 1 means ...
                    2 , _ ' 2 means ...
                    3 )   ' 3 means ...
Dim LettersOfEnglishAlphabet as String = "A"  & _ ' First Letter
                                         "B' & _ '  Second Letter
                                         "Z" '      Final Letter
```
as well as many other use cases

**Comment by AdamSpeight2008** [comment]
@paul1956 You're welcome to add it to the list of places to add comment in #41

**Comment by AdamSpeight2008** [comment]
Also a possible duplicate of #65

**Comment by rskar-git** [comment]
This is legal syntax (certainly since VS 2015):

        Dim x = AnyFunction(1,   ' 1 means ...
                    2,  ' 2 means ...
                    3)   ' 3 means ...
        Dim LettersOfEnglishAlphabet As String = "A" &  ' First Letter
                                         "B" &  '  Second Letter
                                         "Z" '      Final Letter

I think the underscore for line continuation is now mostly seen as something archaic and to be avoided where possible.

**Comment by paul1956** [comment]
@rskar-git the first example in not currently legal, yes the second is legal and I missed it, thanks.


I don't care about the _ I just thought it was needed to avoid a breaking change. I will add this to the other proposals.

I will add the first to #41

**Comment by rskar-git** [comment]
@paul1956 The first example is legal syntax; what I put up there was a copy/paste from an actual VB project that compiles it and runs it. Parenthetically, for `AnyFunction`, I did:

    Function AnyFunction(x As Integer,y As Integer,z As Integer) As Integer
        Return x+y+z
    End Function

So, I promise you, the first example is legal syntax! Well, at least it is for the Visual Basic 2015 that comes with Microsoft Visual Studio Professional 2015, Version 14.0.25123.00 Update 2, Microsoft .NET Framework Version 4.6.01055.

**Comment by reduckted** [comment]
Both examples are currently legal as long as you remove the line continuation marker (which can become implicit), and fix the typo in the second example where a closing `"` was left out:

```vb
Dim x = AnyFunction(1, ' 1 means ...
                    2, ' 2 means ...
                    3) ' 3 means ...
                     
Dim Letters As String = "A" & ' First Letter
                        "B" & ' Second Letter
                        "Z"   ' Final Letter
```

**Comment by paul1956** [comment]
@reduckted Thanks I think I the code being generated had some small issues some you caught. The & was being put on the next line (like C# allows with +) and a few other issues. Now that I know how it is supposed to work I can make use of this feature.

**Comment by tverweij** [comment]
Solved in project Mercury

**Comment by markhealy88** [comment]
Has this regressed in VS 16.5.4?
