### ISSUE TITLE
[Noodling] Abstract Digit(s) Parsing and Validation

### ISSUE THREAD

**Issue by AdamSpeight2008** [dotnet/vblang#254]
Rather than a Numeric Literal being tied to specific type, should we simply treat it as a sequence for digit characters. Then do the calculation of the value, and typing to the specified type at a higher level like binding.  
We allow use the explicit write all of the values `.MinValue` to `.MaxValue`

Eg 
`Dim b As Byte = 10`
 Isn't treated as 
 `Dim b As Byte = CByte(CInt(10) )`
 but as  byte is directly constructed with value `10`

*Rough layout out syntax nodes*
```
Enum DigitKind
  None = &B0000
  Sep  = &B0001
  Bin  = &B0010
  Oct  = 8
  Dec  = 10
  Hex  = 16
End Enum

Abstract Syntax DigitChar
  '...
End Syntax

Syntax DigitSeperator : DigitChar
  ''''
End Syntax

Syntax Digit : DigitChar
  Digit As ' ...
  Kind  As DigitKind
End Syntax

Syntax Digits
  Digits    As SyntaxList(Of DigitChar)
  DigitKind As DigitKind
End Syntax
```

**Comment by gafter** [comment]
What problem are you trying to address? How would this affect the behavior of a program that contains a literal?

**Comment by AdamSpeight2008** [comment]
@gafter I am conceptually thinking that this is syntactically below the level of literal.
Initially we treat it as sequence of numeric character (including separators).  
Let's say we have the following ` 1.23E-45` which conceptually is `1.23 * (10 ^ -45)` 
*Did you know that `-` minus sign isn't considered as unary minus)*

Instead we should syntactically parse it as separate tokens
```
 DigitChars DecimalPoint DigitChars ExponentSymbol Sign DigitChars 
```
Into the following syntax tree
```
             ExponentSymbol
            /              \  
         DecimalPoint       \
        /          \         \
     DigitChars  DigitChars   \
    /                      DigitChars
 Sign?                    / 
                        Sign?
```

Hence posting on the language repository initially.

**Comment by gafter** [comment]
@AdamSpeight2008 Why would we want to change anything here? More to the point, why would we want to make the compiler depart from the VB language specification, which says that [a floating-point literal is a single lexical token](https://github.com/dotnet/vblang/blob/master/spec/lexical-grammar.md#lexical-grammar)?

**Comment by AdamSpeight2008** [comment]
That's doesn't mean it has to stay to way in the future. 
We could have sub-lexical tokens, within literals or other tokens and still preserve semantic meaning.
It could open up other features, like Tagged Strings
Prior art, like the JSON parser by CyrusNajmabadi.
Imagine if we could extended / add additional sub-syntactic on tokens, especially strings. 
*So my thinking is if it can be done to the "core" literals / tokens in the language, it can be done to higher conceptual tokens.*

**Comment by gafter** [comment]
@AdamSpeight2008 I don't see a language proposal in what you're suggesting.

**Comment by AdamSpeight2008** [comment]
That's because it hasn't happened yet, doesn't mean we should terminating so early. 
*It's not like a member of `Roslyn` team is wasting their time doing the exploration. Is it?*
Just kinda make the VB language community aware that someone is look in this particular area *(possibly with a link to their fork, which discussion on it will happen)* of the language. 
If their exploration seem fruitful for them, they'll submit an "official" language proposal.

**Comment by gafter** [comment]
I have no idea what kind of proposal that exploration could lead to.

Generally, it feels like you have the process backwards. We don't design language features because we have some implementation ideas for the compiler. We design language features because programmers need them, and then we figure out how to implement them in the compiler.

**Comment by CyrusNajmabadi** [comment]
Closing out as this was explicitly rejected and the original filer has not clarified anything here.
