### ISSUE TITLE
Localised Compiler Options

### ISSUE THREAD

**Issue by AdamSpeight2008** [dotnet/vblang#255]
Alternative approach to #135 

```vbnet
Using Option Strict Off
  ' ...
End Using
```

**Comment by KathleenDollard** [comment]
Is the need for a separate partial class in a different file a real pain point for people?

It is TOTALLY cool to just ping an old issue with your comments and that should bubble up to the top. 

That's a fine syntax, but I have not thought much about it.  I just wonder if other things, like Await in Catch/Finally are bigger pain points.

**Comment by Bill-McC** [comment]
First of: confused re format of these discussions. Ironic really... is a partial class an issue? Is a partial solution to an issue an issue?
The pain point for me is when I know what kind or kinds of data are coming in, but they aren't "Typed". A block strict off doesn't address that, a dynamic or duck type does

**Comment by KathleenDollard** [comment]
Yes on discussions. GitHub stinks for discussion, but its what we've got. 

I think this issue is somewhat separate from yours because this one is strictly providing Option Strict in a narrower scope. But the separate file seems a hack, but a workaround.

**Comment by Bill-McC** [comment]
#255 partially addresses my scenario , but not as desirable as #106 or #43.  I'm not sure I see the difference between #255 and #117. There's a lot of suggestions around this, and a lot of overlap.  Thanks.

**Comment by KathleenDollard** [comment]
@AdamSpeight2008 Can you clarify why this isn't a duplicate of #117. I'd like to close it as a duplicate if it is.
