### ISSUE TITLE
NormalizeWhiteSpace removes most CRLF's

### ISSUE THREAD

**Issue by paul1956** [dotnet/vblang#258]
Before calling NormalizeWhiteSpace I have a "beautifully" formed program with CRLF in all the places I want them, including multiple CRLF's in places. After calling it most of _them_ are gone in a way I can't figure out. I am trying to shorten very long lines by breaking lines at OperandTokens and after all the formatting everything ends up back on one line. I only call NormalizeWhiteSpace once after all the changes. If I don't call it the code is all squished together with few white spaces and is not a valid source program.

**Comment by reduckted** [comment]
This seems like it belongs on the dotnet/roslyn repo.

**Comment by KathleenDollard** [comment]
I'm confused about why you are calling Normalize White Space as I believe what you are describing is what it is designed to do. 

Do you mean to be formatting your document? is there something not working in that?

**Comment by reduckted** [comment]
I believe he's referring to the roslyn function `NormalizeWhiteSpace`, which is why I suggested that it's not a VB language design issue, but rather a roslyn issue.

**Comment by paul1956** [comment]
It is a Roslyn issue particular to VB,  C# has much finer control over formatting, but I can post there. @KathleenDollard I am building formatted source code and there are a lot of issue with my formatting being ignored.  If I don't call NormalizeWhiteSpace I get a stream of characters jammed together except where I explicitly added returns. I am only formatting CRLF's not all the spaces in the text. NormalizeWhiteSpace does a lot of work making text look nice as long as you don't mind very long lines. Finding every place space is missing and adding the correct spacing on 1,000's of lines of lines of code is too much work.

I posted here because C# has CSharpOptions where some of this can be controlled but VB is missing VBOptions.

**Comment by AdamSpeight2008** [comment]
Are you able to provide an example of the code before, expected and actual? So we (I) can visualise what is happening.

**Comment by sharwell** [comment]
@paul1956 One way or another this is probably an issue to file on dotnet/roslyn. It's possible there is an API that better meets your needs, but like @AdamSpeight2008 mentioned it would be extremely helpful to see three things:

1. The original code (input)
2. The code you are trying to get (expected result)
3. The code you get back from `NormalizeWhitespace` (actual result)

**Comment by CyrusNajmabadi** [comment]
Closing out. This belongs in dotnet/roslyn (and
Could only go somewhere with an actual repro case)
