### ISSUE TITLE
Add the ability to add pictures to the source code

### ISSUE THREAD

**Issue by tverweij** [dotnet/vblang#259]
I would be very nice to have the ability to add pictures to the source code, so I can add pictures of requirements and flowcharts to the code, to make the code more understandable.

**Comment by bandleader** [comment]
While I appreciate the need, I don't think adding this to the **VB language** is a good idea. Source code files are plain text files and need to stay that way for many reasons (file comparison, source code control like Git, etc.)

A better idea would be to reference an image URL in a comment:
```vb
'Flowchart for this class: http://example.com/flowchart.png

Public Class MyClass
    [...]
```

Visual Studio *already* hyperlinks the URL so you can easily open the flowchart from within the code file.

What you may want to request they add is that hovering over the URL should show the image in the tooltip (and optionally open it in a VS tab if clicked). This would be an interesting suggestion for *Visual Studio*, and should be requested on the Visual Studio UserVoice. (You could also implement it yourself via an extension.)

**Comment by AdamSpeight2008** [comment]
Also [ImageComments](https://marketplace.visualstudio.com/items?itemName=MsBishop.ImageComments)

**Comment by tverweij** [comment]
@AdamSpeight2008 : I have that one, but it does not work very well...

@bandleader (and everyone else here):
For me, Visual Studio and Visual Basic is the same thing; VS without VB is nothing, VB without VS is nothing. Compiler and editor are just part of the same package. If I cannot edit well, I cannot program well. If it is not compiled well, I cannot program well, If the editor does not support enough, I cannot program well.
And the only thing I want is to program well. I do not want to get votes (VS Uservoice is based on votes, not on the content). If votes are important, you get stupid things like "bring VB6 back" instead of real important things. That's why I don't use the VS Uservoice, because it does not work at all.

**Comment by ericmutta** [comment]
> @tverweij That's why I don't use the VS Uservoice, because it does not work at all...And yes, I know - this will get at least one thumbs down.

I really understand your frustration with VS UserVoice. My experience with the .NET/Rosyln team here on GitHub has been EXCELLENT. They respond quickly even to the point of fixing issues during Christmas (thanks @jcouv for [#23297](https://github.com/dotnet/roslyn/issues/23927)!). I once reported what turned out to be an IDE issue, it went to UserVoice and they just eventually closed it.

If you get a thumbs down it is only because this repo already has a defined role: **VB language design issues.** Despite the negative experience with VS UserVoice that IS the **current place** for issues like this one...though I agree that in the long-term putting everything under GitHub will offer a better experience by giving us a central place to report issues touching on everything from the IDE down to the CLR itself 👍

**Comment by tverweij** [comment]
@bandleader 
> Source code files are plain text files and need to stay that way for many reasons

If the pictures are stored as base64 encoding like in emails, it would still be plain text.

**Comment by KathleenDollard** [comment]
@tverweij 

This request is as important for any other language as VB, and the Visual Studio folks aren't here. 

Have you tried the "Send feedback" option in VS? Would a better add-in meet your goal?

**Comment by tverweij** [comment]
@KathleenDollard 
>This request is as important for any other language as VB, and the Visual Studio folks aren't here.

That's true for a lot of things, but that does not mean everything is always implemented for everything - some times some languages have to wait to get the sugar.

What I propose is that the pictures are saved inside the VB file as a base64 string, making it part of the source code, and thus a VB-thing, where VB makes use of the WPF capability of the source designer.

About add-in's: They are nice, but it is hard to share code with others when the code needs add-in's. 
The only current add-in works with external saved pictures that are referenced by the code. To update a picture, you have to restart Visual Studio. Support and availability on the next version of VS is also a problem with add-in's (this one is also not official available for VS2017). I used several on VS2015, only a few of them are upgraded to VS2017. So I am very careful with the use of add-in's. 

And I tried the "Send Feedback" option of VS lots of times. Never with any results.
(Mailing with Anthony was the only thing that gave any results till now).

**Comment by tverweij** [comment]
Closed because this is not vblang.
