### ISSUE TITLE
My experiences

### ISSUE THREAD

**Issue by tverweij** [dotnet/vblang#264]
After a number of good email discussions with Anthony he invited me to come to vblang - I did so, but my experiences here are not good.

First of all, there are a lot of people here, with lots of *very* good ideas. 
But there are also people here - mostly the ones that have to implement those ideas - who shoot everything down (even almost all ideas of Anthony); too complex, too difficult, I don't understand what you need it for or just no comment but only thumbs down (something that should no be here; answer, like or stay away - we are not small children).

In the thread #248  "Change in Microsoft Visual Basic PM Role" of Kathleen, the following question was asked: "Please help us be realistic: If we open an issue here for a clearly-defined and valuable feature, what are the chances that it will find its way to VB within, say, 6 months?"
And it was never answered.

As I go further, the par between C# and VB was released; all new stuff comes in C#, and maybe - one day - in VB, even if its fit VB more than C#.
A good example for this is the thread: #222 "Improve return types from async functions", where a function is requested that is already in C#, and the response is a simple "Why?" - and even when it was answered, it still stays on "Scenario needed".

The point is (as I think) that VB developers are a special kind of breed - they think completely different than C#/C/C++ developers.
I work now 23 years with VB - I like new technologies, I like building cutting edge applications, but I am lazy. As WolvenRA stated it in the thread #244 "New Fixed Length (user defined length) Char Primitive Data Type": "Can I write my own funtions for these things? Yes. Should I have to? No."
And that is the VB spirtit. VB should enable us with anything that enables us to do RAD, prevent us from making mistakes and bugs (thats why (non)nullable references should have come to VB first). 
Because VB was and is a RAD tool. If it is not; it has no reason to exist and we should all switch to another language.

As I see it, after monitoring vblang for a few month, VB is dying - there is alsmost no will to implement (specific VB) improvements and VB is excluded from new technologies.
I will survive; I am almost 50 years old and if VB dies, there is enough to do - maintaining the legacy applications - for my remaining professional life.
But it would be a shame to have not only seen the rise of VB in my professional life, but also the fall of it.

Edit: added references to the mentioned threads

**Comment by AdamSpeight2008** [comment]
I am one of the rare few external contributors, that have implemented a feature. Admittedly not production quality, but it enough to for my get "the sense and feel" of a feature. The features I've been perusing are the features / abilities I want Visual Basic to have. 
I don't care who implements feature, or even if there a concurrent efforts. What I care about is getting the feature into the language. Take for example  Default Optional Parameters 
eg` Funtion(Optional n As Int?, Optional i As Int, Optional s As String) `
In my opinion wouldn't take long to implement, especially if they already have knowledge and experience implementing features. Especially considering that some on team have implement support for JSON and Regex on flights.

If the team are not wanting pull-requests, why did they open-source it?
I think the change to open-source was a culture shock and they have a normalisation bias of working in large corporation. Rule 0 is cover your own arse, accept no responsibility..
The VB community could if pushed fork the language, and support it independently.

**Comment by tverweij** [comment]
@AdamSpeight2008 

> The VB community could if pushed fork the language, and support it independently.

I think that would not be such a bad idea - and I would like to contribute, but it would be my first compiler experience ...

**Comment by AdamSpeight2008** [comment]
Also when I prototyped `Enum Flags Operators` and played with the relised that extend the operators to `Expressions`, or in my case `ParenthesisedExpressions` would enhance the feature make more powerful.
Hence I forked that feature and tried it out.

**Comment by AdamSpeight2008** [comment]
My opinion VB programmer like to cobble together something, as it that only what the need to fulfil there needs. C# and C style language programmer, tend to "engineer" their solutions.

**Comment by tverweij** [comment]
Problem is: I have no customers that will pay for engineering.
They want to see results.

**Comment by gafter** [comment]
> If the team are not wanting pull-requests, why did they open-source it?

We welcome pull requests for well-engineered implementations of features that have been reviewed and approved by the LDM. Bug fixes too.

**Comment by tverweij** [comment]
@gafter 
And those are at this moment?

**Comment by gafter** [comment]
@tverweij As we're rebooting the LDM, we're going to start from scratch reviewing language proposals. But for example that would include await in try and finally. I think most of the issues in this query

https://github.com/dotnet/vblang/issues?q=is%3Aopen+is%3Aissue+label%3AApproved-in-Principle

would satisfy, if the design is clear. If the design isn't clear more LDM work might be required.

**Comment by gafter** [comment]
If you're looking for VB bugs to fix, this is a good place to start:

https://github.com/dotnet/roslyn/issues?q=is%3Aopen+is%3Aissue+label%3A%22help+wanted%22+label%3AArea-Compilers+label%3ALanguage-VB

**Comment by tverweij** [comment]
Ok, that is clear.
What is not clear for me is that the label "Approved" (without the "in principle") is missing ...
I can't wait to see some of them (The use of the "declined" label would also be very clear, instead of leaving points open).

**Comment by gafter** [comment]
It would be hard to "approve" a feature design (beyond merely in principle) without an implementation that exposes, in detail, all of the things we might not have thought of in the LDM. That happens, in practice, when it has been integrated into the product.

**Comment by tverweij** [comment]
I mean: Approved for implementation start.
Of cause the resulting implementation should be reviewed in detail.

**Comment by KathleenDollard** [comment]
@tverweij 

>"Please help us be realistic: If we open an issue here for a clearly-defined and valuable feature, what are the chances that it will find its way to VB within, say, 6 months?"

This is a more difficult question to answer than it appears. Months have to do with release cycles. "clearly-defined and valuable feature" is in the eyes of the beholder, and we won't be able to do every good idea in a timely manner. 

I'm going to rephrase your question . _Do we plan to put new features into VB and do we anticipate that the discussion and contributions here are a significant driving force for that?_ the answer to that is "yes, absolutely."

As far as #222, stating a problem scenario is important for getting a feature right. "Why" may have been brief, but it let the conversation proceed to a more clear understanding.

**Comment by KathleenDollard** [comment]
@AdamSpeight2008 

>If the team are not wanting pull-requests, why did they open-source it?

PRs are just one of the benefits of OSS. They are appreciated, but an open dialog about the code is more important, imo. I say that not to discourage the small number of people like you unafraid of understanding the Roslyn compiler, but to encourage the greater number of people that can't contribute code, but can contribute their thoughts and ideas.

**Comment by gafter** [comment]
@tverweij All of the language features that are "Approved in principle" are at a stage where an implementation would be a good next step.

**Comment by AdamSpeight2008** [comment]
@gafter @KathleenDollard 
`Approved In Principle` what happen next? Are there waiting for something ? Is add label and reply indicating the next stage needed. 

Can contributor provide a draft `specification` ? Or does that require a LDM member to write? 

We could do with flow diagram. With what happens in stage and by whom / role. etc.

**Comment by AdamSpeight2008** [comment]
@KathleenDollard 
 > PRs are just one of the benefits of OSS. They are appreciated, but an open dialog about the code is more important,

But that *"open dialog about the code"* seems to be restricted Microsoft Vetted or Approved Code.

**Comment by tverweij** [comment]
@KathleenDollard 
>As far as #222, stating a problem scenario is important for getting a feature right. "Why" may have been brief, but it let the conversation proceed to a more clear understanding.

What I meant was that that specific function is already in C#.
How can there be a "Why?" for VB when there is no "Why?" for C#?

**Comment by tverweij** [comment]
@KathleenDollard 
To show that VB is alive, it would be nice if the VB team would blog about new features as the C# team does. At this moment VB is non-existent on the complete MSDN website and in the MSDN magazine.
I even found things (could not find it back at this moment) about VB support for (I thought) ASP.Net code - the answer was that is was too much work - that, if they created it, it had to be maintained for many years and that the team did not have a clue about VB - and therefore there would not be VB support. 
And this makes me very sad (understatement).

**Comment by gafter** [comment]
> But that *"open dialog about the code"* seems to be restricted to Microsoft Vetted or Approved Code.
Not code related to an exploratory implementation.

Your complaint, as I've understood it many times before, is that the teams at Microsoft are not providing you sufficient support in your effort to understand and experiment with changes to the compilers. From our point of view, you expect us to engage in a custom extended tutorial in language and compiler design that is directed as your interests take you.

We have contributors to Roslyn at many levels of skill. Some of them have the skills and experience to undertake significant language design and implementation projects, and produce implementations that are found to have few issues in review (and who are very responsive to review feedback). Some contributors, on the other hand, submit PRs that propose significant reorganizations of the compiler internals that accomplish nothing but reducing performance and change code to violate our coding conventions, or implement language features that have not been vetted by the LDM and are unlikely to be in a form that the LDM would accept. The latter require a disproportionately large expenditure of our engineering effort just to explain what's wrong. We tend to encourage the former and discourage the latter.

I understand you feel discouraged, and I'm sorry that's the case. But we are unlikely to devote an engineer or two to develop external talent.

**Comment by tverweij** [comment]
@gafter 
That should be a nice new course for the Microsoft certifications: Certified Roslyn Developer.

**Comment by AdamSpeight2008** [comment]
@gafter I'm not ask for *"custom extended tutorial"* but for help with aspects of the internals of the Roslyn compiler. I am i would consult the available documentation, or derive from XML doc comments or even comments with the code. This what is lacking, add some information to non-public APIs.

**Comment by gafter** [comment]
> @gafter I'm not ask for *"custom extended tutorial"* or personalised support but for help with aspects of the internals of the Roslyn compiler.

Those feel the same to us.

**Comment by tverweij** [comment]
@gafter 
What documentation _is_ available? And where?

**Comment by AdamSpeight2008** [comment]
@gafter  To me it feels like "Roslyn" is a gated community.  It would be nice to have occasional open days, where "Roslyn" were allowed to look and comment.

**Comment by gafter** [comment]
@tverweij In https://github.com/dotnet/roslyn/blob/master/CONTRIBUTING.md you'll find the following:

> ## Submitting Pull Requests
> - **DO NOT** submit language features as PRs to this repo first, or they will likely be declined.
> - **DO NOT** submit large code formatting changes without discussing with the team first.

...

> ## Coding Style
> 
> The Roslyn project is a member of the [.NET Foundation](https://github.com/orgs/dotnet) and follow the same [developer guide](https://github.com/dotnet/corefx/blob/master/Documentation/coding-guidelines/coding-style.md).  The repo also includes [.editorconfig](http://editorconfig.org) files to help enforce this convention.  Contributors should ensure they follow these guidelines when making submissions.

**Comment by AdamSpeight2008** [comment]
@gafter  There are no Roslyn / .Net Foundation approved Coding Styles for Visual Basic contributions.
So could argued they are open to interpretation.

**Comment by gafter** [comment]
@AdamSpeight2008 Yes, "Roslyn" is a gated community. It has a set of gatekeepers who vet the quality and contents of code contributions. Discussions are open as long as they are respectful and on topic. Members of the Roslyn team are always allowed to look and comment on both PRs and issues (we don't need a special day on which they have such permission).

**Comment by tverweij** [comment]
@AdamSpeight2008 
A starting point: [http://addressof.com/blog/articles/CodingGuidelines.aspx](url)

**Comment by AdamSpeight2008** [comment]
@tverweij There are lots of external ones, even Microsoft one, but within the Roslyn / .Net Foundation repositories there is no explicit acknowledgement of the Style Guideline Visual Basic contribution to them will follow.

**Comment by gafter** [comment]
@AdamSpeight2008 We haven't had big problems with the style of code you've offered for contribution. Our problem was that you were offering significant rewrites of the code that merely changed the style to one we did not prefer. Generally speaking, we do not want such changes. Thus the guideline in https://github.com/dotnet/roslyn/blob/master/CONTRIBUTING.md

- **DO NOT** submit large code formatting changes without discussing with the team first.

**Comment by AnthonyDGreen** [comment]
Most issues on this repo haven't been "shot down", @tverweij, that's why issues have rarely been closed. The reasons issues have been closed are usually that there design team thinks a different proposal is better. So, in the case of the scenario of making model-view-viewmodel easier to write in VB there were three proposals: Hard code INotifyPropertyChanged, full on AOP, and something in the middle. The design team agreed that the scenario had lots of merit so the question was whether the approaches were mutually exclusive. We asked the question: "if we did A now would we still do B in a future release", we ask that question in both directions. No surprise, nothing would keep us from doing AOP if we had a general, workable solution. But having a general AOP solution would render the other options kinda pointless (though we weren't unanimous on that). But AOP is more than a ways off and there other two solutions were doable by anyone soon. So it became a choice between bindable properties and withproperyevents classes. The LDM felt there latter was the better design so the former was shot down. It was my idea, yes, but so was th idea the wasn't shot down. The idea went on to the next step--more thinking :) The goal of that very successful meeting was to focus on the best of three. That was November. Since then I've revised the design of the WithPropertyEvents feature and am super excited about it. I really just want to prototype it and share it so we can discuss applications. I fully intend to continue championing that idea (and most of my ideas) even now because as a VB user it excites me. I love using the language and want to continue enjoying it.

Anyway, "scenario needed", "speclet needed", "prototype needed", etc were _never_ intended to be dead ends for ideas. Just the next step in the process. Who takes that step and when is where we the community and the VB team at Microsoft get to wiggle. There are no doubt things Kathleen and co _need_ to make happen for VB16. We don't want to and often won't be able to randomize them into prioritizing our pet feature to design and implement but we do, through OSS, have the means to help out.

Lastly, for perspective, when I started on the VB Team Mads had a proposal for tuples. We prototyped it Spring of 2010, I believe. It took until 2017 to ship it and the design had changed a lot. A proposal sitting on the repo for a couple of months is light speed compared to the pre-Roslyn/pre-Open-Source workflow.

**Comment by tverweij** [comment]
@AnthonyDGreen 

I believe my English is not good enough to understand this statement:

> We prototyped it Spring of 2010, I believe. It took until 2017 to ship it

Or are you really saying that the complete implementation from idea to shipment cost 7 years?

**Comment by gafter** [comment]
@tverweij A prototype is a working but possibly incomplete implementation.

**Comment by tverweij** [comment]
Let's stop this discussion, and let's hope that I am wrong; let's hope that VB is alive and kicking.

I want to add a few last comments.
1. A problem that has to be solved quick, is that no people within Microsoft are committed to maintain VB related stuff, as mentioned in the thread aspnet#2738; if nobody at Microsoft want to commit to VB, we are lost: 
> The cost to create an initial set of templates might not be much, but someone has to maintain them. With F# we have people at Microsoft who are committed to maintaining them. We don't have any such people for VB at this time.
2. If VB is almost nonexistent on the Microsoft website, it will continue to decline - if there is no information on VB, people will lose confidence and use c# or something else.
3. If VB is excluded from new technologies like mobile and web development, there will be no future for VB, the world is changing into Web and Mobile and each language (not only the Microsoft ones) has to support them to survive.
4. If VB is excluded from existing technologies because it is not used enough (example: Razor), excluded from new technologies because there is not enough VB support within Microsoft and all old (legacy / abandoned) technologies are removed from Visual Studio, there will be nothing left for VB to support in
the end.

**Comment by tverweij** [comment]
closed.
