### ISSUE TITLE
Hyperlinked implementation of the VB and C# grammar.

### ISSUE THREAD

**Issue by AdamSpeight2008** [dotnet/vblang#275]
@ljw1004 wrote a while back a version Hyperlinked implementation of the [vb and c grammar](https://blogs.msdn.microsoft.com/lucian/2010/04/19/vb-and-c-grammar-for-vs2010/).
We should include a version in the respective repositories. It would make exploring the grammar little easier.

**Comment by zspitz** [comment]
Is the VB.NET grammar still up-to-date?

**Comment by AdamSpeight2008** [comment]
@zspitz The one linked to is a little out of date, it being VB10 and I think the current latest major release is VB15.

**Comment by zspitz** [comment]
I would suggest that there are excellent free / OSS tools available for browsing ANTLR grammers (like [ANTLRWorks](http://www.antlr3.org/works/) and a [VS Code extension](https://marketplace.visualstudio.com/items?itemName=mike-lischke.vscode-antlr4)), so providng a full hyperlinked file shouldn't be necessary.

![image](https://user-images.githubusercontent.com/312166/37252876-0dca42d6-2532-11e8-8d78-87fa1fee49af.png)

However, the grammar available from [here (link at the bottom of the page)](https://github.com/dotnet/vblang/tree/master/spec) has the following errors when run through ANTLR4 :

> The following sets of rules are mutually left-recursive [CCExpression, CCOperatorExpression] and [NonArrayTypeName, NullableTypeName] and [Expression, IsExpression, MemberAccessBase, DictionaryAccessExpression, InvocationExpression, IndexExpression, AdditionOperatorExpression, SubtractionOperatorExpression, MultiplicationOperatorExpression, FPDivisionOperatorExpression, IntegerDivisionOperatorExpression, ModuloOperatorExpression, ExponentOperatorExpression, RelationalOperatorExpression, LikeOperatorExpression, ConcatenationOperatorExpression, ShortCircuitLogicalOperatorExpression, LogicalOperatorExpression, ShiftOperatorExpression, XMLMemberAccessExpression, TypeExpression, MemberAccessExpression, OperatorExpression, ArithmeticOperatorExpression, DivisionOperatorExpression]

I think a better focus would be to try and fix these errors so the current grammar can be used with more advanced tooling.
