### ISSUE TITLE
Proposal: Use .. to refer to the subject of With and Using.

### ISSUE THREAD

**Issue by AdamSpeight2008** [dotnet/vblang#283]
@An alternative to #31

```vbnet
Private Sub AddMemberModifiersIfRequired(symbol As ISymbol)
  With symbol
    AssertContainingSymbol(symbol)

    Dim containingType = TryCast(.ContainingSymbol, INamedTypeSymbol)
    If format.MemberOptions.IncludesOption(SDMO.IncludeModifiers) AndAlso
         (containingType Is Nothing OrElse
           (containingType.TypeKind <> TypeKind.Interface AndAlso Not IsEnumMember(symbol))) Then

        Dim isConst = .Kind = SymbolKind.Field AndAlso DirectCast(symbol, IFieldSymbol).IsConst
        If .IsStatic AndAlso
           (containingType Is Nothing OrElse containingType.TypeKind <> TypeKind.Module) AndAlso
           Not isConst Then

          AddKeyword(SyntaxKind.SharedKeyword, followedBySpace:=True)
        End If

        ' WithEvents visualize as if they are fields.
        If Not IsWithEventsProperty(symbol) Then
        If .IsAbstract Then AddKeyword(SyntaxKind.MustOverrideKeyword, followedBySpace:=True)

        If .IsSealed Then AddKeyword(SyntaxKind.NotOverridableKeyword, followedBySpace:=True)
        If .IsVirtual Then AddKeyword(SyntaxKind.OverridableKeyword, followedBySpace:=True)

        ' Overloads is only available for VisualBasic symbols.
        If IsOverloads(symbol) AndAlso Not .IsOverride Then AddKeyword(SyntaxKind.OverloadsKeyword, followedBySpace:=True)

        If .IsOverride Then AddKeyword(SyntaxKind.OverridesKeyword, followedBySpace:=True)

      End If
    End If
  End With
End Sub
```

Using `..` within a `With` and `Using` to semantically mean use the object referred by the enclosing `With` or `Using`

```vbnet
Private Sub AddMemberModifiersIfRequired(symbol As ISymbol)
  With symbol
    AssertContainingSymbol(..)

    Dim containingType = TryCast(.ContainingSymbol, INamedTypeSymbol)
    If format.MemberOptions.IncludesOption(SDMO.IncludeModifiers) AndAlso
       (containingType Is Nothing OrElse
         (containingType.TypeKind <> TypeKind.Interface AndAlso Not IsEnumMember(..))) Then

      Dim isConst = .Kind = SymbolKind.Field AndAlso DirectCast(.., IFieldSymbol).IsConst
      If .IsStatic AndAlso
         (containingType Is Nothing OrElse containingType.TypeKind <> TypeKind.Module) AndAlso
          Not isConst Then
        AddKeyword(SyntaxKind.SharedKeyword, followedBySpace:=True)
      End If

      ' WithEvents visualize as if they are fields.
      If Not IsWithEventsProperty(..) Then
        If .IsAbstract Then AddKeyword(SyntaxKind.MustOverrideKeyword, followedBySpace:=True)

        If .IsSealed Then AddKeyword(SyntaxKind.NotOverridableKeyword, followedBySpace:=True)

        If .IsVirtual Then AddKeyword(SyntaxKind.OverridableKeyword, followedBySpace:=True)

         ' Overloads is only available for VisualBasic symbols.
         If IsOverloads(..) AndAlso Not .IsOverride Then AddKeyword(SyntaxKind.OverloadsKeyword, followedBySpace:=True)

        If .IsOverride Then AddKeyword(SyntaxKind.OverridesKeyword, followedBySpace:=True)

      End If
    End If
  End With
End Sub
```

**Comment by franzalex** [comment]
It's a nice suggestion as there have been several times that I've needed to use the object of the `With` statement somewhere in the block. I however lean towards extending the `With`keyword to allow a scoped variable declaration as was suggested in #31.

```vb
With x As New MyClass
   .SomeMethod()
   AnotherClass.Action(x)
End With
```

**Comment by xieguigang** [comment]
```vbnet
''' <summary>
''' Extension method for VisualBasic ``With`` anonymous variable syntax source reference helper
''' </summary>
''' <typeparam name="T"></typeparam>
''' <param name="x"></param>
''' <returns></returns>
''' 
<MethodImpl(MethodImplOptions.AggressiveInlining)>
<Extension> Public Function [ByRef](Of T)(x As T) As T
    Return x
End Function
```

### Usage

```vbnet
With "12345"
     Return "Hello " & .ByRef
End With
```

**Comment by franzalex** [comment]
That's a nice extension method @中二病でも恋がしたい！.
The only thing is that it's an *extension __method__*. I always put parentheses after methods, even when it has arguments. This is in spite of  VB.NET allowing methods with no arguments to be called without parentheses.  
As such I'd have preferred it were an _extension **property**_. Unfortunately such a thing doesn't exist in .NET yet so I guess this is as far as we can go.

**Comment by franzalex** [comment]
That's a nice extension method @xieguigan.

The only thing is that it's an *extension __method__*. I always put parentheses after methods, even when it has arguments. This is in spite of  VB.NET allowing methods with no arguments to be called without parentheses.  
As such I'd have preferred it were an _extension **property**_. Unfortunately such a thing doesn't exist in .NET yet so I guess this is as far as we can go.

**Comment by rskar-git** [comment]
@xieguigang  While the '`ByRef`' extension is nice, it has a limitation: It isn't a true reference to the target object of the `With`; it's a copy. That's probably not a big deal for reference types (`Class` objects), but it's likely to make a world of difference for value-types (`Structure` objects) if one every wanted to make a call to a `Sub` or `Function` which takes the target object via a `ByRef` parameter (in order to modify it).

**Comment by Nukepayload2** [comment]
@rskar-git This limitation can be solved with a line of c# code.
```C#
public static ref T ByRef<T>(this ref T value) where T : struct => ref value;
```

Example:
__C#__
```C#
namespace Helpers
{
    public static class WithExtension
    {
        public static ref T ByRef<T>(this ref T value) where T : struct => ref value;
    }
}
```
__VB__
```vb
Imports System.Runtime.CompilerServices
Imports Helpers

Module Program
    Sub Main(args As String())
        Dim x = 0
        Console.WriteLine($"Initially, x = {x}.")
        Console.WriteLine("Limitation: VB doesn't allow ByRef returns.")
        With x
            Increment(.ByRefBuggy)
            Console.WriteLine($"x = {x}")
        End With
        Console.WriteLine("Use ByRef returning C# method.")
        With x
            Increment(.ByRef)
            Console.WriteLine($"x = {x}")
        End With
        Console.Read()
    End Sub

    Sub Increment(ByRef n As Integer)
        n += 1
        Console.WriteLine("Increased value.")
    End Sub

    <Extension>
    Function ByRefBuggy(Of T)(value As T) As T
        Console.WriteLine("Get `With` variable without ByRef returns.")
        Return value
    End Function
End Module
```
This .net code 2.0 console app generates the following output:
```
Initially, x = 0.
Limitation: VB doesn't allow ByRef returns.
Get `With` variable without ByRef returns.
Increased value.
x = 0
Use ByRef returning C# method.
Increased value.
x = 1
```

**Comment by rskar-git** [comment]
@Nukepayload2  Or simply forsake `With` and just use a lambda:

        Dim x = 0
        Call (Sub(ByRef w As Integer)
                  Increment(w)
                  Console.WriteLine($"x = {x}")
              End Sub)(x)

Not as pretty to look at, but it works just fine.

Or one could craft specialized extensions, such as:

    Friend Delegate Sub DoWithAction(Of T)(ByRef x As T)
    <Extension> Friend Sub DoWith(Of T)(ByRef x As T, Action As DoWithAction(Of T))
        Call Action(x)
    End Sub

And then:

        With x
            .DoWith(AddressOf Increment)
            Console.WriteLine($"x = {x}")
        End With

Or maybe instead:

        With x
            .DoWith(Sub(ByRef w As Integer)
                        Increment(w)
                    End Sub)
            Console.WriteLine($"x = {x}")
        End With

**Comment by xieguigang** [comment]
Hi, @rskar-git @Nukepayload2, :raising_hand: I just don't understand why would you want to modify the original value of the ``ValueType`` anonymous variable....

```vbnet
Imports System.Linq.Expressions
Imports System.Reflection
Imports System.Runtime.CompilerServices

Module Module1

    Sub Main()

        With #2018-9-6#
            Call Console.WriteLine("original value of this anonymous variable:")
            Call Console.WriteLine(.ByRef)

            ' VB byref return function
            ' Assign value back to the source reference through byref function
            Call ByRefReturn(Function() .ByRef() = #2020-4-13#)

            Call Console.WriteLine("byref reference value of this anonymous variable after byref return:")
            Call Console.WriteLine(.ByRef)
            Call Console.ReadLine()

            ' original value of this anonymous variable:
            ' 9/6/2018 12:00:00 AM
            ' byref reference value of this anonymous variable after byref return:
            ' 4/13/2020 12:00:00 AM
        End With
    End Sub

    <Extension>
    Public Function [ByRef](Of T)(ByRef x As T) As T
        Return x
    End Function

    ''' <summary>
    ''' Implements a byref return
    ''' </summary>
    ''' <typeparam name="T"></typeparam>
    ''' <param name="linq"></param>
    Public Sub ByRefReturn(Of T)(linq As Expression(Of Func(Of T)))
        Dim body = DirectCast(linq.Body, BinaryExpression)
        ' ByRef function reference for the With anonymous variable
        Dim ref = DirectCast(body.Left, MethodCallExpression).Arguments(0)
        Dim value = DirectCast(body.Right, ConstantExpression).Value
        Dim anonymous = DirectCast(ref, MemberExpression)
        Dim variable = DirectCast(anonymous.Expression, ConstantExpression).Value

        ' byref set value
        Call DirectCast(anonymous.Member, FieldInfo).SetValue(variable, value)
    End Sub
End Module
```

**Comment by Nukepayload2** [comment]
I have ignored a scenario.
If the with variable is a property, and the property is not returning ByRef, The modified value will not be copied back to the property.
```vb
    Property Value As Integer = 0

    Sub Main(args As String())
        Dim x = 0
        Console.WriteLine($"Initially, x = {x}.")
        Console.WriteLine("Limitation: VB doesn't allow ByRef returns.")
        With x
            Increment(.ByRefBuggy)
            Console.WriteLine($"x = {x}")
        End With
        Console.WriteLine("Use ByRef returning C# method.")
        With x
            Increment(.ByRef)
            Console.WriteLine($"x = {x}")
        End With
        Console.WriteLine("Use ByRef returning C# method and VB property.")
        With Value
            Increment(.ByRef)
            Console.WriteLine($"Value = {Value}")
        End With
        Console.WriteLine("Use explicit property name.")
        With Value
            Increment(Value)
            Console.WriteLine($"Value = {Value}")
        End With
        Console.Read()
    End Sub
```
Output:
```
Initially, x = 0.
Limitation: VB doesn't allow ByRef returns.
Get `With` variable without ByRef returns.
Increased value.
x = 0
Use ByRef returning C# method.
Increased value.
x = 1
Use ByRef returning C# method and VB property.
Increased value.
Value = 0
Use explicit property name.
Increased value.
Value = 1
```

**Comment by AdamSpeight2008** [comment]
Out of personal curiosity, why do you prefix Call to method invocations? @xieguigang

**Comment by xieguigang** [comment]
Hi, @AdamSpeight2008 , Add a prefix ``Call`` keyword for method invocation makes VB code have enough distinguishable characteristic when compares with other programming language like C# or python., etc

**Comment by rskar-git** [comment]
"...why would you want to modify the original value of the ValueType anonymous variable...."

@xieguigang  The use-case I have in mind is when you want to process a large array of value-types, whether you want to modify its value(s) or not. VB doesn't do pointers directly, you must work through either a ByRef parameter of a Sub/Function/Lambda or a `With` block. When the `Structure` type is small, then there's little need for pointers, since working via a copy might be faster in that circumstance. However, in the case of larger `Structure` types (> 16 bytes), it begins to make better sense to work from a pointer or reference (e.g. https://stackoverflow.com/questions/1082311/why-should-a-net-struct-be-less-than-16-bytes).

Have a look at this (C# based) article at https://jacksondunstan.com/articles/3860, which demonstrates a major performance difference between processing an array of `class` versus an array of `struct`. Note that in this example, field `Position` gets modified; this sort of thing is commonly done for real-time games and simulations. Now, in C#, one doesn't have an equivalent to `With`, but there are (at least) three options to achieve about the same: (1) use a lambda; (2) use a local function; or (3) use a pointer in unsafe mode.

In VB.NET, we can easily transcend `With` with an inline lambda. `With` was much handier for VBA and VB6 performance-wise, but for VB.NET `With` is just a nice bit of syntactic sugar. 

C# option (3), "use a pointer", is probably something we should think a little more about. When one is stepping sequentially through an array, one can get faster processing with a pointer, since advancing to the next element (or retreating to the previous) keeps it to a very simple increment (or decrement) operation. It's faster because working from the index value will involve one or more multiplication operations too. Interestingly, COBOL has a way of establishing a "behind-the-scenes" pointer into an array via its `INDEXED BY` clause (arrays in COBOL are known as tables). I would think coming up with something like that for VB may be far more powerful than trying to extend `With`.

**Comment by zspitz** [comment]
Also note that the extension method will not work with `Object` variables.

**Comment by bandleader** [comment]
Also `..` conflicts with #245 (and possibly with #165 if we use `..` as I had suggested)

However, `.Me` would be fine.
