### ISSUE TITLE
Support declaration of fields inside 'Property...End Property' blocks.

### ISSUE THREAD

**Issue by ericmutta** [dotnet/vblang#288]
Currently, if you want a property with a backing field, you have to declare it as follows:

```vb
  Private mFoo As String '<-- backing field outside the Property...End Property block.

  Public Property Foo As String
    Get
      If mFoo = "" Then
        mFoo = "Default value if empty"
      End If

      Return mFoo
    End Get

    Set(ArgValue As String)
      mFoo = ArgValue
    End Set
  End Property
```

The backing field `mFoo`  in the above scenario should only be referenced by the getter/setter of property `Foo`, however there is no way to enforce this rule right now, so if you mistakenly reference `mFoo` instead of `Foo` when reading the property value, the results are different:

```vb
    Dim mistake = mFoo '<-- no getter code is executed here.
    Dim correct = Foo '<-- property getter code runs here as expected.
```

The difference between `mFoo` and `Foo` is just one letter and you can easily end up with one or the other when using Intellisense to autocomplete the names.

**In the spirit of encapsulation and code correctness, I propose we add support for declaring fields scoped to the getter/setter of a property**:

```vb
  Public Property Foo As String
    Dim mFoo As String '<-- note backing field is now inside Property...End Property block.

    Get
      'can access mFoo here.
    End Get

    Set(ArgValue As String)
      'can access mFoo here.
    End Set
  End Property

  Dim value = mFoo '<-- ERROR: can't access mFoo outside of Property...End Property block.
```

For implementation this can be a **purely compile-time abstraction**: the final generated code would be exactly the way it is today (i.e the backing field defined inside `Property...End Property` is treated as if it were declared like any other field).

CC: @KathleenDollard

**Comment by reduckted** [comment]
I _think_ this is the same as #195 (or very similar to it), which was [rejected by the LDM](https://github.com/dotnet/vblang/blob/master/meetings/2017/vbldm-notes-2017.11.15.md#proposal-195---static-property-variables):

> **Rejected.** We don't see why this one narrow use case for members nested within other members get's special treatment. If we want to enable nesting we'd look at local functions and types as well.

**Comment by ericmutta** [comment]
> @reduckted I think this is the same as...

Many thanks for the pointer, I had no idea this had already been discussed!

Shame that they rejected it though :disappointed: I spent hours the other day hunting down a bug caused by accessing the backing field directly instead of going through the property...which is why **I strongly believe this should get special treatment**: it is a much more common use-case than local functions (which are reasonably covered by lambdas) and local types (which are reasonably covered by tuples and anonymous types).

@AnthonyDGreen any chance this could be revived? Was consideration given to the software correctness benefits that would result from allowing this form of encapsulation?

**Comment by rskar-git** [comment]
@ericmutta

Is the core issue here about properties with essential side-effects? I.e. from your example, it would seem that the Property Foo "getter" does a kind of lazy-loading.

Is it too late to address this sort of thing via refactoring and code reviews? I'm assuming the backing field(s) are private (since this proposal is about fields visible only to a Property), so it's largely a problem with the class which defines them. I think that a (hopefully not too painful) refactoring could instead keep things managable.

For example:

        Private Structure PrivateBackingFields
            Dim Foo As String
            Dim Bar As Integer
            ' etc. ...
        End Structure
        ''' <summary>
        ''' Never ever directly access these without good reason!!
        ''' Always use respective Property whenever possible!!
        ''' </summary>
        Private _m As PrivateBackingFields

        Public Property Foo As String
            Get
                If _m.Foo = "" Then
                    _m.Foo = "Default value if empty"
                End If

                Return _m.Foo
            End Get

            Set(ArgValue As String)
                _m.Foo = ArgValue
            End Set
        End Property

Leading underscores push identifiers towards the end of the list in the IDE, and the members of the structure won't appear without someone deliberately choosing `_m` first. That should help folks avoid making the `mFoo` vs `Foo` mistake accidentally.

During a code review, access to a `_m` member outside of a `Property` definition would then be a red flag.

**Comment by reduckted** [comment]
Another option would be to write a code analyzer that detects uses of a backing field outside its property. The only downside to that is it applies to _all_ properties whereas with defining the backing field inside the property, you can choose which properties it applies to.

**Comment by ericmutta** [comment]
> @rskar-git Is the core issue here about properties with essential side-effects?

Indeed it is. When some code needs to run on get/set (such as the lazy init logic in the example I gave), you are pretty much guaranteed to get bugs if you access the backing field directly. Currently we have a way to prevent **external** code from touching implementation data (you just make the field private) but we have no way to prevent **internal** code from doing that when the scenario calls for it.

> @rskar-git  Is it too late to address this sort of thing via refactoring and code reviews?

Interesting you mention the refactoring part. Lately, I've come up with a rule that **if you have a field/property X and methods M and N that touch that field, you should move the field X and the methods M and N to a seperate nested class/structure**...kinda similar to the code you showed with `Private Structure PrivateBackingFields`. It helps to isolate the data so accidental access is reduced but it feels like a lot of ceremony compared to just allowing fields scoped to a `Property...End Property` block.

> @reduckted Another option would be to write a code analyzer...

Indeed! I think the whole idea of analyzers is pretty cool and probably the most underused part of Rosyln. Case in point: I know they exist, I know they can solve a good number of the issues we raise in this repo, but I have never written one, or even seen one used in the libraries that I use:

![vs_analyzers](https://user-images.githubusercontent.com/20465797/38266578-b7eab442-3781-11e8-9396-2410a68e2428.png)

I plan on getting very rich and retiring this year so I can have more time to tinker with Rosyln myself, instead of always wanting someone else to do the work :smile:

**Comment by KathleenDollard** [comment]
Leaving the previous decision for now.
