### ISSUE TITLE
VB support assignment to a tuple

### ISSUE THREAD

**Issue by paul1956** [dotnet/vblang#292]
Will VB be able to support assignment directly to a tuple? This seems to be supported by C# but VB returns a syntax error on the first ( on the 4th line. It appears VB can only assign a Tuple to a Tuple variable then I need to use multiple statements to take it apart. Every example always shows a variable on the left side of the equals.
```
Dim getPeStream_Renamed As Func(Of Stream) = Function()
                                                                 Dim ret As Stream
                    (peStream, signingInputStream, ret) = GetPeStream(metadataDiagnostics, peStreamProvider, metadataOnly)
                    Return ret
                                                             End Function
```
In C#
```
Func<Stream> getPeStream = () =>
                {
                    Stream ret;
                    (peStream, signingInputStream, ret) = GetPeStream(metadataDiagnostics, peStreamProvider, metadataOnly);
                    return ret;
                };
```

**Comment by AdamSpeight2008** [comment]
Similar to #278

**Comment by paul1956** [comment]
Actually identical to, so I guess it is not currently supported in VB and I will close.
