### ISSUE TITLE
Proposal: add byte type-literal b

### ISSUE THREAD

**Issue by MohammadHamdyGhanem** [dotnet/vblang#295]
VB.NET has the &B binary literal:
`Dim x = &B1010`
X will be integer.
It also will be useful if we use b as a type symbol for byte like this:
```
Dim b = 12b
Dim c = {1b, 2b, 3b}
```
so VB.NEt can infer that b is byte, and c is byte array

**Comment by Nukepayload2** [comment]
Already proposed https://github.com/dotnet/vblang/issues/213

**Comment by MohammadHamdyGhanem** [comment]
@Nukepayload2 
Thanks. Is there a way to fine tune the search to look in the titles only?

**Comment by Nukepayload2** [comment]
Use the `in:title` qualifier. https://help.github.com/articles/searching-issues-and-pull-requests/

**Comment by AnthonyDGreen** [comment]
@MohammadHamdyGhanem what do you think of proposal #213? Looked like the scenario itself, moreso than any particular proposal, didn't have a lot of support.

**Comment by reduckted** [comment]
Well, #213 is basically a duplicate of #111, and neither of them have gone anywhere despite general agreement that it's a good idea.

It would be nice to see some of these "simple" ideas move forward.

**Comment by AnthonyDGreen** [comment]
Wow. I duplicated my own proposal. So embarrassed.

**Comment by KathleenDollard** [comment]
Dupe of #213
