### ISSUE TITLE
[Proposal] Select TypeOf

### ISSUE THREAD

**Issue by AdamSpeight2008** [dotnet/vblang#304]
# Select TypeOf Blocks
This is follows the same syntax as a `Select Case` block

If we take this [code sample](https://github.com/dotnet/roslyn/blob/160c4098fa90cff36fadad616eab2ae967ad2563/src/VisualStudio/VisualBasic/Impl/CodeModel/VisualBasicCodeModelService.vb#L360), use `Select TypeOf`
```vbnet
        Public Overrides Function GetAttributeNodes(node As SyntaxNode) As IEnumerable(Of SyntaxNode)
            Select TypeOf node
              Case CompilationUnitSyntax    Out result : Return GetAttributeNodes(result.Attributes)
              Case TypeBlockSyntax          Out result : Return GetAttributeNodes(result.BlockStatement.AttributeLists)
              Case EnumBlockSyntax          Out result : Return GetAttributeNodes(result.EnumStatement.AttributeLists)
              Case DelegateStatementSyntax  Out result : Return GetAttributeNodes(result.AttributeLists)
              Case DeclareStatementSyntax   Out result : Return GetAttributeNodes(result.AttributeLists)
              Case MethodStatementSyntax    Out result : Return GetAttributeNodes(result.AttributeLists)
              Case MethodBlockBaseSyntax    Out result : Return GetAttributeNodes(result.BlockStatement.AttributeLists)
              Case PropertyBlockSyntax      Out result : Return GetAttributeNodes(result.PropertyStatement.AttributeLists)
              Case PropertyStatementSyntax  Out result : Return GetAttributeNodes(result.AttributeLists)
              Case EventBlockSyntax         Out result : Return GetAttributeNodes(result.EventStatement.AttributeLists)
              Case EventStatementSyntax     Out result : Return GetAttributeNodes(result.AttributeLists)
              Case FieldDeclarationSyntax   Out result : Return GetAttributeNodes(result.AttributeLists)
              Case ParameterSyntax          Out result : Return GetAttributeNodes(result.AttributeLists)
              Case ModifiedIdentifierSyntax Out result : Return GetAttributeNodes(result.Parent)
              Case VariableDeclaratorSyntax Out result : Return GetAttributeNodes(result.Parent)
            End Select
            Return SpecializedCollections.EmptyEnumerable(Of SyntaxNode)()
        End Function
```

The `Out result` is scoped to only the `Case Block` it is on. eg
```vbnet
Case CompilationUnitSyntax    Out result : Return GetAttributeNodes(result.Attributes)
' ...
 Case CompilationUnitSyntax
    Dim result As CompilationUnitSyntax = DirectCast(node, CompilationUnitSyntax)
    Return GetAttributeNodes(result.Attributes)
```
Which why we can reuse `result` in subsequent Case Statements.

**Comment by gafter** [comment]
This proposal does not extend gracefully to more general pattern matching, so it is unlikely we would take this approach.

**Comment by AdamSpeight2008** [comment]
@gafter What Pattern Matching proposal?

**Comment by gafter** [comment]
@AdamSpeight2008 I am not referring to a specific pattern-matching proposal. I am referring the the possible addition of a pattern-matching construct corresponding to the construct added in C# 7 and 8.

**Comment by paul1956** [comment]
@gafter if I could chime in here, VB really needs a Select Case TypeOf , how you decide to get there is a detail. I don't find that C# Pattern Matching all that useful or understandable except that it allows a Select on TypeOf but in every case I have seen I need to do multiple things in the case block so the free variable creation doesn't save much and I like the variable name to reflect what it is, so "Result" is not something I want/need. I would be thrilled with
```
Public Overrides Function GetAttributeNodes(node As SyntaxNode) As IEnumerable(Of SyntaxNode)
            Select TypeOf node
                 Case CompilationUnitSyntax 
                      Return GetAttributeNodes(CType(node,CompilationUnitSyntax).Attributes)
                 Case TypeBlockSyntax
                       Dim TypeBlock as TypeBlockSyntax = CType(node, TypeBlockSyntax)
                       ' Do something else with TypeBlock
                       Return Something
                 Case ... 
            End Select
            Return SpecializedCollections.EmptyEnumerable(Of SyntaxNode)()
        End Function
``` 
The above pattern appear 100's of times in my code and using If/ElseIF is ugly and the line are very long

**Comment by Berrysoft** [comment]
How about this:
``` VB
Select TypeOf node
    Case result As CompilationUnitSyntax 
        Return GetAttributeNodes(result.Attributes)
    Case TypeBlock As TypeBlockSyntax
        ' Do something else with TypeBlock
        Return Something
    Case ... 
End Select
```

**Comment by gafter** [comment]
@AdamSpeight2008 I don't have a reason not to add one.

**Comment by Nukepayload2** [comment]
@gafter i don't think dropping TypeOf is a good idea. Consider the following code :
```vb
Dim linqExpr = From node In nodes Where node IsNot Nothing 
Select node ' what's the meaning of Select node here? 
    Case result As CompilationUnitSyntax 
        Return GetAttributeNodes(result.Attributes)
    Case TypeBlock As TypeBlockSyntax
        ' Do something else with TypeBlock
        Return Something
    Case ... 
End Select
```

**Comment by gafter** [comment]
@Nukepayload2 How is that any different than if the cases were `Case 3` and `Case 4`?

**Comment by gafter** [comment]
Added the `Case` keyword to the `Select` line.

**Comment by Nukepayload2** [comment]
@gafter There is no problem after adding  the `Case` keyword.

**Comment by paul1956** [comment]
I think either TypeOf or no TypeOf is fine, TypeOf is a little clearer to the reader and more inline with current VB but give me either and I am thrilled as long as each Case block can have a different named variable, or the same name if someone else wants that. In one project I use TypeOf over 1,600 times in "If statements" that should be Select Case.

**Comment by bandleader** [comment]
I think @gafter means that:
- If VB does get pattern matching similar to C#, then besides for testing for a specific value `Case "some string", you can also test for type `Case SomeType` (and also get a cast variable: `Case myTypedVar as SomeType`).
- If that is the case, we don't need a special syntax like `Select Case TypeOf x`, since x is being pattern-matched, not value-matched, and

Yes, some people would be confused, expecting `Select Case` to be a value matching statement as before -- we discussed this also in the context of the `Is` operator which currently checks for reference equality but could be expanded to allow (as in C#) any pattern match.

Another note: In many cases, you could use `Select Case x.GetType` here, followed by `Case GetType(String)` etc. There are slight differences.

**Comment by paul1956** [comment]
@bandleader This may not be the place but can you explain "slight differences"?  If they are the same I will start using it immediately and not wait for this feature.
```
In many cases, you could use Select Case x.GetType here, followed by Case GetType(String) etc. There are slight differences.
```

**Comment by AdamSpeight2008** [comment]
My concern with the following syntax proposal is, currently we are expecting "the thing" were checking against value being the first aspect of the clause. 
```vbnet
Select Case node ' what's the meaning of Select node here? 
    Case result As CompilationUnitSyntax 
        Return GetAttributeNodes(result.Attributes)
    Case TypeBlock As TypeBlockSyntax
        ' Do something else with TypeBlock
        Return Something
    Case ... 
End Select
```
Alternatively we could, add additional meanings the relational clause (`Is > 0`) to, extend the `TypeOf` in the `Select Type`. Thus reusing some the knowledge of `TypeOf` expressions.
```vb
Select TypeOf node ' what's the meaning of Select node here? 
    Case Is CompilationUnitSyntax Out result 
        Return GetAttributeNodes(result.Attributes)
    Case Is TypeBlockSyntax Out TypeBlock
        ' Do something else with TypeBlock
        Return Something
    Case ... 
End Select
```

**Comment by Berrysoft** [comment]
The keyword `Out` makes me confuse. What does this code mean:
```vbnet
Dim CompilationUnitSyntax Out result
```
I think the use of `Case` and `As` is a good idea.
```vbnet
Select Case [TypeOf] node
    Case [Is] result As CompilationUnitSyntax 
        Return GetAttributeNodes(result.Attributes)
    Case [Is] TypeBlock As TypeBlockSyntax
        ' Do something else with TypeBlock
        Return Something
    Case ... 
End Select
```
Possibly we can use:
```vbnet
If TypeOf node Is result As CompilationUnitSyntax Then
    'Do something
End If
```
Even in `TryParse` methods:
```vbnet
If Integer.TryParse("123", result As Integer) Then
    'Do something
End If
```

**Comment by AdamSpeight2008** [comment]
@Berrysoft

`Out` is related to #305, they would akin to Out parameters / variable is C#. 
Use with typeof expression it is a
 ```vbnet
If TypeOf node Is CompilationSyntax Out result Then 
' roughly translating to
If TypeOf node Is CompilationSyntax Then
   [Dim] Result = DirectCast(node, CompilationUnitSyntax`
```
```vbnet
If Integer.TryParse("123",Out result) Then
    'Do something
End If
'''
[Dim] result As Integer = Nothing
If Integer.TryParse("123", result ) Then
  `...
End If
```

The follow syntax would be a breaking change.
`If TypeOf node Is result As CompilationUnitSyntax Then`
as older compilers would be expecting a `TypeIdentifier` after the `Is` rather than an `Identifier`
I proposed `Out` as it wouldn't break existing code.

**Comment by AdamSpeight2008** [comment]
@gafter  Does VB need pattern-matching?

**Comment by rskar-git** [comment]
If I'm understanding the sort of pattern-matching being discussed here (e.g. https://docs.microsoft.com/en-us/dotnet/csharp/pattern-matching), it is at minimum a syntactic sugar that combines `If TypeOf myObj Is SomeType Then` with `Dim x = CType(myObj, SomeType)` in a very handy compact way. Clearly it is possible to carry-on without it, but it does happen often enough where you'd like to do things differently depending on what type of object you're dealing with.

I like the idea of pattern-matching.

It has been suggested to use `Out` as a keyword, but I think we could instead go with `Dim`. Furthermore, I believe if we can keep the VB forms aligned with the C# ones, there's a better chance we can have pattern-matching easily enough.

So something like this (C#):

    public static double ComputeAreaModernIs(object shape)
    {
        if (shape is Square s)
            return s.Side * s.Side;
        else if (shape is Circle c)
            return c.Radius * c.Radius * Math.PI;
        else if (shape is Rectangle r)
            return r.Height * r.Length;
        // elided
        throw new ArgumentException(
            message: "shape is not a recognized shape",
            paramName: nameof(shape));
    }

Could be like this (VB):

    Public Shared Function ComputeAreaModernIs(shape As Object) As Double
        If TypeOf shape Is Square Dim s Then
            Return s.Side * s.Side
        ElseIf TypeOf shape Is Circle Dim c Then
            Return c.Radius * c.Radius * Math.PI
        ElseIf TypeOf shape Is Rectangle Dim r Then
            Return r.Height * r.Length
        End If
        ' elided
        Throw New ArgumentException(
            message:= "shape is not a recognized shape",
            paramName:= NameOf(shape))
    End Function

Behavior of VB form identical to that of C# (should make emitter portion of compiler code real easy to do).

And this (C#):

    public static double ComputeAreaModernSwitch(object shape)
    {
        switch (shape)
        {
            case Square s:
                return s.Side * s.Side;
            case Circle c:
                return c.Radius * c.Radius * Math.PI;
            case Rectangle r:
                return r.Height * r.Length;
            default:
                throw new ArgumentException(
                    message: "shape is not a recognized shape",
                    paramName: nameof(shape));
        }
    }

Could be like this (VB):

    Public Shared Function ComputeAreaModernSwitch(shape As Object)
        Select Case shape
            Case Is Square Dim s
            Case Is Circle Dim c
            Case Is Rectangle Dim r
            Case Else
                Throw New ArgumentException(
                    message:= "shape is not a recognized shape",
                    paramName:= NameOf(shape))
        End Select
    End Function

Again, behavior of VB form identical to that of C# (quirks and caveats and all).

The `Is` part is extended to allow for a type identifier where a comparison operator would otherwise be, and the `Dim` part is optional. And something like `Case Is SomeTypeA, Is SomeTypeB` is valid. A mix of `Case Is SomeType` and/or `Case Is SomeType Dim x` with regular `Case SomeValue` in the same `Select Case` block is thus doable; and that would include something like `Case SomeValueX, Is SomeTypeA, SomeValueY, Is SomeTypeB, Is < 0`. I think `Case Is Nothing` should work in matching null; whereas something like `Case Is <> Nothing` should still work in getting at a default value.

I'll leave it to others if they see a need for `Case IsNot SomeType`. (I personally don't.)

I don't know where things stand for a `When` clause to the `Case` statement; so I don't know if an equivalent to a C# e.g. `case Square s when s.Side == 0` will ever be doable. Frankly I can't think of a situation where refactoring with `If` statement(s) in the `Case` code block couldn't suffice. But in any case, if `When` becomes a thing, then C# `case var x when ...` equivalent becomes thinkable; e.g. `Case Dim o When If(o?.Trim()?.Length, 0) = 0 : Return Nothing`.

**Comment by bandleader** [comment]
@zspitz Yes, that's the difference I meant -- thanks! 
BTW you can use VB syntax highlighting in Github comments using "```vb". See https://help.github.com/articles/creating-and-highlighting-code-blocks/#syntax-highlighting

**Comment by KathleenDollard** [comment]
I'm not quite sure how to label this. 

Yes, we want to solve the underlying problem - pattern matching. 
No, we don't know what the right syntax is, it might not be this explicit.

**Comment by zspitz** [comment]
@AdamSpeight2008 

> My concern with the following syntax proposal is, currently we are expecting "the thing" were checking against value being the first aspect of the clause.

`Select Case` already has constructs that don't test the subject of the `Select Case` against the first item in the `Case` clause:

    Dim i = 5
    Select Case i
        Case > 10 'the Is is optional
        Case < 25, > 47
        Case 0 To 15
    End Select

**Comment by zspitz** [comment]
@Nukepayload2 @paul1956 @rskar-git 

It's important to realize that pattern matching is not limited to type-checking; it simply means that the right side (of the `Case` clause, in this case) has a pattern of some sort, and the subject of the `Select Case` is checked against the pattern to see if it matches.

Pattern matching also enables isolating parts of the pattern and assigning to variables, of which the type-checking-and-casting-to-new-variable is only a specific case.

A third feature of pattern matching, is that it can be recursive -- patterns can contain other patterns.

For example:

    Dim o As Object
    '...
    Select Case o

         'tuple pattern which matches a 2-tuple, using identifier + type patterns to assign to x and y
        Case (x As String, y As Integer)
            Console.WriteLine($"This is a value tuple of two values; the first is a string {x}, and the second an integer {y}")

        'tuple pattern which matches a 2-tuple, using identifier patterns to assign to x and y
        Case (x, y)
            Console.WriteLine($"x = {x}; y = {y}")

        'Identifier pattern -- o is assigned to x
        Case x
            Console.WriteLine($"x = {x}")

        'String matching pattern -- https://github.com/dotnet/vblang/issues/140
        Case $"{protocol}://{rest}"
            Console.WriteLine($"The protocol is {protocol}; the rest of the URL is {rest}")

        'Select Case already supports some limited patterns:

        'range pattern -- matches if the subject is between the two values
        Case 1 To 10

        'comparison pattern -- matches if the comparison against the subject returns True
        Case > 15

        'OR pattern -- matches if either subpattern matches
        Case 1 To 10, > 15

    End Select

(I've described a potential general pattern matching syntax [here](https://github.com/dotnet/vblang/issues/124#issuecomment-416292181).)

**Comment by AdamSpeight2008** [comment]
@zspitz  it is still using the argument supplied to the `Select Case ...`.

**Comment by zspitz** [comment]
@AdamSpeight2008 So I don't understand what's wrong with this syntax:
```vb
Select Case node
    Case result As CompilationUnitSyntax 
        Return GetAttributeNodes(result.Attributes)
    Case TypeBlock As TypeBlockSyntax
        ' Do something else with TypeBlock
        Return Something
End Select
```
The subject of the `Select Case` is also being matched against the pattern.

**Comment by paul1956** [comment]
@zspitz pattern matching might be the swiss army knife of programming and if I could have it today I would be happy. If priorities need to be made VB desperately needs just what you showed in the example directly above. My code is full of "If" statements trying to duplicate it without the simplicity.

**Comment by zspitz** [comment]
@paul1956 @reduckted AFAICT the LDT is [not going to move forward if the syntax doesn't scale to generalized pattern matching](https://github.com/dotnet/vblang/issues/304#issuecomment-396124795).

In the meantime I use the following:
```vb
Public Function ExecIfType(Of T)(toTest As Object, action As Action(Of T), Optional [else] As Action = Nothing) As Boolean
    If TypeOf toTest Is T Then
        action?.Invoke(toTest)
        Return True
    End If
    [else]?.Invoke
    Return False
End Function
```
and can be used as follows:
```vb
Dim o As Object
'...
Select Case True
    Case ExecIfType(Of String)(o, Sub(s) Console.WriteLine(s.Length)
    Case ExecIfType(Of Integer)(o, Sub(i) Console.WriteLine(i + 5)
End Select
```
or like this:
```vb
ExecIfType(Of Random)(o, Sub(rnd) Console.WriteLine(rnd.Next), Sub() Console.WriteLine("Not a Random"))
```

**Comment by paul1956** [comment]
@zspitz Sorry for the delayed reply. The issue with your nice workaround is it makes for very long lines and I don't see how it works for the use case where the Case needs to return a value as in the examples.  What is the current status of getting something in VB?

**Comment by zspitz** [comment]
@paul1956 It's possible to convert `ExecIfType` to return a value, although what I usually would do is create a local variable and set it within the body of the lambdas passed to `ExecIfType`.
