### ISSUE TITLE
In and Out operators

### ISSUE THREAD

**Issue by AdamSpeight2008** [dotnet/vblang#305]
# In and Out operators
## In Operator
```
Syntax InBinaryOperator Inherits BinaryOperatorSyntax
  Left      As ExpressionSyntax
  InKeyword As InKeywordToken
  Right     As ExpressionSyntax
End Syntax
```
The in operator takes it left operand and see if it is contained in it right operand. RightOperand must have the `Contains` pattern. `ICollection`

```vbnet
If x In { 0, 1, 2, 3, 4, 5, ... } Then
```

It could also use with `TypeOf` expression, *may need a little shoehorning of those expressions*. To permit check against multiple possible types. See #23
```vb
If TypeOf expr Is In { T0, T1, T1 } Then
```

## Out Operator
```
Syntax OutBinaryOperator Inherits BinaryOperatorSyntax
  Left       As ExpressionSyntax
  OutKeyword As OutKeywordToken
  Right      As ExpressionSyntax
End Syntax
```
The `Out` operator takes it left operand (primarily `TypeOf` expressions) and directly casts it to the right operand. If the identifier on the right operand isn't declared, it is explicitly declared and initialise, with that result of the cast.

```vbnet
If TypeOf obj Is T Out result Then
  ' Dim result = DirectCast( obj, T ) 
End If
```

In theory we should also be able to write
`If TypeOf expr Is In { T0, T1, T1 } Out result Then`, which has the following operator precedence if the he implied parenthesis are stated.
`If (TypeOf (expr) Is (In { T0, T1, T1 })) Out (result)) Then`

**Comment by KathleenDollard** [comment]
@AdamSpeight2008 

On the In operator... is this just a cleaner way to write 

```VB
If {0,1,2,3,4}.Contains(x) Then
```

And the second example cleaner version of 

```
If {GetType(T0), GetType(T1)}.Contains(expr.GetType) Then
```

The `Out` operator looks similar to C# 7's `out`keyword. Is that the intent?

**Comment by AdamSpeight2008** [comment]
Yep the `In` operator, would support that. Though I thinking it be more pattern based like LINQ, so that it could work with other kinds of object. Eg Intersecting `TextSpan`, `Point` etc.

The second on is an alternative form of #23. as an example of using both `In` and `Out` in the same expression. It would be akin to `out var` in C#.
eg
```C#
string s = "Hello";

if (int.TryParse(s, out var result))
{

}
```

but I'm think of allowing the `declaration` to be defined at that point of use. Technically on the `BoundOutVariableNode`, which allows the *code block* it on inside to determine it's scope.
 Does the scope expand to the outer scope or narrows to the inner scope.
`Out Declarations` are useful when combined with the `Select TypeOf` proposal (see #304). especially if we also have `guard expressions` (`When Result > 0 `) on the Case Clause Statement.

**Comment by AdamSpeight2008** [comment]
It may not be as valuable in that case, as I'm thinking `result` having the type, common to all values in the list. A bit like collection type inference. 

```
TypeOf expr Is In { T0, T1, T2 } Out result
' expanded out to
(TypeOf expr Is T0 Out result) OrElse (TypeOf expr Is T1 Out result) OrElse (TypeOf expr Is T2 Out result)
```

**Comment by gafter** [comment]
The proposed `Out operator appears to be a subset of what we'd do to support pattern-matching as we added in C# 7 and 8. If we were to do pattern-matching, I think we'd prefer a syntax form that can generalize to full pattern-matching.

**Comment by zspitz** [comment]
Aren't your proposed `In` and `Out` two completely different things? Is there any connection between them?
