### ISSUE TITLE
An ambiguity that is not!

### ISSUE THREAD

**Issue by MohammadHamdyGhanem** [dotnet/vblang#309]
NOTE: I edited the post to give an easy to re-produce example.

I have this code in a a VB project called WindowsApp1:
```
Namespace Test
    Public NotInheritable Class Methods
        Public Function Group(X As String) As String
            Return X
        End Function
    End Class


    Public Class Group

        Public Sub New(x As String)

        End Sub


    End Class
End Namespace
```

In a form1 code page I added:
```
Imports WindowsApp1.Test
Imports WindowsApp1.Test.Methods
```

Then I addedd a button on the form, and wrote this in its click event handler:
```Dim x = Group("test")```
VB.NET find this ambiguous ! This code gives the error:
> 'Group' is ambiguous, imported from the namespaces or types 'RegexBuilder, RegexBuilder.Patterns'

While this is fine:
```Dim x = New Group("test")```

The strange thing is that I use the same code in C# and it is not ambiguous there!
VB.NET can easily realize that Group("abc")
 is a method call and there is only one method with this signature, so, there is no actual ambiguity

**Comment by rskar-git** [comment]
Sorry, but the example code doesn't really illustrate the issue. For starters, where is Pattern defined? Is the `"abc"` of `Group("abc")` meant to be automatically be converted into a Pattern? And where exactly is that `Dim p = Group("abc")` going? I tried to follow along, and got to this:

	Imports RegexBuilder
	Imports RegexBuilder.Patterns

	Namespace RegexBuilder
		Public Class Group

		End Class

		Public NotInheritable Class Patterns

			Public Shared Function Group(
				  ParamArray patterns() As Pattern) As Group

				Return Nothing
			End Function

			Sub foo()
				Dim p = Group("abc")
			End Sub

		End Class

	End Namespace

**Comment by MohammadHamdyGhanem** [comment]
Sorry, I  forgot to add the link to the reop:
https://github.com/MohammadHamdyGhanem/Verex
You can reference Verex.dll in C# project and VB.NET project and add the above imports and try the code.

**Comment by MohammadHamdyGhanem** [comment]
By the way, The patterns "ststic" class has shared methods with the same names as the calsses defiend in the RegexBuilder namespace. I do that to write the names directly without the new part, and do other things. This worked fine in C# where I wrote the code first, but I face this issue in when testing it in VB.NET.

**Comment by MohammadHamdyGhanem** [comment]
@rskar-git 
I had to change all class names to avoid this conflict. I will not upload the changes for 6 hours, so you can test the isuue, or at least copy the old project to your PC.
I hope VB.NET get rid of this false ambiguity.
Thanks.

**Comment by pricerc** [comment]
Do you possibly have both a property and a function called 'Group', where the property is an indexer ? e.g. can you do both of these in C# code using your library:
```C#
var a = Group["abc"];
var b = Group("abc");
```

if so, these would be ambiguous in VB.

**Comment by MohammadHamdyGhanem** [comment]
@rskar-git @pricerc 
I recreated the same situation in VB:

```
Namespace WindowsApp1.Test
    Public NotInheritable Class Methods
        Public Function Group(X As String) As String
            Return X
        End Function
    End Class


    Public Class Group

        Public Sub New(x As String)

        End Sub


    End Class
End Namespace
```

In a form1 code page add:
```
Imports WindowsApp1.Test
Imports WindowsApp1.Test.Methods
```

now add a button on the form, and write this in its click event handler:
```Dim x = Group("test")```
VB.NET find this ambiguous !
While this is fine:
```Dim x = New Group("test")```

**Comment by Nukepayload2** [comment]
@pricerc 
> Do you possibly have both a property and a function called 'Group', where the property is an indexer ? 

No, because the following code won't compile.
```c#
    public class Parent
    {
        public GroupIndexer Group { get; set; }
        public int Group() { return 0; } //Error CS0102
    }
    public class GroupIndexer
    {
        public int this[int index] => 0;
    }
```

**Comment by AnthonyDGreen** [comment]
The second case is not ambiguous because after `New ` the compiler is only looking for types and namespaces. It's a completely different look-up context that doesn't include methods or fields or locals so there's no way for the method `Group` to create an ambiguity. But in just a regular expression context all kinds of references are valid. So, for example, if you wrote:

``` VB.NET
Group.Equals(123)
```

That could be a reference to the shared `Equals` method on the `Group` type, or an instance method `Equals` on a shared `Group` property returning a singleton, or a argumentless invocation of a Shared `Group` function that returns something. Not in your exact example, but in theory any of those scenarios could be constructed. The compiler doesn't "wait and see" what the entire expression is before reporting an ambiguity (in this case). When it tries to find `Group` it finds two things--a type and a method group--so it's ambiguous. I suspect this is by design and would be on the risky side to change.

It is an intriguing coding pattern you've described though. Very similar to what we do with our `SyntaxFactory` methods in Roslyn. I've written code almost exactly what you have here and the only thing that has saved me from encountering the ambiguity is that we suffixed all of the Roslyn syntax nodes with `Syntax` and the factory methods omit that suffix. But it would suck if I couldn't use just `Imports` the factory type to shorten all of the object construction code.

I do like the workaround of renaming the `Pattern` subtypes with a suffix. But you might also try moving the import of the containing namespace into a project-level import and leaving the import of the static class at the file-level. I believe VB will check the file-level imports before the project-level ones thus avoiding the ambiguity.

**Comment by MohammadHamdyGhanem** [comment]
@AnthonyDGreen 
Thanks for your detailed response.
But, I think you should give this case some analysis, because as I said, it is not an issue in C#, so the code designed by C# doesn't consider who VB.NET treats it.
I tried to define a Default shared property (default stativ indexer) but it is forbidden, so, there is no way to think of  Group in
```Dim x = Group(1)```
as a class, so if the ambiguity is between a class name or a method name, the absence of the new keyword is enough to eliminate the ambiguity.
The same with:
```Dim x = Group(1).[Member]```
The ambiguity can appear in:
```Dim x = Group.foo()```
and it should be ambiguous only and only if the Group class has a shared member foo, and the Group method returns an abject with an instance method foo with the same signature, which is possible only if the Group return type is not the Group class type. So, In my case it is impossible in all cases to have an ambiguity, and in general the only possible ambiguity is when the static Group.foo() in has the same signature of the instance Group.foo() where Groupe method return type <> Group Class type.
I think using these roles to fix this issue is safe and will not break any excising code. Once again, this particular case is when one of the two names is a class and the other is a property or a method. If  the name refers to two classes or two members, the it is ambigious.
You also can take a look at c# compiler to see how it solves this issue.
thanks

**Comment by rskar-git** [comment]
Ah, OK then, I got it now! For everyone else, here's what lays it out.

First a module (e.g. ClassMod.vb):

	Namespace WindowsApp1.Test

	#If 1 Then
		' Making Group a Shared Function (or Property) is the only way a statement
		' like `Dim x = Group("test") can be something compile-able.
		Public NotInheritable Class Methods
			Public Shared Function Group(X As String) As String
				Return X
			End Function
		End Class
	#Else
		Public NotInheritable Class Methods
			Public Function Group(X As String) As String
				Return X
			End Function
		End Class
	#End If

		Public Class Group
			Public Sub New(x As String)

			End Sub
		End Class

	End Namespace

And now a Form (e.g. Form1.vb):

	#If 0 Then
	'Order of Imports statements don't matter.
	Imports Issue309.WindowsApp1.Test.Methods
	Imports Issue309.WindowsApp1.Test
	#Else
	'Imports WindowsApp1.Test
	'Imports WindowsApp1.Test.Methods
	Imports Issue309.WindowsApp1.Test
	Imports Issue309.WindowsApp1.Test.Methods
	#End If

	Public Class Form1
		Private Sub Button1_Click(sender As Object, 
		    e As EventArgs) Handles Button1.Click

			'The following statements all work, no problems here:
			Dim o1 As New Group("obj1")
			Dim o2 = New Group("obj2")
			Dim o3 As Group = New Group("Obj3")
			Dim o4 = CType(Nothing, Group)
			Dim o5 = DirectCast(Nothing, Group)

			'The bone of contention right here - flagged as ambiguous, whether
                        'Methods.Group is Shared or not:
			Dim x = Group("test")  ' <= Group the Function, not the Class
			'The above shouldn't compile anyway when Group isn't Shared.
			'    However, when Group function is Shared, 
			'        should ambiguity error go away?

			'The obvious work-around, for Shared Function Group:
			Dim xx = Methods.Group("test")
			'And for non-Shared, a non-issue anyway (no problems then):
                        'Dim myMethods As New Methods()
			'Dim xx = myMethods.Group("test")

		End Sub
	End Class

It should be noted that if `Methods.Group` was defined as a `Shared Property` instead, it would still show this ambiguity issue.

**Comment by gafter** [comment]
In VB, a shared default indexer makes it possible to index a type. That is why the lookup for `Group` in `Group("test")` includes both types and methods. In this program, that lookup results in an ambiguity.

C# doesn't have this problem because C# doesn't have default indexers.

This is by design.

**Comment by MohammadHamdyGhanem** [comment]
@gafter 
I don't get it.. 

I tried to define a shared property as you say:
```
Class Foo
    Default Public Shared Property Item(i As Integer) As String
        ' ...........
    End Property
End Class
```
But VB.NET says:
> 'Shared' cannot be combined with 'Default' on a property declaration.

So, how can a I define a  "shared default indexer" in VB.NET?

**Comment by gafter** [comment]
@MohammadHamdyGhanem Hmm, good point.

In C#, the language specifies how name lookup works, and in the [context of a call name lookup ignores type names](https://github.com/dotnet/csharplang/blob/master/spec/expressions.md#member-lookup).

In VB, the language specifies how name lookup works. [It is not context dependent in the same way that C# is](https://github.com/dotnet/vblang/blob/master/spec/expressions.md#simple-name-expressions).

We do not have a proposal to change how name lookup works in VB, and I doubt we could make such a change without breaking compatibility.

**Comment by MohammadHamdyGhanem** [comment]
@gafter 
Conseder this 
> proposal to change how name lookup works in VB

:)
I suggested how this case is treated without risk:
https://github.com/dotnet/vblang/issues/309#issuecomment-396053567
At least put it in mind to the future. No rush :)
