### ISSUE TITLE
Comments should strongly prefer to be attached as trailing trivia rather than leading.

### ISSUE THREAD

**Issue by AdamSpeight2008** [dotnet/vblang#313]
Comments that are in a block structure like
 * `Select Case ... End Case`,
 *  `If .. Then .. ElseIf ... Else ... End If` 

are attached as trivia, in rather unexpected way.
``` vbnet
Select Case value
  Case 0
    ' comment
    Console.WriteLine()
    ' comment
  Case 1
    ' comment
    Console.WriteLine()
    ' comment
  Case Else
    ' comment
    Console.WriteLine()
    ' comment
End Select
```
*In the follow `{| ... |}` indicates the text span on which comment is part of.*
You initially expect the comments to be laid out in the following blocks.
```
Select Case value
  Case 0
    {|' comment
    Console.WriteLine()
    ' comment|}
  Case 1|}
    {|' comment
    Console.WriteLine()
    ' comment|}
  Case Else
    {|' comment
    Console.WriteLine()
    ' comment|}
End Select
```
but it rather strangely it is the following
```
Select Case value
  Case 0
    {|' comment
    Console.WriteLine()|}
    {|' comment
  Case 1|}
    {|' comment
    Console.WriteLine()|}
    {|' comment
  Case Else|}
    {|' comment
    Console.WriteLine()|}
    {|' comment
End Select|}
```

I'm proposing that comments should attach to near *"block"* strongly prefering to be trailing trivia rather that leading trivia.

I'm saying that `CaseBlockSyntax.FullSpan` should contain the comments after the last executable instructions. Eg
```vb.net
  Case 0
    ' comment
    Console.WriteLine()
    ' comment
```
Which also means the `.ToString` would also return the section of code.

**Comment by sharwell** [comment]
We make a ton of assumptions about the association of trivia to tokens in StyleCop Analyzers. We aren't analyzing VB code in that project, but if the association were to change in a future release, I would expect it to make it very difficult for analyzers to work in both older and newer versions of Roslyn. Trivia is already a difficult area to understand, so I'd be apprehensive to make the overall situation worse for extension developers.

**Comment by AdamSpeight2008** [comment]
@sharwell  I'm trying to make it easier for extension developers, by put in the place you'd think logically should be. Hence not having to go exploring to find where it actually is.
The situation is a lot worst for the `If ... Then ... End If` block structure.  where the *trailing comment* are potentially on different part `ElseIf`, `Else`, `End If` since those are optional sub structures of the if then block.

**Comment by sharwell** [comment]
The best way to do that is probably documenting the current rules for trivia placement. That way new users can easily find the correct trivia, and existing users can continue working with correct knowledge already gained from experience. 😄

**Comment by gafter** [comment]
We are not going to change the rules for the attachment of trivia.
