### ISSUE TITLE
Provide easier mechanism to set Visual Basic language version

### ISSUE THREAD

**Issue by KathleenDollard** [dotnet/vblang#327]
I am opening this issue in response to comments on the unrelated #320.

Mechanisms for updating 

1) [Update the vbproj](https://docs.microsoft.com/en-us/dotnet/visual-basic/language-reference/configure-language-version) Available today, most certainly not a traditional "VB" way of doing things.
2) An analyzer that helps you upgrade if you use a new feature
  * This has the downside of you knowing the feature you want to use, but if you don't know it, why would you care if you upgrade?
  * It has the upside of being part of the OSS Roslyn work
3) Updating the Options dialog in Visual Studio.

A key part of our forward facing work is to make the xxproj file the natural way to do many things. It is a much different experience than old style xxproj files and will be a way to do many common things like setting target frameworks.

**Comment by paul1956** [comment]
@KathleenDollard to address point 2 above; in 15.5 there is already a CodeFix that produces the error so you actually don't need to know about the feature. Just click on the screwdriver while the cursor on a middle unnamed parameter. This is how I found it, and I liked that I could name True and False without creating a temp variable. I like is so much that I have refactored my whole codebase to use it, then got tripped up on my tests failing.

**Comment by reduckted** [comment]
There was already an issue created about this not so long ago (#308), but it was closed and moved to https://github.com/dotnet/roslyn/issues/28557 and https://github.com/dotnet/project-system/issues/3141.

**Comment by KathleenDollard** [comment]
@paul1956 Fantastic!

@reduckted My mistake. I searched open issues. I'm closing again.

**Comment by reduckted** [comment]
No problem. It sounded familiar, but I couldn't find it in this repo either (I didn't think to search in closed issues either). I went and found the issue in the Roslyn repo and found the reference to it there. 🙂
