### ISSUE TITLE
Make Optional optional

### ISSUE THREAD

**Issue by JustNrik** [dotnet/vblang#354]
Yea it sounds a bit redundant :thinking: 

I think Optional keyword should be optional just like ByVal. Why? Because assigning a value to a parameter should be implicitly considered as an optional parameter, this will reduce a bit the verbosity of the language.

What do you think?

**Comment by zspitz** [comment]
This seems to be a duplicate of #174.

**Comment by zspitz** [comment]
@bandleader I don't think this can be done within VB.NET, as I've noted [here](https://github.com/dotnet/vblang/issues/174#issuecomment-439638287).

**Comment by bandleader** [comment]
@zspitz You are right that that is a duplicate. @KathleenDollard, could you please mark as duplicate?

I commented on #174.

>I think there is some expectation that arguments should be declarable the same way.

@zspitz Just wanted to note that AFAIK we don't currently support optional parameters without initializers, so I don't think there is an expectation per se. That said, I commented on #174 as to that issue.

**Comment by KathleenDollard** [comment]
Duplicate of #174
