### ISSUE TITLE
Wizard based new project templates like in <VB6

### ISSUE THREAD

**Issue by rrvenki** [dotnet/vblang#364]
Like we had wizard based new project templates in pre dotNET period, wish to have them now.  That will solve a great deal of challenges while creating projects like ASP MVC which involves Azure AD login, Password reset/recover screens, social media logins integration, choose between themes, choose .NET standard or .NET core, Choose EF6 or EF Core, Choose the db connection/its parameters etc.  Not only for ASP, these wizard options for WinForms/wpf, UWP, Xamarin will also be a great deal.

This will add immense charm to VB (B#) and it will once again become a good RAD tool.

**Comment by KathleenDollard** [comment]
Templating issues are in the repo https://github.com/dotnet/templating. It isn't a language or VB specific issue (any improvements could also benefit C#). 

I'm going to close this so it can be reopened in that repo.
