### ISSUE TITLE
CheckForIllegalCrossThreadCalls and default threading in B#

### ISSUE THREAD

**Issue by rrvenki** [dotnet/vblang#365]
In VB6 the default was apartment thread. In .NET we have multi thread. But to access cross threads we need to use delegates. In addition we have concurrent and parallel threads.
Its high time there has to be a "long time plan" to make the default core thread of an app address to these variable options.
Without using delegates, the standard calls to other subroutines and functions should use concurrency or parallel threads as appropriate.  I understand this may be a ground breaking change in the compiler. But it is time to shift to that stage as hereafter, the future is definitely not going to have a single core single thread CPU. Then why have default app thread run in that mode?

**Comment by KathleenDollard** [comment]
Multiple threads require more than just starting. They require waiting for threads to return and combining and piping values as needed. I don't think current code is rich enough to do this correctly. 

We have a mechanism - with programmer intervention, which is async/await.
