### ISSUE TITLE
Like operator is not supported in .NET Core

### ISSUE THREAD

**Issue by JohnyL** [dotnet/vblang#373]
- OS: Windows 10 x64
- Project: Console .NET Core 3.0 (3.0.100-preview-009812)

The following code doesn't compile:
```
Dim s As String = "ZZK99"
If s Like "##K*" Then
End If
```
Error:

> Error BC37234: Like operator is not supported in current project type

What's the reason it's not supported?

**Comment by JustNrik** [comment]
Because .NET Core doesn't fully support VB and F# yet. As far as I know they will be fully supported on .NET Core 3 RELEASE so let's just be patient ;P

**Comment by ericmutta** [comment]
See [#2605](https://github.com/dotnet/roslyn/issues/26058) for some more on this (including workarounds) until .Net Core 3 comes out.

**Comment by DualBrain** [comment]
I'm happy to report that this does appear to work with the latest bits (nightly build)!

    Dim s As String = "ZZK99"
    If s Like "**K*" Then
      Console.WriteLine("Is LIKE!")
    Else
      Console.WriteLine("Is NOT like!")
    End If

Compiles and results in Is LIKE! I'm not sure if there are multiple people to thank for this; however, I see a lot of recent commits by @cston so I'm guessing we have him to thank (as well as @KathleenDollard for driving the project forward). :-D

**Comment by JohnyL** [comment]
@DualBrain Yes, I confirm that now **LIKE** works as expected! 😊 Thanks everyone!
