### ISSUE TITLE
VS IDE tab support

### ISSUE THREAD

**Issue by rrvenki** [dotnet/vblang#375]
When I already have part of keyword already in editor and intellisense suggests remaining part, I press TAB key to bring the remaining part of the keyword. But if the already existing part is the succeeding part, the full intellisense word and existing word both comes to editor which makes cumbersome to use TAB key.
For example, If I have "MsgBox" already in code editor and I type "Sho" before "MsgBox", the intellisense would prompt "ShowMsgBox" (which is already a function from another code).  I press TAB and the result would be "ShowMsgBoxMsgBox".  I have to remove the extra "MsgBox" in this case.  This is same case in XAML editing also.
I request you to make the Intellisense to work on the entire word in case of TAB than just inserting the suggested word irrespective of existing/appended word. This is a silly issue but would save a lot of code building time.

**Comment by reduckted** [comment]
This issue is better suited to the [dotnet/roslyn](https://github.com/dotnet/roslyn/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+intellisense) repo.

**Comment by franzalex** [comment]
@reduckted

It appears to me that this is an IDE-specific issue, not one to do with the analyser. As such it should be migrated to the IDE repo (I don't know which one that is) instead of the dotnet/roslyn repo.

That said, it's clear that this issue doesn't fit in this particular repo's definition of terms.

**Comment by reduckted** [comment]
There are some issues in that repo about code completion, but yeah, I'm not really sure if it's the _best_place. Just better than here. I'm never quite sure where the line is between Visual Studio and Roslyn. :smile:

The best option is probably to "Report an Issue" within Visual Studio. That will make sure the right people get to see it, and then that team can create an issue in the best place.

**Comment by CyrusNajmabadi** [comment]
Closing out as this is unrelated too the vb language specification.
