### ISSUE TITLE
Proposal: Try expression

### ISSUE THREAD

**Issue by VBAndCs** [dotnet/vblang#389]
I suggest to add a Try expression:
`Dim x = Try([expr], [value if expr raise exception])`

It is similar to the If(x y)  expression, except it yields the first expression if it doesn't cause exception. If it does, it suppresses the exception and returns the second expression. Try expression should evaluated to this block:

```VB.NET
Dim x = value
Try
    x = expr;
Catch

End try
```

Ex: I will give an example of the Parse method. I know there is a TryParse method to solve this, but not all built-in methods or user defined functions have a TryXX version, besides this is not just for functions but any expression that can produce a value or raise exception:

```VB.NET
Dim n = Try(Int.Parse(s), 10)
Dim m = Try(10 / n, 1)  ' produces 1 if n = 0
```

```VB.NET
Dim n = 10
Try
    x = Int.Parse(s);
Catch

End try

Dim m = 1
Try
    m = 10 / n;
Catch

End try

```

Note:
The second expression can throw an exception:
`Dim x = Try([Expr], Throw New Exception("msg"))`
this is still a shortcut for:
```VB.NET
Dim x As [Infered type from expr]
Try
    x = expr;
Catch
     Throw New Exception("msg")
End try
```

#EDIT:
I would also propose another Try expression:
`Dim success As Boolean= Try (expr)`
try returns false if the expr throws an exception.
ex:
```VB.NET
If Try(Dim i = Convert.ToInt32(o))
   DoSomething(i)
ElseIf Try(Dim i = Convert.ToInt64(o))
   DoSomething(i)
ElseIf Try(Dim i = Convert.ToIntDecimal(o))
   DoSomething(i)
ElseIf Try(Dim i = Convert.ToDouble(o))
   DoSomething(i)
```

**Comment by reduckted** [comment]
Suppressing exceptions is generally frowned upon. Yes, you have to do it occasionally, but I would hope it's not done often enough to require first-class language support.

> I will give an example of the Parse method. I know there is a TryParse method to solve this

Can you give a _real_ example then? It's hard to see why this is needed if the only example you can give already has a workaround.

> ```vb
> Dim n = Try(Int.Parse(s), 10)
> Dim m = Try(10 / n, 1)  ' produces 1 if n = 0
> ```

But that's just being lazy and letting an exception be thrown for no reason. You can easily avoid that situation:
```vb
Dim m As Double
If n = 0 Then
    m = 1
Else 
    m = 10 / n
End If
```
Or, if you wanted a one-line statement:
```vb
Dim m = If(n = 0, 1, 10 / n)
```

**Comment by VBAndCs** [comment]
@reduckted 
We can't  prevent exceptions in all cases, so we have Try Catch.
Here is some example:
`Dim n = Try(someStream.ReadInt(), 10);`

**Comment by rskar-git** [comment]
Sorry, but `Dim n = Try(someStream.ReadInt(), 10)` isn't much of an example. Using an exception to detect an end-of-stream situation is very inefficient (assuming a BinaryReader). Any other exception would mean the stream is in a bad place, which goes undetected (and that would no doubt lead to some challenging troubleshooting).

**Comment by VBAndCs** [comment]
I would also propose another Try expression:
`Dim success As Boolean= Try (expr)`
try returns false if the expr throws an exception.
ex:
```VB.NET
If Try(Dim i = Convert.ToInt32(o))
   DoSomething(i)
ElseIf Try(Dim i = Convert.ToInt64(o))
   DoSomething(i)
ElseIf Try(Dim i = Convert.ToIntDecimal(o))
   DoSomething(i)
ElseIf Try(Dim i = Convert.ToDouble(o))
   DoSomething(i)
```

**Comment by JustNrik** [comment]
The idea is really bad and encourages code/design smell tbh.

**Comment by VBAndCs** [comment]
Ok. Since it is rejected, I can implement the first form like this (based on HaloFour's work):
```VB.NET
    Function TryEval(Of T)(expr As Func(Of T), value As T) As T
        Try
            Return expr()
        Catch ex As Exception
            Return value
        End Try
    End Function
```

`Dim d = TryEval(Function() Date.Parse("13/13/2019"), Now)`

And the second can be implmented like this:
```VB.NET
    Function TrySet(Of T)(expr As Func(Of T), <Out> ByRef value As T) As Boolean
        Try
            value = expr()
            Return True
        Catch ex As Exception
            value = Nothing
            Return False
        End Try
    End Function
```

```VB.NET
        Dim O As Object = "1st"
        Dim I As Integer
        If TrySet(Function() Convert.ToInt32(o), I) Then
            Console.WriteLine(I)
        Else
            Console.WriteLine("bad value")
        End If
```

It will be very nice If we can declare the out variable in place like C# does:
```VB.NET
        Dim O As Object = "1st"        
        If TrySet(Function() Convert.ToInt32(o), Dim I) Then
            Console.WriteLine(I)
        Else
            Console.WriteLine("bad value")
        End If
```

Thanks

**Comment by VBAndCs** [comment]
And this is a third one:
```VB.NET
    Function TryExecute(action As Action) As Boolean
        Try
            action()
            Return True
        Catch ex As Exception
            Return False
        End Try
    End Function
```
