### ISSUE TITLE
Try Resume

### ISSUE THREAD

**Issue by VBAndCs** [dotnet/vblang#391]
VB.NET has a legacy `On Error Resume Next` to suppress exceptions, but it  affects all next statements until the end of the function, and it can't co-exist with Try Catch.
I wish to have a better statement with a block that ignores exception, say:
```
Try Resume
     '  ....................
     ' Suppress all exceptions inside this block
     '  ....................
End Try
```

**Comment by rskar-git** [comment]
You may need to show a compelling use-case which demonstrates why there's a true need to support an anti-pattern like that. It would have to be something where a specialized `Sub` or `Function` which begins with `On Error Resume Next` simply can't be made to work.

**Comment by VBAndCs** [comment]
@rskar-git

```VB.NET
Try
    Foo1()
Catch

End Try

Try
        Foo2()
Catch

End Try

Try
    Foo3()
Catch ex as exception
    Msg(ex.Message)
End try          
```

It can be reduced to
```VB.NET
Try Resume
     Foo1()
     Foo2()
End Try

Try
    Foo3()
Catch ex as exception
    Msg(ex.Message)
End try  
```

**Comment by rskar-git** [comment]
My question was not about syntactic sugar. `On Error Resume Next` is already regarded as an anti-pattern, and you want to enshrine it with `Try Resume`. The general advice on whenever there is the (highly dubious) need to ignore all exceptions is to encapsulate it in its own function, complete with comments on why the necessity. So your example could be handled today like so:

    Sub DangerousFoo()
        ' We are communicating with a very flaky networked
        ' device using its quite unreliable protocol. The
        ' vendor of said device has gone out of business.
        ' Defaults are used so that other processing may 
        ' continue, as detailed in document XYZ123PDQ.
        On Error Resume Next
        Foo1()
        Foo2()
    End Try

    Sub LetUsDoTheseFoo()
        DangerousFoo()
        Try
            Foo3()
        Catch ex as exception
            Msg(ex.Message)
        End try  
    End Sub

**Comment by VBAndCs** [comment]
@rskar-git  
Based on your solution, it is better to use lambda subs so the code stays in one place and access all local variables without the need to pass all of them to another sub:

```VB.NET
    Sub TryResume(action As Action)
        On Error Resume Next
        action()
    End Sub
```

```VB.NET

TryResume(Sub()
     Foo1()
     Foo2()
End sub)

Try
    Foo3()
Catch ex as exception
    Msg(ex.Message)
End try   
```

**Comment by VBAndCs** [comment]
But there is still a problem:
`On error resume next` exits the sub immediately after the line than caused the error, and this is not the behavior I wanted from `Try Resume`.. Try:
```VB.NET
TryResume(Sub()
     Console.WriteLine("Line 1")
     Throw New Exception()
     Console.WriteLine("Line 2")
End Sub)
Console.WriteLine("Line 3")
```

This will print:
> Line1
> Line3

This is not the behavior I want.

**Comment by VBAndCs** [comment]
Note:
When I called a normal sub that contains the `on error resume next` it worked fine and `Line 2` appeared in the output!
The On error resume next breaks any clled sub when error happens and resums the next line to the caller! This behavior will prevent using lambda subs, as VB.NET refuses to use 'on error resume next` inside lambdas!
So, no other way than deviding code between two subs, and passing all necessary vars by ref to the one with the 'on error resume next` !
