### ISSUE TITLE
Proposal: Redim Initializer

### ISSUE THREAD

**Issue by VBAndCs** [dotnet/vblang#414]
I suggest this:
```VB.NET
Dim A() As Integer = GetArray()
ReDim Preserve A() From {5, 6, 7, 8}
```

The last sentence is equivalent to:
```VB.NET
Dim L = A.Length
ReDim Preserve A(L + 3) 
A(L) = 5
A(L + 1) = 6
A(L + 2) = 7
A(L + 3) = 8
```
In case of Redim without preserve:
`ReDim A() From {5, 6, 7, 8}`
It is equal to:
`A= {5, 6, 7, 8}`
The second is better of course, but we can have this:
`ReDim A(5) From {5, 6, 7, 8}`
In this case, we initialize only the first 4 cells of the array.
This can be used also with Preserve:
`ReDim Preserve A(10) From {5, 6, 7, 8}`
It will initialize only the first four of the newly appended cells.
If the new cells are less than 4, we can decide wither or not it cause a run time error.

I also suggest this shortcut:
` ReDim [Preserve] A(-2) `
for:
` ReDim [Preserve] A(A.Length-3) `
-2 means: take out the last two cells.

**Comment by paul1956** [comment]
Right now I just use Lists to do this (my code doesn't really care about high performance I assuming this would be faster then List(Of Integer)). This would be incredible useful, much simpler, less error prone and easier to read. I might use Append as the keyword instead of From to make it even clearer what is happening.

**Comment by VBAndCs** [comment]
I thought of this alternative :
Redim Preserve A() += {1, 2, 3, 4}

But note that arrays are immutable,  and Redim Preserve creates a new array and copies the old values to it. This proposal doesn't chabge that performance.

**Comment by VBAndCs** [comment]
In fact, I thought about extending this to include collections:
`myList += {1, 2, 3, 4}`
which can call the Add method (if it accepts a collection)
`myList.Add( {1, 2, 3, 4})`
but this is not a language feature, becuase it can be done by overloading the + operator.

**Comment by pricerc** [comment]
Basically, what @paul1956  said.

As a rule, you should be using collections, not arrays. Arrays have their uses, but their use should generally be considered 'discouraged' in a modern .NET application.

`Redim Preserve` is a potentially expensive operation, at worst, the whole array needs to be copied to a new, larger memory location, and all references to it updated, so it can be O(N) operation.

If you use one of the many collection objects, `List(Of T)` being the closest in use to an 'Array', then you get the benefits of ease-of-use, and all the performance optimisations implemented in corefx.

**Comment by pricerc** [comment]
> ReDim [Preserve] A(-2)

vs

> ReDim [Preserve] A(A.Length-3)

For me, the test of whether something is a good pattern for VB, is whether my friend Trevor, who is not a programmer, would be able to understand it without explanation. I would argue that your proposal would fail this test.

**Comment by pricerc** [comment]
> In fact, I thought about extending this to include collections:
> `myList += {1, 2, 3, 4}`
> which can call the Add method (if it accepts a collection)
> `myList.Add( {1, 2, 3, 4})`
> but this is not a language feature, becuase it can be done by overloading the + operator.

I initially thought this had potential (actually, I still do), but then I realised that  `myList += {1, 2, 3, 4}` is actually ambiguous.

The immediately obvious meaning is "Append these values to the list", but it could also be interpreted as a set operator:
```
myList(0) += 1
myList(1) += 2
myList(2) += 3
myList(3) += 4
```

So there's probably a case to be made that because some people might want to implement a `+` operator to work this way, that it's better to not to implement + as an 'Append' operator.

Perhaps VB's concatenation operator (`&`) would be a better fit.

**Comment by ericmutta** [comment]
> @pricerc As a rule, you should be using collections, not arrays. Arrays have their uses, but their use should generally be considered 'discouraged' in a modern .NET application.

I second this :+1:  If you need to resize your arrays, it is better to use `List(Of T)` which wraps all that behaviour in a standard way. Combined with LINQ and methods from the [Enumerable](https://docs.microsoft.com/en-us/dotnet/api/system.linq.enumerable?view=netframework-4.7.2) class, you get a lot more power and flexibility than when using raw arrays.

The only time I use arrays these days is when dealing with binary data (so arrays of bytes or integers or longs would apply) where the array lengths stay stable (e.g. you can allocate a 4KB buffer that stays that way for life).

**Comment by jrmoreno1** [comment]
I would suggest:

    Dim A  = GetList(of Integer)
    A.AddRange({5, 6, 7, 8})

Generic are the way to go.  Arrays should only be for when you really care about performance, and I doubt that occurs with ReDim very much.

**Comment by VBAndCs** [comment]
Redim is an important part of the language. It acually creates a new array, then uses the Array.Copy to move the old items to it, which by the way what lists do when exceeds its initial capacity.
Redim shouldn't be used insid a loop, but it can be used to combine two arrays at a single step. 
This shouldn't be a debat about using Redim or not. It is a tool, and each programmer can decide how and when to use it.

**Comment by rskar-git** [comment]
@VBAndCs
> It is a tool, and each programmer can decide how and when to use it.

Yep, and most programmers have settled on `List(Of T)` for most needs. Regularly repeated use of `ReDim Preserve` in a program's execution flow may indicate where `List(Of T)` is actually the better choice.

But anyway, the sorts of things you are asking for can already be achieved within VB today with a set of convenience functions. For example:

    <Extension>
    Sub Append(Of T)(ByRef A As T(), X As IEnumerable(Of T))
        With DirectCast(A, IEnumerable(Of T))
            A = .Concat(X).ToArray()
        End With
    End Sub

`ReDim Preserve A() From {5, 6, 7, 8}` could then be done like this:

    A.Append({5, 6, 7, 8})

The shortcut idea, e.g. `ReDim [Preserve] A(-2)`, clashes with current usage: `ReDim [Preserve] A(-1)` currently means to reduce the array to a length of 0. That makes it a non-starter. If you need this sort of thing:

    <Extension>
    Sub Resize(Of T)(ByRef A As T(), Length As Integer)
        If Length = 0 Then
            ReDim A(-1)
        ElseIf Length < 0 Then
            Dim L = A.Length + Length
            If L = 0 Then
                ReDim A(-1)
            ElseIf L < 0 Then
                Throw New IndexOutOfRangeException()
            Else
                ReDim Preserve A(L - 1)
            End If
        Else
            ReDim Preserve A(Length - 1)
        End If
    End Sub

`ReDim [Preserve] A(-2)` is then realized as:

    A.Resize(-2)

`ReDim Preserve A(10) From {5, 6, 7, 8}` is a very quirky use-case. You may need to show me how often that sort of thing comes up. But from the way you described it:

    A.Append({5, 6, 7, 8})
    A.Resize(11)
