### ISSUE TITLE
Proposal: use Expand keyword to expand lists as ParamArray values

### ISSUE THREAD

**Issue by VBAndCs** [dotnet/vblang#415]
We can send an array to the paramArray, or send individual elements
but I faced a situation where I need to send a value1 and a list then a value to the paramArray!
This made me write a block of code to crate a new array that contains v1, values of the list and v2 then send this array to the function!
Another solution is to add a new overload to manage this situation, but it may require writing many variations with nearly exact code!

I think it will be helpful if we can do it directly like this:
`Foo(v1, Expand lst, v2)`

the `Expand` keyword (or any other suitable one) tells vb that call the overload with ParamsArray if exists (or it its an error). The suitable overloads are:
`Foo(v1 as integer, ParamArray lst)`
and:
`Foo(ParamArray lst)`

so, the overload resolution picks up the suitable one, and create the param array.

**Comment by ericmutta** [comment]
> This made me write a block of code to crate a new array that contains v1, values of the list and v2 then send this array to the function!

You can do this quite easily with a single expression like this:

```vb
Foo({v1}.Union(lst).Union({v2}).ToArray())
```

...which will remove duplicates as per the [Enumerable.Union](https://docs.microsoft.com/en-us/dotnet/api/system.linq.enumerable.union?view=netframework-4.7.2) behaviour. If you want duplicates you can just do:

```vb
Foo({v1}.Concat(lst).Concat({v2}).ToArray())
```

...which works as per the [Enumerable.Concat](https://docs.microsoft.com/en-us/dotnet/api/system.linq.enumerable.concat?view=netframework-4.7.2) behaviour.

**Comment by VBAndCs** [comment]
True but you create one or two new lists then copy it to an array. This is an over kill. In my case, I created a new overload becuase its faster and the code of the method is a few lines. If this was not the case, I would need more steps to call the original overload on some parts of the code.
There is a proposal to allow params lisr in c#. It will be nice but also should consider this case. I hope it is done in vb too.

**Comment by pricerc** [comment]
I'd be curious to see a more real-world example of what problem you're trying to solve, because I don't see how this is a common scenario.

Even if the language implemented something resembling your proposal, underneath, it is most likely just going to implement @ericmutta 's Concat-based solution; anything more sophisticated is probably more than I'd want the compiler to do.

**Comment by CyrusNajmabadi** [comment]
Closing this out as this seems extremely niche and it's trivial to just suppor the behavior you want with linq today.

**Comment by zspitz** [comment]
As a workaround you could use a library like [OneOf](https://github.com/mcintyre321/OneOf)
```vb.net
Function Foo(ParamArray Args As OneOf(Integer, IEnumerable(Of Integer)))
    ' Use the OneOf Match or Switch methods to handle both possibilities
End Function
```
Or if VB.NET ever gets [composable types](#47) you could use that.
