### ISSUE TITLE
Porting C# dll to VB.NET in .NET Core 3 preview issues

### ISSUE THREAD

**Issue by rrvenki** [dotnet/vblang#417]
I took a GitHub source which is in C#. This is source of a DLL to access the webcam. The "Analyze Project Portability" option in VS2019 gives below report.

Submission Id | 63fad1ea-894b-4730-a4ec-32d691b877aa
Targets | .NET Core + Platform Extensions,.NET   Core,.NET Framework,.NET Standard + Platform Extensions

.NET Core +   Platform Extensions = 73.6
.NET Core = 100
.NET Framework = 100
.NET   Standard + Platform Extensions = 73.6

API Catalog last updated on: Tuesday, March 5, 2019
See   'http://go.microsoft.com/fwlink/?LinkId=397652' to learn how to read this table

Based on this report, I planned to migrate the C# code which is currently targeting .NET Framework 3.5 into VB.NET code targeting .NET Core 3 [3.0.100-preview3-010431].  Issues I face are below.

1. Error in "Inherits DependencyObject" as this could not be inherited from System.Windows. This compiles fine in C#.
2. InteropBitmap prompts to reference PresentationCore.dll.  If I click "Add reference to PresentationCore.dll" menuitem, it adds reference to ".NET 3.0" version of PresentationCore.dll.  Do we have an equivalent of PresentationCore.dll in .NET Core 3?
3. Microsoft.NETCore.Platforms reference says "<The system cannot find the reference specified>".
4. Microsoft.WindowsDesktop.App reference says "<The system cannot find the reference specified>".
5. Threading is not a member of System.Windows -> Error.

and few more errors. Do we have any guidance for these type of migrations?

**Comment by Nukepayload2** [comment]
Can you share your vbproj file?
I've ported a simple VB.NET WPF app to .NET Core 3.0 preview 1 last year. Maybe it's helpful. https://github.com/Nukepayload2/NetCore3Pre1VBWinExe

**Comment by rrvenki** [comment]
Hi @Nukepayload2, I went through your code and looks good. In my case I took the code from GitHub by name AvCapWpf. It has several  comimports. Currently I've 14 errors mainly due to unavailability of PresentationCore.dll not found in .NET Core 3 Preview 3 (Or I don't know).  In the below code, 

```
Public Class CapPlayer
    Inherits Image
    Implements IDisposable

End Class
```
Error is "Type 'Image' is not defined",
Type 'DependencyObject' is not defined,
Error	BC30451	'Application' is not declared. It may be inaccessible due to its protection level.
and few more.

Below is the Project file
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>CamCapture</RootNamespace>
    <OutputType>Library</OutputType>
    <TargetFramework>netcoreapp3.0</TargetFramework>
  </PropertyGroup>
</Project>

**Comment by Nukepayload2** [comment]
@rrvenki 
Your vbproj file needs attention. The value of `<Project>.@Sdk` attribute should be "Microsoft.NET.Sdk.WindowsDesktop". And you need to put `<UseWpf>true</UseWpf>` in one of the `<Project>...<PropertyGroup>` elements. 

```xml
<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">
  <PropertyGroup>
    <RootNamespace>CamCapture</RootNamespace>
    <OutputType>Library</OutputType>
    <TargetFramework>netcoreapp3.0</TargetFramework>
    <UseWpf>true</UseWpf>
  </PropertyGroup>
</Project>
```
