### ISSUE TITLE
[Proposal] Fix variable declaration

### ISSUE THREAD

**Issue by hartmair** [dotnet/vblang#450]
Add a redundant keyword for [`Dim`](https://docs.microsoft.com/en-us/dotnet/visual-basic/language-reference/statements/dim-statement)

## Details
Before:
```vb
Dim x = 5
```

After:
```vb
Let x = 5
```
## Why?
VB.NET is all about writing code that is intuitive, easy to read and understand. Nobody would guess the keyword `Dim` for declaring variables in English, see [What does DIM stand for in Visual Basic and BASIC?](https://stackoverflow.com/q/1033507). 
`Let` is concise, can be read as English sentence, and is commonly used in mathematics. 
`Declare` is even better regarding intuitivity, however, it is not concise.

**Comment by zspitz** [comment]
There's already a previous proposal to [make `Dim` completely optional](https://github.com/dotnet/vblang/issues/177).

The LDT is trying to get away from explicit variable declarations such as `Dim`.

**Comment by hartmair** [comment]
I am not yet completely convinced it is a good idea to not distinguish variable declarations and variable assignments as in #177 
```vb
Let x = 5
' ... many lines of code
x = 7
```
vs.
```vb
x = 5
' ... many lines of code
x = 7
```
However, let's close this issue in favor of #177.
