### ISSUE TITLE
Optimize comparison operators when comparing unsigned integers to 0

### ISSUE THREAD

**Issue by Nukepayload2** [dotnet/vblang#463]
I'm dealing with a performance problem in a VB class library. The following code slows down the whole function:
```vb
Dim fraction As ULong = m2 And mask
If fraction <> 0 Then
    Return False
End If
```
Because `fraction <> 0` is actually `Decimal.Compare(New Decimal(fraction), Decimal.Zero) <> 0`.
There's no warning or code fix for this performance issue even `Option Strict` is `On`.
I have to replace all occurrences of `0` with `Nothing` to solve this performance problem.

__Suggested optimizations__
- Treat `0` as `0UL` when comparing `0` with `ULong` 
- Treat `0` as `0UI` when comparing `0` with `UInteger` 
- Provide new compiler warnings for implicitly promoting numeric types (Disable these warnings by default to avoid breaking existing codes).

**Comment by hartmair** [comment]
I've got a very similar problem with the `Byte` data type. I tried this for all number types:
- Implicitely treat `0` as `CByte(0)` when comparing `0` with `Byte` (uses Integer)
- Implicitely treat `0` as `CSByte(0)` when comparing `0` with `SByte` (uses Integer)
- Implicitely treat `0` as `0US` when comparing `0` with `UShort` (uses Integer)
- Implicitely treat `0` as `0S` when comparing `0` with `Short` (uses Integer)
- Implicitely treat `0` as `0UI` when comparing `0` with `UInteger` (uses Decimal)
- ~Implicitely treat `0` as `0I` when comparing `0` with `Integer`~ (uses Integer)
- Implicitely treat `0` as `0UL` when comparing `0` with `ULong` (uses Decimal)
- ~Implicitely treat `0` as `0L` when comparing `0` with `Long`~ (uses Long)
- ~Implicitely treat `0` as `0D` when comparing `0` with `Decimal`~ (uses Decimal)
- ~Implicitely treat `0` as `0F` when comparing `0` with `Single`~ (uses Single)
- ~Implicitely treat `0` as `0R` when comparing `0` with `Double`~ (uses Double)

Note that the same thing applies also to for loops:
```vb
Dim n As UInteger = 20
' This doesn't even compile, because there is no common type between Integer and UInteger
For i = 1 To n
  ...
Next
```

**Comment by AdamSpeight2008** [comment]
Why not write an analyzer to add the suffix for you?

**Comment by rskar-git** [comment]
@Nukepayload2

> I have to replace all occurrences of 0 with Nothing to solve this performance problem.

Wouldn't it make better sense to use decorated literals instead e.g. `0UL`? Or `Const` where one must, e.g. `Const ZedByte As Byte = 0` and `Const ZedSByte As SByte = 0`?

`Nothing` carries the (perhaps small) risk of getting something unexpected - it is, after all, the default value of some target data type, which might not be a straightforward thing where overloads and generics get involved. I'm thinking that one might get too stuck on "Nothing means exactly the zero I need" when reading code.

**Comment by rskar-git** [comment]
That does seem like a strange oversight - one would think that any built-in integral literal or `Const` for zero (and perhaps some range of values too, at least 0 to +127) could be consistently recognized by the compiler and optimized accordingly.

I tried similar in C#, and it got the ulong-ulong `!=` overload:

    ulong fraction = 123;
    if(fraction!=0)
    {
        return false;
    }
    return true;

Side note: Option Strict, via the "Implicit conversion" warning configuration, responds to only implicit conversions of the Narrowing kind. Widening conversions are considered as safe (since they signal a "contract" which promises no surprises such as run-time errors or inappropriate mappings).

Hence, VB went with `Decimal` since it can reliably represent anything from Integer.MinValue through ULong.MaxValue (making that a Widening conversion). So VB allows this, whereas C# does not without explicit casting:

	Dim wholepart As Long = 123
	If fraction <> wholepart Then  ' Uses Decimal overload
		Return False
	End If

The good news here is that this can be addressed in VB as it is today - one can work-around the suboptimal choice the compiler made. The bad news is that one has to scrutinize every expression, with assistance from the IDE (e.g. hovering the mouse cursor over the `<>` does indicate the chosen overload).

**Comment by rskar-git** [comment]
> That does seem like a strange oversight - one would think that any built-in integral literal or Const for zero...

Yep, I said the above, but with some further thought I can see that this sort of thing can get very tricky. I wonder if the scope of this issue should be restricted to `=` and `<>` (and maybe a few more). Sometimes you want to force the use of a particular overload or generic, so we need to be very careful about what we wish for.

I wonder if an analyzer making info-warnings should be the first step.

**Comment by AdamSpeight2008** [comment]
I am working on a [NumberSuffix Analyser And CodeFix](https://github.com/AdamSpeight2008/NumberSuffix_AnalyserAndCodeFix). _Prototype code._

**Comment by VBAndCs** [comment]
There are more issues related to ULong even in C#, See this topics and the discussion: 
https://github.com/dotnet/csharplang/issues/2322

**Comment by AdamSpeight2008** [comment]
@VBAndCs How does it affect vb.net?

**Comment by CyrusNajmabadi** [comment]
Closing this out due to this:

> Provide new compiler warnings for implicitly promoting numeric types

New compiler warnings can be provided by writing an analyzer. Indeed, these are the exact sorts of cases where analyzers are intended to be used.

**Comment by VBAndCs** [comment]
If there is a way, so, why closing?
If the team will not do it, such issues should be marked as `Left for community` or something a like, so that some contributes can look at it someday and implement it.
I advice no to rush closing issues here, as it it is a burden needs to be thrown away.

**Comment by CyrusNajmabadi** [comment]
> If there is a way, so, why closing?

Because it's not part of vblang. You could write this analyzer yourself. So we dunt need the issue here tracking it. 

> I advise no to rush closing issues here, 

There's no rush. This issue is 18 months old. It just doesn't fit in this repo. Thanks.
