### ISSUE TITLE
[Proposal] Auto-constructed Properties

### ISSUE THREAD

**Issue by VBAndCs** [dotnet/vblang#474]
I suggest to use a Constructed attribute in C# and VB.NET to auto initialize some properties and fields through the constructor. This will save a lot of coding in cases where there is no need to process the constructor params.. 
This will be helpful in many cases, such as dependency injection through constructors used a lot in controllers and PageModels in ASP.NET Core.

Example:
```VB.NET  
Class MyClass
        <Constructed>Public Property X As Integer
        <Constructed>Public Property Y As Integer
        <Constructed>Public Property Z As Integer

        Public Sub New(Msg As String)
              ' do something
        End Sub

End Class
```

Roslyn can generate this code:
```VB.NET
Class MyClass
        Public Property X As Integer
        Public Property Y As Integer
        Public Property Z As Integer

        Public Sub New(x As Integer, y As Integer, z As Integer)
              Me.X = x
              Me.Y = y
              Me.Z = z
        End Sub

        Public Sub New(x As Integer, y As Integer, z As Integer, Msg As String)
              Me.X = x
              Me.Y = y
              Me.Z = z
              ' do something
        End Sub

End Class
```

If we want a constructor that doesn't initialize the properties:
```VB.NET  
Class MyClass
        <Constructed>Public Property X As Integer
        <Constructed>Public Property Y As Integer
        <Constructed>Public Property Z As Integer

        Public Sub New()
              ' do something
        End Sub

        <NonConstructing>Public Sub New(Msg As String)
              ' do something
        End Sub

End Class
```

Then Roslyn generates this code:
```VB.NET
Class MyClass
        Public Property X As Integer
        Public Property Y As Integer
        Public Property Z As Integer

        Public Sub New(x As Integer, y As Integer, z As Integer)
              Me.X = x
              Me.Y = y
              Me.Z = z
              ' do something
        End Sub

        Public Sub New(Msg As String)
              ' do something
        End Sub

End Class
```

**Comment by VBAndCs** [comment]
@gafter
I proposed this as a Roslyn feature, because it can be done without any change in compilers. 
And why did you move it to VB repo, while I stated it is for both C# and VB.NET? Your policy says such feature requests for both languages goes to C# repo. Now I need to make another copy for C#! I think that Roslyn is the most suitable place.

**Comment by VBAndCs** [comment]
It will be better to combine our ideas like this:
```VB.NET
Class MyClass (Private X As Integer = 0, ReadOnly Y As Integer = 1, Protected Z As Integer= 2)
    <NonConstructed> Public Sub New(Msg As String)
       'do something
    End Sub
End Class
```

This will generate:
```VB.NET
Class MyClass 
  Private Property X As Integer
  public ReadOnly Property Y As Integer
  Protected Property Z As Integer

    Public Sub New (x As Integr, y As Integer, z As Integer)
       Me.X = x;
       Me.Y = y;
       Me.Z = z;
    End Sub

   public Sub New(Msg As String)
       Me.X = 0;
       Me.Y = 1;
       Me.Z = 2;
       ' do something
    End Sub
End Class
```

**Comment by gafter** [comment]
> I proposed this as a Roslyn feature, because it can be done without any change in compilers

The Roslyn repo is for the compilers, so if it can be done without changing the compilers then that is probably the wrong place for it.

If you intend this to be a feature proposal for both languages, then it requires two proposals.  We can do neither, both, or just one.

**Comment by InteXX** [comment]
@VBAndCs 

Hi, just making sure you're OK. We haven't heard from you in a while, hope all is well.

**Comment by CyrusNajmabadi** [comment]
I think this would be possible with SourceGenerators.  You can make a source generator that recognizes this attribute and spits out a new onstructor with the logic you want in it.

**Comment by zspitz** [comment]
Can I use source generators with VB today?

**Comment by CyrusNajmabadi** [comment]
@zspitz  See: https://github.com/dotnet/roslyn/pull/49139
