### ISSUE TITLE
IDebugProperty3 is ambiguous in the namespace 'Microsoft.VisualStudio.Debugger.Interop'

### ISSUE THREAD

**Issue by rrvenki** [dotnet/vblang#480]
While converting SqliteVisualizer CS sample to VB I encountered 'IDebugProperty3' is ambiguous in the namespace 'Microsoft.VisualStudio.Debugger.Interop'. The heading of the popup says "Interface Microsoft.VisualStudio.Debugger.Interop.IDebugProperty3'.
Question 1: Can we pass an interface as parameter to a function in VB like this in CS?
Question 2: If it is ambiguous where else it (IDebugProperty3) is found?  If duplicates of this interface is available in different DLLs can visual studio directly give us the list of referenced DLLs having the implementation of the particular function/interface? -> probably a good idea for another visualizer.

**Comment by CyrusNajmabadi** [comment]
Closing out as this is unrelated to the vb language. You could consider filing requests for this over at dotnet/roslyn.  Please provide a full repro though.
