### ISSUE TITLE
MyApplicationCodeGenerator for Core doesn't work

### ISSUE THREAD

**Issue by paul1956** [dotnet/vblang#485]
I am opening this here because I don't know where else to report it. If you port an application from Framework to Core you can't bring across Application.Designer.vb and you can't regenerate it using MyApplicationCodeGenerator because the resulting file has many errors.

Before VB has all the necessary support it would nice to generate something basic that allowed VB programs to run and comment out the broken features and pass the feature(s) that work.

It should as least generate
```
    <STAThread>
    Public Shared Sub Main()
        Application.SetCompatibleTextRenderingDefault(False)
        ' the next 4 lines would work using the settings from Application.myapp
        Application.EnableVisualStyles()
        Dim f As New Form1()
        Application.Run(f)
        f.Dispose()
    End Sub
```

**Comment by AdamSpeight2008** [comment]
@paul1956 has this fixed?

**Comment by paul1956** [comment]
- In Core5 yes which is the first time WinForms is supported for VB anyway.
