### ISSUE TITLE
Code gallery in VB - Compilation issue

### ISSUE THREAD

**Issue by rrvenki** [dotnet/vblang#486]
I was building few projects (WPF) which are in C# into VB using .NET Core 3.1. I'm using VS2019 16.5.0 Preview 1.
Initially the app worked with .NET Core 3.0.  Once I target 3.1, the code compiles to zero error but while executing (F5) it says there are build errors and does not run (but errors windows shows 0 errors). Now even if I retarget to Core 3.0 it continues to give same error. As per
[https://github.com/dotnet/wpf/issues/1734](https://github.com/dotnet/wpf/issues/1734)
[https://github.com/dotnet/winforms/issues/1698](https://github.com/dotnet/winforms/issues/1698)
should we wait until preview of .NET 5 and related templates are released to do any VB development at all?
@KathleenDollard please advice.  Do we have chance to work using alpha/beta versions of .NET 5.0? (For VB samples building sake) or there is any plan to support in existing .NET Core 3.1.

**Comment by zspitz** [comment]
Is there anything in the Output pane?

If you delete the `bin` and `obj` folders and rebuild, what happens?

**Comment by paul1956** [comment]
I have ported a few samples and with Preview 1 and Core 3.1, it is easier. If you created a Main remove it and make sure you have the line below in project file where RootNamespace and Form1 match your application.
```xml
     <StartupObject>RootNamespace.Form1</StartupObject>
```
You can look at https://github.com/paul1956/samples/tree/Sudoku_VB for a completely working port waiting to merge. There are significant changes in the readme.md file for the new samples vs reference samples, start with the one in Sudoku and change the text/values. The reference source uses a lot of HTML and the new format has none plus there is some "magic" in the header that is needed, it took a lot of commits to get it correct. Once Sudoku is merged I will commit Conway's Game of Life. Also you will need a local .editorconfig for VB until the Samples Repo updates theirs right now it only has code styles for C# but the reviewers want VB to use a dotnet style. I created one, used it and then deleted it before doing the commit.

**Comment by rrvenki** [comment]
Got it compiled and working now. How?
1. As per @zspitz advice, there was a warning stating that a property in another class is not accessible from MainWindow even though the class is already public and the property is also public string.
2. I deleted the Bin and Obj folders and "Rebuild" the solution. It compiled with same error again but the hourglass was still rotating. After a while (5-15) seconds the warning just vanished and it started working.
If I keep the PC not connected to internet, this auto correction can happen?
