### ISSUE TITLE
Support editing an object's member when it's retrieved via a writable property

### ISSUE THREAD

**Issue by dovisutu** [dotnet/vblang#487]
I've first encountered this when I'm writing a Huffman Encoding method for pricticing my coding. Some of my porposal code is like this: (simplified)
```vb
Class Node
    Public Property value As Integer
    Public Parent As Node
End Class
Module T
    Function Foo(input As String) As Node 'Root node
        Dim rawNodes As New Dictionary(Of Char, Node)
        For Each char In input
            Try
                ' ... (adding new letter)
            Catch(ex As Exception)
                rawNodes(char).value += 1 'Error Occurs here
            End Try
        ' ...
        Next
    End Function
End Module
```
Then error is triggered due to editing a readonly object (returned by getter). It's frustrating because I have to do a workaround like this:
```vb
Class Node
    ' ...
    Public Sub Add()
        Me.value += 1
    End Sub
End Class
Module T
   Function Foo(input As String) As Node
        '...
        rawNodes(char).Add()
    End Function
End Module
```

**Suggestion:**
make the privious self-adding(aka `rawNodes(char).value += 1`) legal (at least for native classes like `List(Of T)`,`Dictionary(Of T)`,...)

*Is it for `vblang` or `runtime` repository?*

**Comment by hartmair** [comment]
Which exception do you encounter? I don't get any with this code:
```vb
Sub Main()
    Dim input = "Hello, World!"
    Dim rawNodes As New Dictionary(Of Char, Node)
    For Each c In input
        Try
            rawNodes.Add(c, New Node())
        Catch ex As Exception
            rawNodes(c).Value += 1 'No error occurs here
        End Try
    Next
End Sub
```

Btw., check out the Dictionary `Try...` methods which are way faster than exceptions.
```vb
Sub Main()
    Dim input = "Hello, World!"
    Dim rawNodes As New Dictionary(Of Char, Node)
    For Each c In input
        Dim n As Node
        If rawNodes.TryGetValue(c, n) Then
            n.Value += 1
        Else
            rawNodes.Add(c, New Node())
        End If
    Next
End Sub
```

**Comment by dovisutu** [comment]
Sorry about that because I previously did that on an older version so it (seems) not work. Closing.
And thanks for the advice on using `TryGetValue`.

**Comment by VBAndCs** [comment]
It can be solved by this [proposal](https://github.com/dotnet/vblang/issues/513)
```
rawNodes(char).value +<= 1 
```
