### ISSUE TITLE
Proposal: An Extensible VB.NET Compiler

### ISSUE THREAD

**Issue by VBAndCs** [dotnet/vblang#498]
Extensible VB.NET
Can we make VB.NET compiler extensible?
MS frozen VB.NET , and I expect that many forks an new implementations will emerge, and it can be a mess.
It will be better if we have the MSVB .NET  as a black box, and add extensions to it (an xml syntax file and a parser dll that lowers the new syntax to the standard syntax). More than one extensions can be added to the folder. This will allow is to choose the extensions we prefer.
This will keep us synchronous to MS VB.NET if it make any sudden change to the compiler, and gather all the efforts in extension gallery, so all efforts build up.

**Comment by CyrusNajmabadi** [comment]
Clsoing out.  Requests about the VB compiler should go at dotnet/roslyn.  Thanks!

**Comment by zspitz** [comment]
@CyrusNajmabadi Are you saying that introducing extensibility points into the compiler isn't part of the language? Wouldn't such an extensibility model require some additional VB.NET language syntax to use?

**Comment by CyrusNajmabadi** [comment]
> @CyrusNajmabadi Are you saying that introducing extensibility points into the compiler isn't part of the language?

Correct.  Roslyn, for example, has several extensibility points for both C# and Vb and it doesn't require language support for any of it.
