### ISSUE TITLE
[Bug] Strange Overload Resolution error

### ISSUE THREAD

**Issue by VBAndCs** [dotnet/vblang#506]
This code:

```vb.net
builder.OwnsOne(
   Function(o) o.ShipToAddress,
   Sub(a)
      a.WithOwner()
      a.Property(Function(a) a.ZipCode).HasMaxLength(18).IsRequired()
      a.Property(Function(a) a.Street).HasMaxLength(180).IsRequired()
      a.Property(Function(a) a.State).HasMaxLength(60)
      a.Property(Function(a) a.Country).HasMaxLength(90).IsRequired()
      a.Property(Function(a) a.City).HasMaxLength(100).IsRequired()
   End Sub
```

gives the error:
> Overload resolution failed because no accessible 'OwnsOne' can be called with these arguments:    'Public Overridable Overloads Function OwnsOne(Of Address)(navigationExpression As Expression(Of Func(Of Order, Address)), buildAction As Action(Of OwnedNavigationBuilder(Of Order, Address))) As EntityTypeBuilder(Of Order)': Lambda parameter 'a' hides a variable in an enclosing block, a previously defined range variable, or an implicitly declared variable in a query expression.    'Public Overridable Overloads Function OwnsOne(Of Address)(navigationExpression As Expression(Of Func(Of Order, Address)), buildAction As Action(Of OwnedNavigationBuilder(Of Order, Address))) As EntityTypeBuilder(Of Order)': Lambda parameter 'a' hides a variable in an enclosing block, a previously defined range variable, or an implicitly declared variable in a query expression.    'Public Overridable Overloads Function OwnsOne(Of Address)(navigationExpression As Expression(Of Func(Of Order, Address)), buildAction As Action(Of OwnedNavigationBuilder(Of Order, Address))) As EntityTypeBuilder(Of Order)': Lambda parameter 'a' hides a variable in an enclosing block, a previously defined range variable, or an implicitly declared variable in a query expression.    'Public Overridable Overloads Function OwnsOne(Of Address)(navigationExpression As Expression(Of Func(Of Order, Address)), buildAction As Action(Of OwnedNavigationBuilder(Of Order, Address))) As EntityTypeBuilder(Of Order)': Lambda parameter 'a' hides a variable in an enclosing block, a previously defined range variable, or an implicitly declared variable in a query expression.    'Public Overridable Overloads Function OwnsOne(Of Address)(navigationExpression As Expression(Of Func(Of Order, Address)), buildAction As Action(Of OwnedNavigationBuilder(Of Order, Address))) As EntityTypeBuilder(Of Order)': Lambda parameter 'a' hides a variable in an enclosing block, a previously defined range variable, or an implicitly declared variable in a query expression.    'Public Overridable Overloads Function OwnsOne(ownedTypeName As String, navigationName As String) As OwnedNavigationBuilder': Lambda expression cannot be converted to 'String' because 'String' is not a delegate type.    'Public Overridable Overloads Function OwnsOne(ownedTypeName As String, navigationName As String) As OwnedNavigationBuilder': Lambda expression cannot be converted to 'String' because 'String' is not a delegate type.    'Public Overridable Overloads Function OwnsOne(ownedType As Type, navigationName As String) As OwnedNavigationBuilder': Lambda expression cannot be converted to 'Type' because 'Type' is not a delegate type.    'Public Overridable Overloads Function OwnsOne(ownedType As Type, navigationName As String) As OwnedNavigationBuilder': Lambda expression cannot be converted to 'String' because 'String' is not a delegate type.

the strange is that the error goes away when I remove the all the lines from the sub except the first.. This works:

```vb.net
            builder.OwnsOne(
                Function(o) o.ShipToAddress,
                Sub(a)
                    a.WithOwner()
                End Sub
```

I also tried:
```
builder.OwnsOne(
  Function(o) o.ShipToAddress,
  Sub(a)
     a.Property(Function(a) a.ZipCode).HasMaxLength(18).IsRequired()
  End Sub
```

But it gave the overload resolution error. For some reason, these long statements make VB think that there is a third param so the resolution failed!
Note that this code works fine in C#.

 Note:
This gives the same error:
```
     Dim action = Sub(a)
                             a.WithOwner()
                         End Sub

            builder.OwnsOne(
                Function(o) o.ShipToAddress,
                action
            )
```

Note:
I discovered the source of the problem. look here https://github.com/dotnet/vblang/issues/506#issuecomment-602138831

**Comment by VBAndCs** [comment]
Note:
This gives the same error:
```VB.NET
            Dim action = Sub(a)
                             a.WithOwner()
                         End Sub

            builder.OwnsOne(
                Function(o) o.ShipToAddress,
                action
            )
```

**Comment by VBAndCs** [comment]
Seems to need an explicit conversion. This works:
```
            Dim action As Action(Of OwnedNavigationBuilder(Of Order, Address)) =
                Sub(x)
                    x.WithOwner()
                    x.Property(Function(a) a.ZipCode).HasMaxLength(18).IsRequired()
                    x.Property(Function(a) a.Street).HasMaxLength(180).IsRequired()
                    x.Property(Function(a) a.State).HasMaxLength(60)
                    x.Property(Function(a) a.Country).HasMaxLength(90).IsRequired()
                    x.Property(Function(a) a.City).HasMaxLength(100).IsRequired()
                End Sub

            builder.OwnsOne(
                Function(o) o.ShipToAddress,
                action
            )
```

**Comment by VBAndCs** [comment]
And the reason that implicit conversion didn't work in the first code, is because of using the same variable name `a` in the outer sub and inner functions, which VB thinks it will hide each other (didn't happen in C#), so the bug here is the false error message!.. I got the right err message when I assigned the sub to a variable with explicit type. When I used type inference, I got no message and the error happens! so I used `Sub(x)` instead of `Sub(a)` and it worked.
So, this code works too:
```
                Function(o) o.ShipToAddress,
                                Sub(x)
                                    x.WithOwner()
                                    x.Property(Function(a) a.ZipCode).HasMaxLength(18).IsRequired()
                                    x.Property(Function(a) a.Street).HasMaxLength(180).IsRequired()
                                    x.Property(Function(a) a.State).HasMaxLength(60)
                                    x.Property(Function(a) a.Country).HasMaxLength(90).IsRequired()
                                    x.Property(Function(a) a.City).HasMaxLength(100).IsRequired()
                                End Sub
            )
```

Please fix the error message. I wasted too long time to discover the source of this error!

**Comment by RevensofT** [comment]
Did you use web translate C# code to VB then copy and paste ? It work only basic and standard code, many unique feature from C# can't be translate to VB directly by reverse back from IL code; if you write a code normally VS will stop you even before you finish that line and an error message will be very clear and easy to understand ... much more then an error from dynamic_method, it just tell you your code is wrong but never tell you what or where is it an error happen.

**Comment by VBAndCs** [comment]
Yes, I used @paul1956 [converter](https://github.com/paul1956/CSharpToVB).
Put I copy and past shouldn't be an issue. Besides, why does C# accept the names but VB doesn't?

**Comment by pricerc** [comment]
> Besides, why does C# accept the names but VB doesn't?

Because they are different languages with different variable scoping and lambda parameter naming rules?

You didn't post the original C#, but if C# lets you use the exact same variable name in the exact same context, then I think C# is at fault here, not VB, because *to a human*, it would not be clear to which 'a' an 'a.Property' refers.

**Comment by RevensofT** [comment]
VB can pass outside variant into Lamda method directly, I'm not sure C# can do it too or not but in VB if you look at my code below if I use `Data As Int32` VB compiler going to be confuse which `Data` I ask for.

```vb
        Dim Data = {9, 5, 7, 10, 4, 8, 6}

        Dim Find_7 = (Function(Target As Int32)
                          For i = 0 To Data.Length
                              If Data(i) = Target Then Return i
                          Next
                          Return -1
                      End Function)(7)
```

**Comment by tverweij** [comment]
@VBAndCs : Can you post a piece of code that I can in VB to test?

**Comment by VBAndCs** [comment]
@pricerc
[This is the original C# code](https://github.com/dotnet-architecture/eShopOnWeb/blob/master/src/Infrastructure/Data/Config/OrderConfiguration.cs)

@tverweij
I am converting [eShopOnWeb](https://github.com/dotnet-architecture/eShopOnWeb) to VB.NET as a full working ASP.NET Core 3.1 with pages and views designed by [Vazor](https://github.com/VBAndCs/Vazor) and [ZML](https://github.com/VBAndCs/ZML). I already have [a working 2.2 ver](https://github.com/VBAndCs/Vazor-DotNetCore2/tree/master/eShopOnWeb.vazor) but I left the ApplicationCore and Infrastructure projects in C# because I was focusing on the Web project. I got the ver 3.1 ver working yesterday, but decided to convert the ApplicationCore and Infrastructure projects to VB as well. I finally built them, but there is an elusive exception I am chasing now, resulting from differences between the two languages or broken EF Core convention. As soon as I fix it and have the app up and running, I will publish the repo and notify you. But you can simulate the issue by creating a Foo method with two overloads, one of them accepts an Action(of Integer) argument and test 
```
Call Foo(Sub(a)
           Dim x = Function(a) a + 1
       End Sub
```

**Comment by pricerc** [comment]
> 
> @pricerc
> [This is the original C# code](https://github.com/dotnet-architecture/eShopOnWeb/blob/master/src/Infrastructure/Data/Config/OrderConfiguration.cs)
> 

I go with my previous comment: I think VB does this correctly, and C# has it wrong. 

C# is allowing you to re-use an identifier in an inner scope that presumably overrides the outer scope. 

I suppose the person coding this way sees 'a' as just a 'throwaway' variable inside a lambda declaration. But it is not hard to use a different 'throwaway' variable for the two layers of scope, so a casual glance at the code isn't ambiguous.

But I still think that this is at best a 'code smell' - it's a potential maintenance problem; even if it's technically legal, there should be a StyleCop warning against it.

Personally, even for a 'throwaway' variable, I will always give it a meaningful name, so that when I read the code again in a year, I know what I'm looking at.

**Comment by pricerc** [comment]
A thought experiment.
Given:
```
Sub SubA(a)
      Dim x = Function(a) a + 1
End Sub
```

If you imagine a flavour of VB can do 'named local' functions, you could write this as:

```VB
Sub SubA(a As Int32)
     Function FunctionA(a As Int32)
        Return a + 1 
     End Function
   
     Dim x = Inner(a)
End Sub
```

Now imagine a longer version
```VB
Sub SubA(a As Int32)
   '
   '  10 lines of other code
   '
     Function FunctionA(a As Int32)
       '
       ' 20 lines of other code
      '
        Return a + 1 
     End Function
   
     Dim x = FunctionA(a)
End Sub
```

would anyone really choose 'a' as the parameter for both 'SubA' and 'FunctionA' and not expect any confusion about what gets returned by Return a + 1?

**Comment by VBAndCs** [comment]
@pricerc
You are right. VB nailed it, but still misleads us by the wrong error message, which I wish to be fixed.

**Comment by pricerc** [comment]
> Lambda parameter 'a' hides a variable in an enclosing block, a previously defined range variable, or an implicitly declared variable in a query expression.

Appears several times in the errors in your original post.

What more do you want?

**Comment by VBAndCs** [comment]
> Appears several times in the errors in your original post.

No, it didn't appear until I changes the code and assigned the lambda to a non-interred variable, which is not the usual thing to do when writing code, because it is a two steps back in the language evolution.

**Comment by pricerc** [comment]
> > Appears several times in the errors in your original post.
> 
> No, it didn't appear until I changes the code and assigned the lambda to a non-interred variable, which is not the usual thing to do when writing code, because it is a two steps back in the language evolution.

? 

Your original Post; the 5 errors highlighted:

> This code:
> 
> ```vbnet
> builder.OwnsOne(
>    Function(o) o.ShipToAddress,
>    Sub(a)
>       a.WithOwner()
>       a.Property(Function(a) a.ZipCode).HasMaxLength(18).IsRequired()
>       a.Property(Function(a) a.Street).HasMaxLength(180).IsRequired()
>       a.Property(Function(a) a.State).HasMaxLength(60)
>       a.Property(Function(a) a.Country).HasMaxLength(90).IsRequired()
>       a.Property(Function(a) a.City).HasMaxLength(100).IsRequired()
>    End Sub
> ```
> 
> gives the error:
> 
> > Overload resolution failed because no accessible 'OwnsOne' can be called with these arguments:    'Public Overridable Overloads Function OwnsOne(Of Address)(navigationExpression As Expression(Of Func(Of Order, Address)), buildAction As Action(Of OwnedNavigationBuilder(Of Order, Address))) As EntityTypeBuilder(Of Order)': **_Lambda parameter 'a' hides a variable in an enclosing block, a previously defined range variable, or an implicitly declared variable in a query expression._**    'Public Overridable Overloads Function OwnsOne(Of Address)(navigationExpression As Expression(Of Func(Of Order, Address)), buildAction As Action(Of OwnedNavigationBuilder(Of Order, Address))) As EntityTypeBuilder(Of Order)': **_Lambda parameter 'a' hides a variable in an enclosing block, a previously defined range variable, or an implicitly declared variable in a query expression._**    'Public Overridable Overloads Function OwnsOne(Of Address)(navigationExpression As Expression(Of Func(Of Order, Address)), buildAction As Action(Of OwnedNavigationBuilder(Of Order, Address))) As EntityTypeBuilder(Of Order)': **_Lambda parameter 'a' hides a variable in an enclosing block, a previously defined range variable, or an implicitly declared variable in a query expression._**    'Public Overridable Overloads Function OwnsOne(Of Address)(navigationExpression As Expression(Of Func(Of Order, Address)), buildAction As Action(Of OwnedNavigationBuilder(Of Order, Address))) As EntityTypeBuilder(Of Order)': **_Lambda parameter 'a' hides a variable in an enclosing block, a previously defined range variable, or an implicitly declared variable in a query expression._**    'Public Overridable Overloads Function OwnsOne(Of Address)(navigationExpression As Expression(Of Func(Of Order, Address)), buildAction As Action(Of OwnedNavigationBuilder(Of Order, Address))) As EntityTypeBuilder(Of Order)': **_Lambda parameter 'a' hides a variable in an enclosing block, a previously defined range variable, or an implicitly declared variable in a query expression._**    'Public Overridable Overloads Function OwnsOne(ownedTypeName As String, navigationName As String) As OwnedNavigationBuilder': Lambda expression cannot be converted to 'String' because 'String' is not a delegate type.    'Public Overridable Overloads Function OwnsOne(ownedTypeName As String, navigationName As String) As OwnedNavigationBuilder': Lambda expression cannot be converted to 'String' because 'String' is not a delegate type.    'Public Overridable Overloads Function OwnsOne(ownedType As Type, navigationName As String) As OwnedNavigationBuilder': Lambda expression cannot be converted to 'Type' because 'Type' is not a delegate type.    'Public Overridable Overloads Function OwnsOne(ownedType As Type, navigationName As String) As OwnedNavigationBuilder': Lambda expression cannot be converted to 'String' because 'String' is not a delegate type.
> 
> the strange is that the error goes away when I remove the all the lines from the sub except the first.. This works:
> 
> ```vbnet
>             builder.OwnsOne(
>                 Function(o) o.ShipToAddress,
>                 Sub(a)
>                     a.WithOwner()
>                 End Sub
> ```
> 
> I also tried:
> 
> ```
> builder.OwnsOne(
>   Function(o) o.ShipToAddress,
>   Sub(a)
>      a.Property(Function(a) a.ZipCode).HasMaxLength(18).IsRequired()
>   End Sub
> ```
> 
> But it gave the overload resolution error. For some reason, these long statements make VB think that there is a third param so the resolution failed!
> Note that this code works fine in C#.
> 
> Note:
> This gives the same error:
> 
> ```
>      Dim action = Sub(a)
>                              a.WithOwner()
>                          End Sub
> 
>             builder.OwnsOne(
>                 Function(o) o.ShipToAddress,
>                 action
>             )
> ```
> 
> Note:
> I discovered the source of the problem. look here [#506 (comment)](https://github.com/dotnet/vblang/issues/506#issuecomment-602138831)

**Comment by zspitz** [comment]
I would theorize that overload resolution is mentioned in the error, is because lambda syntax doesn't have an inherent type -- the same lambda syntax can be used for multiple delegate types.
```vb
Dim action1 As Action(Of String) = Sub(arg) Console.WriteLine(arg)
Dim action2 As Action(Of Random) = Sub(arg) Console.WriteLine(arg)
```
or even for an expression instead of for a delegate.

In order for the compiler to choose an appropriate overload of `OwnsOne`, it has to be able to compile the lambda syntax and resolve its types, which it cannot do because of the error. Some of the overloads don't succeed even before attempting to compile the lambda syntax:

> Lambda expression cannot be converted to 'String' because 'String' is not a delegate type.

**Comment by VBAndCs** [comment]
@pricerc  
Sorry. I never read all the message, as I use large fonts, which make most of the message disappear, and I diddint read it after copying it here!

**Comment by CyrusNajmabadi** [comment]
Closing out due to this statement:

> You are right. VB nailed it, but still misleads us by the wrong error message, which I wish to be fixed.

Requests to improve error messages should go to dotnet/roslyn.  vblang does not choose the error messages.  Those are chosen by the compiler developers and compiler implementation.
