### ISSUE TITLE
Array of arrays initializer issue

### ISSUE THREAD

**Issue by VBAndCs** [dotnet/vblang#518]
This code:
```VB.NET
Dim x As String()() = {
  {"a", "b"},
  {"c", "d"}
}
```

gives the error:
> Value of type 'String(*,*)' cannot be converted to 'String()()' because the array types have different numbers of dimensions.

What does `String(*,*)` mean? and why can't this work in array of arrays but works in normal array?

```
  Dim s1 = {"a", "b"}
  Dim s2 = {"c", "d"}
  Dim x As String()() = {s1, s2}
```

The only way to do this directly is:
```VB.NET
Dim x As String()() = {
   New String() {"a", "b"},
   New String() {"c", "d"}
}
```

Which is Ok if we want to infer x the type:
```VB.NET
Dim x = {
   New String() {"a", "b"},
   New String() {"c", "d"}
}
```

but is not necessary if we already explicitly declared the type of x.

So, what is wrong with:
```VB.NET
Dim x As String()() = {
  {"a", "b"},
  {"c", "d"}
}
```

And why we can't even use:
```VB.NET
Dim x = {
  {"a", "b"},
  {"c", "d", "e"}
}
```

**Comment by Happypig375** [comment]
```vb
Dim x As String()() = {
  {"a", "b"},
  {"c", "d"}
}
```
is a [rectangular array](https://docs.microsoft.com/en-us/dotnet/visual-basic/programming-guide/language-features/arrays/#array-size).
```vb
Dim x As String()() = {
   New String() {"a", "b"},
   New String() {"c", "d"}
}
```
is a [jagged array](https://docs.microsoft.com/en-us/dotnet/visual-basic/programming-guide/language-features/arrays/#jagged-arrays).

**Comment by VBAndCs** [comment]
```VB.NET
Dim x As String()() = {
  {"a", "b"},
  {"c", "d"}
}
```

can be a jagged array, since `As String()()` eliminates any ambiguity, and the need to repeat `New String()` at each element. This will not break any existing code, but will shorten the code. This is my code:
```

**Comment by Happypig375** [comment]
You can always define a
```vb
    Function A(Of T)(ParamArray Array As T()) As T()
        Return Array
    End Function
```
to help you.

**Comment by AdamSpeight2008** [comment]
[ Array Literal Syntax](https://docs.microsoft.com/en-us/dotnet/visual-basic/programming-guide/language-features/arrays/)

**Comment by Happypig375** [comment]
@AdamSpeight2008 You literally linked to the same page as I did lol

**Comment by VBAndCs** [comment]
Just to be clear:
```VB.NET
If Variable type is a jagged array Then
    Try Parse Array Literal as a jagged array
ElseIf Variable type is inferred Then 
    If Parsing Array Literal to multi-dimensional array succeeded Then
        Variable type is multi-dimensional.
    ElseIf Parsing Array Literal as a jagged array succeeded Then
        Variable type is a jagged array.
    Else 
        Error
    End If
Ekse
    Try Parse Array Literal as a multi-dimensional array 
End If
```

This is how I want the sepcs to be, and will try to do it some day.

**Comment by rskar-git** [comment]
@VBAndCs 

VB can do what you need, make jagged array like so:

        Dim x As String()() = {
          ({"a", "b"}),
          ({"c", "d"})
        }

**Comment by VBAndCs** [comment]
@rskar-git 
Wow. I never so this syntax before. Was it always there from beginning or added later?
Thanks.
