### ISSUE TITLE
[Proposal] Inline Enums

### ISSUE THREAD

**Issue by VBAndCs** [dotnet/vblang#526]
Many times, we just declare an enum to use it as a param type or a return value type in one function only. I suggest to declare it inline like this:

** Declaration
```VB.NET
Sub Foo1(x As Order[First, Second, Last])
    Select Case x
         Case Order.First

         Case  Order.Seceond

         Case Else

    End Select

End Sub
```

``` VB.NET
Function Foo2() as MyType[Tye1, Type2, Type3]
    '……..
    if cond then return MyType.Type1

    return MyType.Type2
End Function
```

** Rules
- VB will declare Order and MyType enums at the class containing their methods. 
inline enum has the same access modifiers of its method. 
- The type of inline enum is always Integer, and its constants can't have explicit numeric values. They will always have 0, 1, 2…. implicitly.
- Inline enum can't be a flag. It is just a fast coding of the very common enum use case.

Finally, use inline enum outside its method as a normal enum:

```VB.NET
  Call Foo1(Order.Last)
  Dim t = Foo2()
  If t = Order.type1 then
```

**Comment by rskar-git** [comment]
Not very compelling. What can be done today is just fine:

    Enum Order : First : Second : Last : End Enum
    Sub Foo1(x As Order)
        Select Case x
            Case Order.First

            Case Order.Second

            Case Else

        End Select

    End Sub

    Enum MyType : Type1 : Type2 : Type3 : End Enum
    Function Foo2() As MyType
        If cond Then Return MyType.Type1

        Return MyType.Type2
    End Function

**Comment by DualBrain** [comment]
@rskar-git I have to say... I've never tried writing Enums that way... that is AWESOME!  It makes perfect sense, just never thought of looking at it that way.

**Comment by DualBrain** [comment]
As for the suggestion... I'd find it hard to believe that I would ever leverage what is being proposed.  The point of using Enums is to create readability and improve reliability... it's not something that is "local" (inline) and deserves to be well defined.

**Comment by CyrusNajmabadi** [comment]
Closing out as there is already a way to write things this succinctly (though it's debatable if one *should* write things htat way) :)
