### ISSUE TITLE
Towards xsd-based auto-completion: An html5 CompletionProvider for XML Literals

### ISSUE THREAD

**Issue by VBAndCs** [dotnet/vblang#527]
I added a VbXmlCompletionProvider to [this repo](https://github.com/VBAndCs/Xml-Literals-Completion-Provider)
You can add the two files to your Roslyn fork, in the folder `Completion/CompletionProviders` in the project `Microsoft.CodeAnalysis.VisualBasic.Features`
It will provide HTML5 auto completion in VB.NET XML Literals, but only inside the `<vbxml></vbxml>` tag. 
I did this for two reasons:
1. not to mess with other xml literals that doesn't deal with html.
2. to support [Vazor](https://github.com/VBAndCs/Vazor).

I will make a VSIX for this to allow install it as a VS extension (in progress now), but my aim from publishing this, is to allow contributors to build upon to provide a generic XML literals completion provider, based on the xsd that user supplies in the context as this missing feature was [described in the docs](https://docs.microsoft.com/en-us/previous-versions/visualstudio/visual-studio-2013/bb531325%28v%3dvs.120%29#enabling-xml-intellisense-in-visual-basic)

**Comment by VBAndCs** [comment]
And here is the [VSIX installer](https://github.com/VBAndCs/Vazor/blob/master/vbxmlCompletionProviderVSIX.zip?raw=true) to add this CompletionProvider to your VS as an extension:
Give it a tr, but notice it provide auto completion for HTML5 in VB.NET XML literals only inside vbxml tags:
```XML
<vbxml>
   <!—auto completion for HTML 5 is available here -->
</vbxml>
```
Feedback is appreciated:
https://github.com/VBAndCs/Vazor/issues

**Comment by VBAndCs** [comment]
To do:
1. [ZML](https://github.com/VBAndCs/ZML) auto completion.
2. Tag helpers auto completion. 
3. Also I may reinvent tag helpers to be more suitable VB.NET and XML literals. This will eliminate the need for Razor engine entirely which means I can drop the Virtual file provider, and process vbxml totally in VB.NET (Real Vazor).

**Comment by VBAndCs** [comment]
I told the whole Vazor story here: https://github.com/VBAndCs/Vazor/blob/master/A-Vazor-story.md

**Comment by CyrusNajmabadi** [comment]
This doesn't seem to be an issue for the vblang repo.  Closing out.
