### ISSUE TITLE
To be able to debug static variables

### ISSUE THREAD

**Issue by riov** [dotnet/vblang#536]
There is an old bug that does not allow you to debug static variables in VS. Can I please ask you to vote on this issue so that it gets fixed? [Link](https://developercommunity.visualstudio.com/content/problem/949116/static-variables-cannot-be-debugged-in-visual-basi.html).

**Comment by VBAndCs** [comment]
I voted up, but personally, I stopped using static variables for many years. It is a bad habit, and causes a headache to reset the static var and control its behaviour. This involves writing some if statements or, using a reset param or whatever.

**Comment by rskar-git** [comment]
@VBAndCs 

Static variables do have one interesting feature: They do a (thread-safe) lazy load of their initializers.

In other words, `Static x As Date = Now` works very differently from `Static x As Date : x = Now`.

    Function Foo1() As Date
        ' This will hold steady
        Static x As Date = Now
        Return x
    End Function
    Function Foo2() As Date
        ' This will change with each call
        Static x As Date : x = Now
        Return x
    End Function

    MessageBox.Show($"Now: {Now}")
    For i = 1 To 10
        MessageBox.Show($"Foo1:{Foo1()}  Foo2:{Foo2()}")
    Next

This makes them handy for `ReadOnly Property` or `Function` scenarios where you want a `Class` or program to load a value that is then held steady for its entire lifetime.


    Class Fooey
        ReadOnly Property StartupTime As Date
            Get
                Static Value As Date = Now
                Return Value
            End Get
        End Property
        Sub New()
            With StartupTime() : End With
        End Sub
    End Class

    MessageBox.Show($"Now: {Now}")
    Dim A1 As New Fooey()
    Threading.Thread.Sleep(2000)
    Dim A2 As New Fooey()
    MessageBox.Show($"A1:{Foo1()}  A2:{Foo2()}")

Obviously, these are simplistic examples, but if it were something like a database query or networked request or machine dependent lookup then it could be of more interest.

**Comment by riov** [comment]
Some users report that they do not experience this issue. Can you please report back if you can debug static variables in VS or not?

**Comment by VBAndCs** [comment]
I tried it in VS.NET 2019 (ver 16.5.5) on bith win 7 (x86) and win 10 (x64), and it is true:
> error BC30451: 'x' is not declared. It may be inaccessible due to its protection level.

**Comment by CyrusNajmabadi** [comment]
Closing out. This is not a vblang issue. Feel free to file this over at dotnet/Roslyn. You can also contribute a fix if interested! :-)

**Comment by VBAndCs** [comment]
@CyrusNajmabadi
You can move the issue to Roslyn instead of closing it. We've seen many issues here moved from Roslyn.
