### ISSUE TITLE
[Proposal] Small Talk - like flexibility in how to manipulate the definition of the language.

### ISSUE THREAD

**Issue by AdamSpeight2008** [dotnet/vblang#552]
This isn't yet a fully fledged out proposal, but synopsis for see if further research into the this area would be beneficial.

Imagine if the language definition eg.
 * the language words,
  * the language grammar
  * the language semantics
  * the language rules
  * etc
where a fundamental core design of the language, and the VB,net was implemented using it own fundamental core concepts.

Imagine what we could achieve if, the core was that flexible.
  * Ability to modify and extend the language.
   * These abilities would also have to transferable to the language runtime.
    * It by me possible to stay "somewhat" compatible with previous versions of the language.
    * Whilst still being able to extend definitions, semantics.
       * Imagine defining a new `method prefix` say `ProceduceEvents` to assist in the production of XAML based code.
       * Essentially we give specific information and context to the compiler, that it can use to manipulate the compilation to automatically generate the "boilerplate` coding, that raises the XAML events.
       * Eg `Superpower Snippets`
       * Eg `Embedded Templates` that are "autowired in" and "live-plugin compatible" in to **Superpower Snippets** process or system.
      * In essences the Visual Basic Compiler itself flexes and changes to the programmers will, become as powerful as the programmer requires. Yet can stay simple for beginner to the language. As the programmer become more skilled in the language, the language itself levels up, give you access to more features and capabilities. It sort of learns the you (the programmer can respect the power that these unlocked skill provide, the programmer can decide if to use them for them Light side or the Dark side.

**Comment by CyrusNajmabadi** [comment]
Closing this out as this does not actually specify an issue or an actual request for a change in the language.
