### ISSUE TITLE
LinQ necessary enhancements

### ISSUE THREAD

**Issue by VBAndCs** [dotnet/vblang#576]
Using EF6, I needed to get a result from db, like this:
`dim r = (from a in …… select a.ID, a.Name).ToList`
Then I wanted to append a value (not from db) to r, containing an ID and a Name
`r.Append(new with {.ID = ID, .Name = Name})`
the first issue here, is that we can't create a new instance of an anonymous type, and there is no implicit conversion between anonymous types even they have the same field types. So, I suggest to:
1. infer the anonymous type from context and crate a new instance of it like this:
`r.Append(new with {ID, Name})`
here, there is no field names, so, this means to use the inferred anonymous type.

2. implicit conversion between anonymous types if individual values types are matched or can be casted.

No. I tried to workaround by using Tuples: 
`dim r = (from a in …… select (a.ID, a.Name)).ToList`
`r.Append((ID, Name))`

This would be grate, but LinQ gave me an exception, because it can't convert expression trees containing tuples to SQL! I don't know if this is an EF6 issue or a VB one, but even it is related to EF6, vb can fix it by treating the tuple expression as if it was an anonymous type when crating the expression tree, so by this trick, the SQL can be generated.

Currently, the solution is to create a structure to hold the results instead of the anonymous type. I didn't try it, but I think it should work with Ef6. But if it doesn't work, so, vb should make it work too!

I also can manually convert the anonymous list to a tuple one then append to it. This can be time consuming for long lists, and extra unnecessary code. 
I used another way by dealing with the id and name as a new separate list, and converted the code that processes the list to a local sub (by using lambdas of course since no local function in VB)

My conclusion here:
Everyday, I need a time consuming, or code-complicating workarounds in VB and C#, because many useful features added to the lang are not completed or refined. People asked for these enhancements overtime, but they have low priority against new features the language want. and the team was satisfied that there are workarounds and the machine is working. Overtime, small issues like these combine in an unexpected ways, to create such frustrating situations, that makes vb or C# code turn out longer, less readable or less efficient.
This is why I always ask for a smart language, not a workarounds language.

**Comment by Happypig375** [comment]
What about you do the work to implement this in the VB compiler?

**Comment by VBAndCs** [comment]
I hope. But this needs a deep knowledge about Roslyn that I am trying to acquire in last 2 years, and a lot of time. I am gathering all my suggestions here on the hope I can implement them myself someday. A couple of month a ago, I was studying the Small Basic source code to get familiar with compilers, and I was about to make changes to it for practice, but I suddenly got 2 projects together, that took all my free time! One of them of course is the origin of my last new issues (the other is no a VB project).

**Comment by VBAndCs** [comment]
@KathleenDollard 
I think this can belong to the `Stability` of the language that you promised to maintain. The inability to declare a new instance of anonymous type in a well known contest is certainly against language stability, isn't it?
I see this as a bug not a proposal, so, please fix it.

**Comment by zspitz** [comment]
> we can't create a new instance of an anonymous type

Please clarify. The following:
```
Dim a As New With {.Number = 1, .Text = "One"}
Dim lst = {a}.ToList
lst.Add(New With {.Number = 2, .Text = "Two"})
```
works just fine.

**Comment by VBAndCs** [comment]
It works but not in EF6 query. I returned to my code, and seems the issue coming form the keys used in the anonymous type:
```
Error	BC30311	Value of type '<anonymous type: ValidDate As Date, Amount As Double>' cannot be converted to '<anonymous type: Key ValidDate As Date, Key Amount As Decimal>'.
```

**Comment by VBAndCs** [comment]
I add the `key' to the properties, and still got the issue:
```
Error	BC30311	Value of type '<anonymous type: Key ValidDate As Date, Key Amount As Double>' cannot be converted to '<anonymous type: Key ValidDate As Date, Key Amount As Decimal>'.
```

**Comment by VBAndCs** [comment]
OK. I got it. The dg returns Decimal, and I use Double!
This is something to consider also, as I mentioned in my post: if values can be casted, so the two types are compatible and this error should not happen!

**Comment by VBAndCs** [comment]
This works now:
```VB.NET
.ToList.Append(New With {Key .ValidDate = rcvValidDate.Value, Key .Amount = CDec(rcvAmount)})
```

Which is two much code to add 2 values! I want to only write:
```VB.NET
.ToList.Append(New With {rcvValidDate.Value, rcvAmount})
```

or even:
```VB.NET
.ToList.Append(New {rcvValidDate.Value, rcvAmount})
```

**Comment by VBAndCs** [comment]
I think my pint is clear in this practical sample: Verbose code is not just a few keystrokes more, or a bad looking text to read. It is also confusing, error prone, and waste my time trying to find the exact syntax to provide. This code:
`.ToList.Append(New With {
       Key .ValidDate = rcvValidDate.Value, 
       Key .Amount = CDec(rcvAmount)
    }
)
```

is a C# strict syntax code, but no way a VB code!
VB syntax was and always should be short and uses implicit conversion (unless stated otherwise).
This syntax is a VB one:
`.ToList.Append(New {rcvValidDate, rcvAmount})`

**Comment by zspitz** [comment]
My understanding is that VB anonymous types are mutable by default:
```
Dim a As New With {.Number = 1, .Text = "One"}
a.Number = 2
a.Text = "Two"
```
which introduces another problem. If the anonymous type is mutable, the simple implementation of `GetHashCode` -- calculating a result based on the values of its' fields  -- could return different results on each call. Imagine a Dictionary or HashSet depending on such a `GetHashCode`.

C# gets around this by saying that all instances of anonymous types are immutable. But VB offers increased flexibility here, at the cost of forcing you to use the `Key` keyword for those fields which contribute to the `GetHashCode` result. And indeed, fields marked with `Key` cannot be modified.

Links:

* [Original announcement of immutability of C# anonymous types](https://docs.microsoft.com/en-us/archive/blogs/sreekarc/immutable-is-the-new-anonymous-type)
* [Reasoning behind the VB design](http://www.panopticoncentral.net/2007/05/11/mutable-and-immutable-anonymous-types-and-keys/)

**Comment by pricerc** [comment]
> OK. I got it. The db returns Decimal, and I use Double!
> This is something to consider also, as I mentioned in my post: if values can be casted, so the two types are compatible and this error should not happen!

Decimal and Double are often *not* compatible, which is why we have two distinct types. So absolutely, an error *should* happen.

**Comment by VBAndCs** [comment]
> Decimal and Double are often not compatible, which is why we have two distinct types. So absolutely, an error should happen.

This is C# talking. In vb this is OK:
```vb.net
        Dim x As Double = 0.01
        Dim y As Decimal = 1.22
        x = y
        y = x * 1.001
```

the risk is the programmers responsibility. In sql server, I used the `Numeric(10, 2)` type to control the no of digits and decimal places, so, vb used the decimal type to represent that, but my data will always be valid as decimal and double. 
but this is not the issue here. The problem will happen with any other types.

> And indeed, fields marked with Key cannot be modified.
This is not the issue here. The list has a `well known` `anonymous` type, so, the append method knows in advance that any element will be added has some fields with names and data types and keys. The simple task here is to pass just values to this type, so:
`.ToList.Append(New {rcvValidDate, rcvAmount})`
will be cleverly lowered to:
```VB.NET
.ToList.Append(New With {
       Key .ValidDate = If (rcvValidDate is Nothing, Nothing, rcvValidDate.Value), 
       Key .Amount = CDec(rcvAmount)
    }
)
```

And yes `Date = Date?` is safe in VB, but `Date = Date?.Value` is error prone and needs this starnge code to avoid the exception:
`If (rcvValidDate is Nothing, Nothing, rcvValidDate.Value)`
as assigning nothing to date will reset it to its default value!
So, why after 60 years of BASIC, can't we write vb code in VB.NET, and write such C# code wired code:
```VB.NET
.ToList.Append(New With {
       Key .ValidDate = If (rcvValidDate is Nothing, Nothing, rcvValidDate.Value), 
       Key .Amount = CDec(rcvAmount)
    }
)
```

I want my VB back. Lets rebirth this lang as it should be for a new generation.

**Comment by VBAndCs** [comment]
Note:
The reason I'm using double in the code instead of decimal, is: 
> the decimal operations take 21 times longer to execute than the double operations.

as experimented here: https://exceptionnotfound.net/decimal-vs-double-and-other-tips-about-number-types-in-net/
We have a sense that double has best performance with little precision than decimal.
I will revise the model to use the double type instead of decimal. But I will postpone this as I sometimes modify the model after modifying the db, so, this step must be in final stages.

**Comment by VBAndCs** [comment]
And better, I want to use a tuple as a constructor for the new type as I suggested in #554:
`.ToList.Append( (rcvValidDate, rcvAmount) )`
This is what supposed to happen:
1. Does method Append accept a tuple param?. No.
2. Can tuple be converted to the anonymous type? Curruntly no, but I have previous proposal to convert each to the other. Let's stuck with no here.
3. If 1 and 2 failed, then this is a tuples constructor, so, lower it to:
`New T(rcvValidDate, rcvAmount)`
where T is the runtime type of the anonymous type.
4. Since T has no constructor, convert this to initialization:
`New with {rcvValidDate, rcvAmount}`
5. Infer the exact declaration from T and adjust the previous declaration:
```
.ToList.Append(New With {
       Key .ValidDate = If (rcvValidDate is Nothing, Nothing, rcvValidDate.Value), 
       Key .Amount = CDec(rcvAmount)
    }
)
```

and we are done! I only write `(rcvValidDate, rcvAmount)` and let VB.NET do what  should be done. This is how a VB should be after 60 years of experience. Otherwise, it is fair to die in silence.

**Comment by VBAndCs** [comment]
This another example:
```VB.NET
    Function GetOperations(onDate As Date) As IEnumerable(Of (PayState As Byte, Operations As IEnumerable(Of Operation)))
        Return (From op In Me.Operations
                Where (From h In op.Check.StateHistory
                       Order By h.Date Descending).FirstOrDefault.Date = onDate
                Group By PayState = op.Check.CheckState.PayStateID
                Into Operations = Group
               ).ToList().Select(Function(x) (x.PayState, x.Operations))

    End Function
```

I need a known type to use for the return value of the function, and of course the anonymous type can't be used for this purpose. I will have a dozen of functions like that, and it will be insane to define a structure for each function!
Using Tuple would solve the issue, but the Linq containing a tuple can't be translated to SQL!
So, I had to add extra 2 steps to convert the result to a list of anonymous then convert it to a list of tuple!
This is not all. the part:
`From h In op.Check.StateHistory  Order By h.Date Descending).FirstOrDefault.Date `
is a workaround to `op.Check.StateHistory.Last.Date` because the last function can't be translated to SQL! O' really? I just did it! Can you VB.NET please learn this and do it for me the next time?
I am loosing so much time in coding, and writing a lot of unnecessary lines to do obvious things. This is a very bad experience.

**Comment by VBAndCs** [comment]
This is how I wish to write the previous function:
```VB.NET
Function GetOperations(onDate As Date) As {}
        Return (From op In Me.Operations
                Where op.Check.StateHistory.Last.Date = onDate
                Group By PayState = op.Check.CheckState.PayStateID
                Into Operations = Group
End Function
```

the `{}` tells VB to infer the return type from the return statements. VB should give error if multiple return statements have different signatures.

**Comment by zspitz** [comment]
> > Decimal and Double are often not compatible, which is why we have two distinct types. So absolutely, an error should happen.
> 
> This is C# talking.

Not everything in a programming language is either C# or VB. You do have `Option Strict On`, don't you?

---

> ```vbnet
>         Dim x As Double = 0.01
>         Dim y As Decimal = 1.22
>         x = y
>         y = x * 1.001
> ```
> 
> 
> the risk is the programmers responsibility
> ```

So why not turn `Option Strict Off` and use `Object` for everything? You want the language to verify and warn on such type errors.

Also note that this code does not compile; the last line has "BC30152: Option Strict disallows implicit conversions from 'Double' to 'Decimal'".

This doesn't seem to be something specific to Visual Basic (or C#); I think the set of widening and narrowing operations is defined at the CLR level for the relevant types.

---

> 
> ```vbnet
> .ToList.Append(New With {rcvValidDate, rcvAmount})
> ```

Although I'm not entirely sure this is a bad idea, that word _cleverly_ is a problem. What happens if someone chooses to modify the above code into this:

> ```vbnet
> Dim a = New With {rcvValidDate, rcvAmount}
> r.Append(a)

Because the anonymous type declaration means something different now, the code will suddenly fail to compile.

---

> can't we write vb code in VB.NET, and write such C# code wired code:
> 
> ```vbnet
> .ToList.Append(New With {
>        Key .ValidDate = If (rcvValidDate is Nothing, Nothing, rcvValidDate.Value), 
>        Key .Amount = CDec(rcvAmount)
>     }
> )
> ```

Actually, the C# code will be shorter, because C# has no mutable anonymous types, so no need for the `Key` keyword (and because C# syntax doesn't require the `With` keyword):

```csharp
r.Append(new {
    rcvValidDate = rcvValidDate ?? null,
    rcvAmount = (decimal)rcvAmount
}
```

Also note, that in both VB and C# you can replace your conditional `If` with null coalescing:

```vbnet
r.Append(New With {
    .rcvValidDate = If(rcvValidDate, Nothing),
    .rcvAmount = (CDec)rcvAmount
})
```

**Comment by pricerc** [comment]
> > Decimal and Double are often not compatible, which is why we have two distinct types. So absolutely, an error should happen.
> 
> This is C# talking. In vb this is OK:
> 
> ```vbnet
>         Dim x As Double = 0.01
>         Dim y As Decimal = 1.22
>         x = y
>         y = x * 1.001
> ```

try this:
```VB.Net
Dim x As Double = 123456789.0123456789R
Dim y As Decimal = 123456789.0123456789D

If Cdec(x) = Cdec(y) Then
  Console.WriteLine($"Yes: {x:0.0000000000},{y:0.0000000000}")
  
Else
  Console.WriteLine($"No: {x:0.0000000000},{y:0.0000000000}")
End If

```

**Comment by VBAndCs** [comment]
I gave up using double after this https://github.com/dotnet/roslyn/issues/48466
I always aware of the floating point errors, and I have only tow decimal digits and no division or multiplications involved, so I think it is a minimum risk. But, there is a bigger risk to loose precision of the integer part. So, Decimal it is!
But I think we need a small decimal type (8 bytes) to handle most practical cases using less time and memory.

**Comment by CyrusNajmabadi** [comment]
> It works but not in EF6 query

Closing out as this does not appear to be an issue with VB, but with an external lib.  Issues with other libraries should go to those respective projects.  Thanks!
