### ISSUE TITLE
Updated version of the Language Spec

### ISSUE THREAD

**Issue by AdamSpeight2008** [dotnet/vblang#6]
The latest version of VB.net available is VB14 (VB15 in preview) the most current version of the Language Specification is VB11. That 3 or 4 versions behind. We should really have at least the most recently released version ie VB14.

**Comment by AnthonyDGreen** [comment]
@AdamSpeight2008 Yep. We first wanted to convert the spec into markdown before updating it with the VB14 (VS2017) changes. Thanks for the reminder.
