### ISSUE TITLE
[WIP] `AnyOf` Operator

### ISSUE THREAD

**Issue by AdamSpeight2008** [dotnet/vblang#75]
# `AnyOf` Operator
*This is a generalisation of Proposal #23 to allow other usage cases.*

The `AnyOf` operator as two modes of usage, as a :=
* Binary Operator ` left AnyOf right `
* Unary Prefix Operator `AnyOf right` 

-------
## Binary Operator

This is provides the equivalent of an `=` against a single instance and collection of instance, of some type. 

**Example Usage**
Consider the following code., where we are checking the `part.Kind` is one of a set of values.
**Exisiting**
```vbnet
previousWasClass = ( part.Kind = SymbolDisplayPartKind.ClassName )     OrElse
                   ( part.Kind = SymbolDisplayPartKind.InterfaceName ) OrElse
                   ( part.Kind = SymbolDisplayPartKind.StructName )
```
What if we express that in a more operator like form.
**Proposed**
```vbnet
previousWasClass = part.Kind AnyOf {SymbolDisplayPartKind.ClassName,
                                    SymbolDisplayPartKind.InterfaceName,
                                    SymbolDisplay}
```
The code produced by both are functionally equivalent 

---------
Today this functionality (not syntax) via extension method
```
<Extension()>
Function AnyOf( p As SymbolDisplayPartKind, paramarray these() as SymbolDisplayPartKind) As Boolean
  For i = 0 To these.length - 1
    If p = these(i) Then Return True
  Next
End Function
```

------------
## Unary Operator

The primary usage target of this prefix is in `TypeOf obj Is ...` expressions.
**Existing**
```vbnet
(TypeOf obj Is T0) OrElse (TypeOf obj Is T1) OrElse (TypeOf obj Is T2) ...
(TypeOf obj IsNot T0) AndAlso (TypeOf obj IsNot T1) AndAlso (TypeOf obj IsNot T2) ...
```
**Proposed**
```vbnet
 TypeOf obj Is AnyOf { T0, T1, T2 ... }
 TypeOf obj IsNot AnyOf { T0, T1, T2 ... }
```
----------------------

## Implementation

The compiler treats them as syntactic sugar for the exist code. Just that we let the compiler build the underlying expression itself.  It then could choose to implement the expression using the operators `=` and `<>` or if the object is `IComparable/IComparable(Of T)` via `o.ComparedTo( x ) = 0` or `EqualTo( )`.

**Comment by Echo-8-ERA** [comment]
Isn't your binary operator basically the `IN` operator from SQL? `obj In collection` is more intuitive than `obj AnyOf collection` while reusing an existing keyword.
Your unary operator could also reuse the `In` keyword and from what I can tell, keeps the spirit of your  proposal intact.

**Comment by AdamSpeight2008** [comment]
@Echo-8-ERA It is just like the `In` operator from SQL.

**Comment by zspitz** [comment]
@AdamSpeight2008 

The `Is` operator already has a similar ambiguity of what goes on the right side. It can be used to compare object references:
```
Dim lst As New List(Of Integer)
Dim lst1 = l
If lst Is lst1 Then Debug.Print(True)
```
or even instances of `System.Type`:
```
Dim t = GetType(List(Of Integer))
If t Is GetType(List(Of Integer)) Then Debug.Print(True)
```
But it also has a usage as part of the `TypeOf ... Is ...`, in which case the right side uses types without the the `GetType` operator:
```
If TypeOf lst Is List(Of Integer) Then Debug.Print(True)
```
---
This could be resolved by leaving `AnyOf` exclusively for type-checking, and reusing the `In` keyword for the value-comparison usage, like @Echo-8-ERA [suggests](https://github.com/dotnet/vblang/issues/75#issuecomment-302363491):
```
If part.Kind In {SymbolDisplayPartKind.ClassName,
                                    SymbolDisplayPartKind.InterfaceName,
                                    SymbolDisplay} Then
End If
```
and extended to any IEnumerable(Of T):
```
Dim i=5
Dim range = Enumerable.Range(1,5)
If i In range Then
End If
```
Perhaps it would compile to `Enumerable.Contains`, a la the following extension methods:
```
<Extension> Public Function [In](Of T)(item As T, col As IEnumerable(Of T)) As Boolean
    Return col.Contains(item)
End Function
<Extension> Public Function [In](Of T)(item As T, ParamArray col As T()) As Boolean
    Return col.Contains(item)
End Function
````

**Comment by AdamSpeight2008** [comment]
Using `.Range(1,5)` then `.Contains(..)` over a contiguous set of values, seems to (me) inefficient 
When it could be simpler to express as a Bounds of Limits.  eg `  1 <= x <= 5 `

**Comment by zspitz** [comment]
@AdamSpeight2008 Of course, but the pattern can be extended very simply:
```
Dim i=5
Dim squares = Enumerable.Range(1,5).Select(Function(x) x*x)
If i in squares Then
End If
```

**Comment by AdamSpeight2008** [comment]
@zspitz I was thinking of an type the did represent Bounds / Limits. It could implement `IEnumerable` so it as access to the LINQ to Objects extension methods.

**Comment by tverweij** [comment]
@AdamSpeight2008 

>  TypeOf obj Is AnyOf { T0, T1, T2 ... }
>  TypeOf obj IsNot AnyOf { T0, T1, T2 ... }

This is already possible:
```
{T0.GetType, T1.GetType, T2.Gettype, ...}.contains(obj.GetType)
Not {T0.GetType, T1.GetType, T2.Gettype, ...}.contains(obj.GetType)
```

Same for:
> previousWasClass = ( part.Kind = SymbolDisplayPartKind.ClassName )     OrElse
>                    ( part.Kind = SymbolDisplayPartKind.InterfaceName ) OrElse
>                    ( part.Kind = SymbolDisplayPartKind.StructName )

```
{SymbolDisplayPartKind.ClassName, 
 SymbolDisplayPartKind.InterfaceName, 
 SymbolDisplayPartKind.StructName}.contains(part.Kind)
```

**Comment by zspitz** [comment]
@tverweij

Presumably you mean:

    {GetType(T0), GetType(T1), GetType(T2)}.Contains(obj.GetType)

But this is not quite the same. If `obj.GetType` represents a type which inherits or implements `T0`, then `TypeOf obj Is T0` would evaluate to `True`, even though `obj.GetType = GetType(T0)` would evaluate to `False`. Similarly, `TypeOf obj Is AnyOf {T0, T1, T2}` would also evaluate to `True` if `obj.GetType` would inherit/implement any of `T0`, `T1`, or `T2`.
________________________________
