### ISSUE TITLE
Design Meeting Notes for last two design meetings

### ISSUE THREAD

**Issue by AnthonyDGreen** [dotnet/vblang#76]
Reminder to upload these.

**Comment by KlausLoeffelmann** [comment]
I would like this a lot, since it would help for the discussions of #82, #83, #84, #85, #87, #88!

**Comment by AnthonyDGreen** [comment]
I'm experimenting a bit with the format. The thing I don't like about design notes is that it spreads out the discussion of an idea across the meetings where we happened to discuss them. Then the community feedback is spread out over different issues reacting to specific notes. I'm playing around with an alternate format where I append the notes pertaining to a particular idea, rather than in the notes folder. Maybe the notes will just cover the agenda and link back to the issues. It's an experiment at this time.

**Comment by AnthonyDGreen** [comment]
Added.
